### ISSUE TITLE
Consider adding .editorconfig file to exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1252]
Many of our students will be new to the .NET platform. As such, they won't be familiar with the usual conventions applied to C# code. It is possible to define the conventions in an `.editorconfig` file (see e.g. https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions?view=vs-2017#example). With the next version of Roslyn (which will be released somewhere in the near future), it will even be possible for the compiler to throw an error if one of those rules doesn't match. Maybe we should consider adding an `.editorconfig` file that defines the default .NET conventions?

Note: if we add `.editorconfig` files, we could also consider supporting the [dotnet format](https://github.com/dotnet/roslyn/tree/master/src/Tools/dotnet-format) tool, to allow users to automatically format the code.

**Comment by SleeplessByte** [comment]
FWIW, we have added said [`.editorconfig`](https://github.com/exercism/javascript/blob/master/.editorconfig) to [exercism/javascript](https://github.com/exercism/javascript/blob/master/.editorconfig) even though 2 spaces is _not_ a language standard.

Since then, we see more "sanely" indented code. Not all IDEs pick up on it, but the majority does.

**Comment by ErikSchierboom** [comment]
Good to hear! I am sort of hoping for the same result.

**Comment by ErikSchierboom** [comment]
@SleeplessByte I've taken a quick peek at the exercism/javascript repo, and am I correct in seeing that you've added the .editorconfig file to the repository itself, not to the exercises? Or is is automatically added somehow (if so, how)?

**Comment by SleeplessByte** [comment]
@ErikSchierboom you're correct -- I'm just testing it out for the contributors + maintainers. 

In [this](https://github.com/exercism/javascript/pull/638/files#diff-49c0833c6ec28bcb649f0236b8f33740) proposal you can see us copying over "main repo config" to each exercise! First for `.eslintrc` and `babel.config` but that would work as well.

**Comment by ErikSchierboom** [comment]
Ah nice! Now I just have to think on how specific I want to be in the `.editorconfig` file.

**Comment by SleeplessByte** [comment]
I think spaces vs tabs and the size of the `.cs` files would be a great first step!

**Comment by mrtank** [comment]
We could also support Resharper configs. They are very deep in details.

**Comment by ErikSchierboom** [comment]
> I think spaces vs tabs and the size of the .cs files would be a great first step!

What do you mean by size? Number of lines? Number of classes?

> We could also support Resharper configs. They are very deep in details.

They are, but I must admit I'm hesitant to introduce ReSharper-specific settings. Furthermore, there are already many, many settings available: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#language-code-styles

Ideally, I'd like to keep the editorconfig file relatively simple. Some things I'd also like to _not_ enforce, as it can be very valuable to have a (automated) mentor comment on these things (like var vs explicit type).

**Comment by SleeplessByte** [comment]
> What do you mean by size? Number of lines? Number of classes?

tabsize / number of spaces.:

```.editorconfig
indent_style = space
indent_size = 5
```

**Comment by ErikSchierboom** [comment]
Ah right. What a horrible suggestion by the way, an indent size of 5 ;)

**Comment by robkeim** [comment]
We've already got an .editorconfig file at the root here:
https://github.com/exercism/csharp/blob/master/.editorconfig

I think what we need is a script to copy this file to all of the directories that contain a project so that when a student clones a specific exercise they get the editorconfig file as well.

Then we need to tweak the settings to conform with what we want.

Am I understanding this right?

**Comment by robkeim** [comment]
Or maybe we want to have a different .editorconfig file that we use internally for the project compared to the one that we provide for students.

**Comment by ErikSchierboom** [comment]
> Or maybe we want to have a different .editorconfig file that we use internally for the project compared to the one that we provide for students.

In this case, I think we do want a different .editorconfig file. as our existing one also says things about line endings and *.Cake and *.ps1 files. 

The main goal of adding the .editorconfig file is to help students learn the default coding standards in a non-obtrusive way. As part of this process, I think we should set the notification level of most editorconfig settings to at least show up as part of the build (meaning they should not be set to the "suggestion' level I think. What do you think about having these styling issues be included in the build output?

As there are so many settings, maybe we can have a discussion which settings to include for the students' editorconfig files?

I think I'd like to see:

```
[*.{cs,vb}]
indent_style = space
indent_size = 4

dotnet_style_qualification_for_field = false
dotnet_style_qualification_for_property = false
dotnet_style_qualification_for_method = false
dotnet_style_qualification_for_event = false

dotnet_style_predefined_type_for_locals_parameters_members = true
dotnet_style_predefined_type_for_member_access = true

dotnet_style_require_accessibility_modifiers = always
dotnet_style_readonly_field = true

dotnet_style_parentheses_in_other_operators = never_if_unnecessary

dotnet_style_object_initializer = true
dotnet_style_collection_initializer = true
dotnet_style_explicit_tuple_names = true
dotnet_style_prefer_inferred_tuple_names = true
dotnet_style_prefer_inferred_anonymous_type_member_names = true
dotnet_style_prefer_auto_properties = true
dotnet_style_prefer_conditional_expression_over_assignment = true
dotnet_style_prefer_conditional_expression_over_return = true

dotnet_style_coalesce_expression = true

csharp_style_expression_bodied_methods = true
csharp_style_expression_bodied_constructors = true
csharp_style_expression_bodied_operators = true
csharp_style_expression_bodied_properties = true
csharp_style_expression_bodied_indexers = true
csharp_style_expression_bodied_accessors = true

csharp_style_inlined_variable_declaration = true

csharp_prefer_simple_default_expression = true

csharp_style_throw_expression = true

csharp_style_conditional_delegate_call = true

csharp_new_line_before_open_brace = all
csharp_new_line_before_else = true
csharp_new_line_before_catch = true
csharp_new_line_before_finally = true
csharp_new_line_before_members_in_object_initializers = true
csharp_new_line_before_members_in_anonymous_types = true
csharp_new_line_between_query_expression_clauses = true

csharp_indent_case_contents = true
csharp_indent_switch_labels = true

csharp_space_after_cast = true
csharp_space_after_keywords_in_control_flow_statements = true
csharp_space_between_method_declaration_parameter_list_parentheses = true
csharp_space_between_method_call_parameter_list_parentheses = true
csharp_space_between_parentheses = control_flow_statements, type_casts
csharp_space_before_colon_in_inheritance_clause = true
csharp_space_after_colon_in_inheritance_clause = true
csharp_space_around_binary_operators = before_and_after
csharp_space_between_method_declaration_empty_parameter_list_parentheses = false
csharp_space_between_method_call_name_and_opening_parenthesis = false
csharp_space_between_method_call_empty_parameter_list_parentheses = false

csharp_preserve_single_line_blocks = true
csharp_preserve_single_line_statements = true
```

I'm a little bit unsure on what to do with `csharp_prefer_braces = true`. Personally, I don't mind if-statements without the braces, but what do you all think?

**Comment by ErikSchierboom** [comment]
I think that maybe we should also be using the editorconfig settings we will be choosing for the students, for this repository too.

**Comment by mrtank** [comment]
var vs explicit types might cause a war. `csharp_prefer_braces = true` may as well (how to follow 4 lines per function? If You follow Uncle Bob). We shouldn't add them which are so oppinionated IMHO.

**Comment by SleeplessByte** [comment]
In general we only have rules that help with making sure there are no _bugs_ and the _syntax_ is correct. Not with styling persé. JS and TS are special in some way tho because there is no 1 standard.

In this case I would probably not add the rules @mrtank mentions here for the very reason that there is no "This is how you must write C#" guide, right?

**Comment by ErikSchierboom** [comment]
I agree. I've left out both the var/explicit type and prefer braces options.

> [...] there is no "This is how you must write C#" guide, right?
Well, there is [this document](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions). And, there has been a lot of effort into making the .editorconfig support a first-class concept. In the next version of the compiler, the compiler will know about editorconfig files and such, so I expect its use will greatly increase.

As for the aforementioned rules, we could also decide to "only" include the formatting rules, not the semantic, language-usage rules. What do you think @robkeim?

**Comment by robkeim** [comment]
I think including semantic, language-usage rules is another learning opportunity for students to get feedback on their code before their code even winds up on Exercism for review. If students really don't want to follow them, the rules aren't blocking so they could always ignore them and continue working.

The only hesitation I would have with having so many rules is are they going to be overwhelming for students? I think the answer is probably no because most of the rules will probably never be hit (ex: casting, naming of private local members, lambdas) given how most of the exercises are small functions and don't even use classes.

**Comment by mrtank** [comment]
> most of the rules will probably never be hit

That, and the fact, that students most likely won't notice, that the config is doing it's job. I mean who will open the .editorconfig?

**Comment by ErikSchierboom** [comment]
Thanks for the response @robkeim and @mrtank! Let's just give things a go and see how they turn out.

**Comment by Mehni** [comment]
I've used it for a few exercises now, and there are two downsides I experience as a student.

-  The "messages" window of my IDE shows a lot of false positives because the unit tests don't adhere to the suggested style in the .editorconfig.
- The config suggests using `var` for things like `for (var i = 0; i < length;)`. `var` for whatever comes out of a LINQ query? Sure. `var` for an int? That's where I prefer seeing explicit types.

![image](https://user-images.githubusercontent.com/27952749/55077724-be54f280-5098-11e9-9056-5f859e7da218.png)

**Comment by SleeplessByte** [comment]
@ErikSchierboom You could _exclude_ the test files for now.

**Comment by ErikSchierboom** [comment]
@Mehni Thanks for the feedback, that is incredibly helpful! About the `var` suggestion, that is a mistake on my part. I'll fix it soon! 

@SleeplessByte how do you exclude files in .editorconfig files?

**Comment by SleeplessByte** [comment]
You can't really, because [this](https://github.com/editorconfig/editorconfig/issues/228) has never been implemented, but if I recall correctly, you _could_ probably do:

```.editorconfig
[*Test.cs]

all=none
the=none
rules=none
set=none
to=none
none=none
```
