### ISSUE TITLE
Confusing method names on Triangle tests

### ISSUE THREAD

**Issue by Mehni** [exercism/csharp#1253]
See: https://github.com/exercism/csharp/blob/e10ee93f61935c55388f7b510ad4852a684a96d4/exercises/triangle/TriangleTest.cs#L14

All [Test] method names in the Triangle exercise start with "returns true if ..." even if the method is expected to return false.

**Comment by ErikSchierboom** [comment]
Hi! The test names that we use are automatically generated from a source file that is shared between the various exercism tracks. The source for this specific exercise can be found [here](https://github.com/exercism/problem-specifications/blob/master/exercises/triangle/canonical-data.json). Could you create an issue or pull request in [that repository](https://github.com/exercism/problem-specifications/issues)? When a pull request has been merged there, let us know, and we can regenerate the corresponding C# test cases.

**Comment by Mehni** [comment]
Will do.

**Comment by Mehni** [comment]
The pull request was merged as commit https://github.com/exercism/problem-specifications/commit/c652ec2529486b87e7786073cf62121f6aa9a8a9.

**Comment by ErikSchierboom** [comment]
@Mehni Thanks for letting me know! I've created a [PR](#1257).
