### ISSUE TITLE
Consider replacing shell scripts with PowerShell

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1255]
Currently, we have two versions of our scripts:

- A Unix shell script
- A Windows command script 

Now that PowerShell is fully cross-platform (it works nicely on my Mac), we could consider writing all our scripts in PowerShell. This would reduce some duplication and would make it easier to add new scripts, as you only have to write one version. What do you think?

**Comment by ErikSchierboom** [comment]
@robkeim @mrtank @jpreese what do you think?

**Comment by mrtank** [comment]
Hmm. I'm not really a script expert, and definitely haven't touched PowerShell much. I have written some Bash files, but not much.

Tho I would like to point out some properties, which would lead the language choice:

- cross platform or not
- free or not
- is it something that we already have (these were to considerations yet)
- how much programmer use it
- evolving or not
- runtime environment needs installation or not
- (browsers have privilege to run it or not) I don't know if it's really important, or should be considered.

I would add Python to the options. IMHO it's very popular, and lot of Exercismers could contribute code in it.

**Comment by robkeim** [comment]
Thanks for putting together that list @mrtank of factors in making a language choice. I've gone ahead and tried to respond below, and it looks like they're fairly similar.

|   | PowerShell | Python |
|---|---|---|
| Cross platform? | Yes | Yes |
| Free? | Yes | Yes |
| Code already written? | Yes | No |
| How widely adopted is it? | Big in Windows ecosystem | Big |
| Continuing to evolve? | Yes | Yes |
| Runtime needs installation? | Installed by default in Windows | Yes |
| Executable in browser? | No | No |

My $0.02 is I think it makes sense from a maintenance perspective to stop trying to maintain two versions of the scripts. I don't see a whole lot of value migrating the scripts to Python given the frequency of how often we need to update them. My vote would be to consolidate to the existing PowerShell scripts.

**Comment by ErikSchierboom** [comment]
> My vote would be to consolidate to the existing PowerShell scripts.

I agree. Thanks for the input @mrtank and @robkeim!
