### ISSUE TITLE
Add script to get started with implementing a new exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1256]
We have a [GitHub template](https://github.com/exercism/csharp/blob/master/.github/ISSUE_TEMPLATE/new_exercise.md) that describes the steps to implement a new exercise. We should create a script to automate these steps where possible.

**Comment by robkeim** [comment]
Here's the PR that added a script to automate the process in the F# track: https://github.com/exercism/fsharp/pull/711
