### ISSUE TITLE
Exclude test file from .editorconfig file

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1259]
See https://github.com/exercism/csharp/issues/1252#issuecomment-477145822

**Comment by SleeplessByte** [comment]
You can't really, because [this](https://github.com/editorconfig/editorconfig/issues/228) has never been implemented, but if I recall correctly, you _could_ probably do:

```.editorconfig
[*Test.cs]

all=none
the=none
rules=none
set=none
to=none
none=none
```
