### ISSUE TITLE
Improve performance on Robot_names_are_unique

### ISSUE THREAD

**Issue by j2jensen** [exercism/csharp#1263]
Due to a [weird implementation](https://github.com/xunit/xunit/issues/1543) of Assert.DoesNotContain in XUnit, `Robot_names_are_unique` (in RobotNameTest.cs) takes much longer than it needs to. 

`Assert.False(names.Contains(robot.Name));` causes an xunit analyzer warning, but if we combine that with the next line we can get even faster behavior and avoid the analyzer warning:
```
Assert.True(names.Add(robot.Name));
```
This runs in 1.7 seconds instead of 7.3 seconds.

**Comment by robkeim** [comment]
Thanks for doing this investigation and detailed write-up @j2jensen! Would you be interested in creating the corresponding PR to fix this?

Here's where you can find that line in the project:
https://github.com/exercism/csharp/blob/ddfe60039f88fadb3ad8248e95402afe5facbd88/exercises/robot-name/RobotNameTest.cs#L48

**Comment by j2jensen** [comment]
@robkeim Done.

**Comment by j2jensen** [comment]
After further testing, I'm realizing that the test execution time is around 1.67 seconds when I'm running a single test that does absolutely nothing. So this change makes an even bigger difference, proportionately, than I'd thought.

**Comment by robkeim** [comment]
Thanks a lot for taking care of this @j2jensen! 👍
