### ISSUE TITLE
Order of introduction of bitwise operations

### ISSUE THREAD

**Issue by Mehni** [exercism/csharp#1265]
Bitwise operations are first introduced in the main track by Allergies, yet the Secret Handshake side exercise is unlocked before it (by Hamming). Allergies provides a more gentle introduction to bitwise operations than Secret Handshake does, and due to the abstract nature of the topic I believe mentoring can greatly help.

My primary motivation is the understanding that new concepts should be introduced in the main track before the side track.

I'll gladly PR the appropriate file.
https://github.com/exercism/csharp/blob/master/config.json#L554

**Comment by ErikSchierboom** [comment]
This is, once again, a great evaluation! It is absolutely wrong that secret-handshake is available before allergies. We'd totally welcome a PR. I think it would make sense to have allergies unlock secret-handshake, as students can then further practice bitwise operations.
