### ISSUE TITLE
Remove default `null` value in TwoFer stub

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1268]
The [two-fer stub implementation](https://github.com/exercism/csharp/blob/master/exercises/two-fer/Example.cs) defines the `input` parameter as having a default value of `null`. This is problematic, as we really don't want the second exercise in the track teach about nullability (which is a hard concept). It also means that we are already steering people towards a specific solution, namely one where the default value is `null`. As such, many students never even consider changing the default value, which is actually the most elegant solution (`input = "you"`). We thus lose the option to teach students about default values, which really is a missed opportunity.

Side note: we could also rename `input` to `name` while were at it (in a separate commit).

**Comment by iHiD** [comment]
So a stub like this?

```csharp
using System;

  public static class TwoFer
  {
      public static string Name()
      {
      }
  }
```

> Side note: we could also rename input to name while were at it (in a separate commit).

I'd consider naming the method to `two_fer` if you do this, else both the method and the param will share a name.

**Comment by ErikSchierboom** [comment]
I was thinking of a solution like this:

```csharp
using System;

  public static class TwoFer
  {
      public static string Name(...)
      {
      }
  }
```

So with ellipsis in place of the parameter. If we were to provide a parameterless constructor, I think this would lead people to perhaps use function overloading, which would be a learning option too. In fact, it might even be a more natural learning progression, as default parameters did not always exist, and one had to use overloading then.

> I'd consider naming the method to two_fer if you do this

The .NET naming conventions require PascalCase, which would mean that the method itself would be named `TwoFer`. This is not allowed though, as a member cannot have the same name as its class. However, not providing the parameter solves this :)

I think the new stub should be:

```csharp
using System;

public static class TwoFer
{
    public static string Name()
    {
        throw new NotImplementedException();
    }
}
```

**Comment by iHiD** [comment]
That sounds like a good conclusion to me!

I'm not a huge fan of `Name` as the method name because it doesn't really say what it does. I'd suggest like `Speak` or something. But this isn't my track :)

**Comment by ErikSchierboom** [comment]
I quite like `Speak`!
