### ISSUE TITLE
Can't start Hello world project as it keeps asking for SDK

### ISSUE THREAD

**Issue by NobbZ** [exercism/csharp#1288]
@Jack6776 commented on [Thu Jun 20 2019](https://github.com/exercism/cli/issues/858)

Hello,

I am new to exercism so this might be a simple fix but I am completely lost. I managed to set up excersim and managed to download the "Hello world" program.

However once I try to open the C# project i get the following error: The SDK 'Microsoft.NET.sdk' specified could not be found.

I have downloaded the latest version of the SDK but the error keeps showing up. Because of this I can't even attempt the project and I am not sure what else to try now.

---

@NobbZ commented on [Fri Jun 21 2019](https://github.com/exercism/cli/issues/858#issuecomment-504405545)

As this is not related to the `exercism` CLI but rather the track specific toolchain, I'll send this issue over there.

Then you can provide additional information in the copied thread.

You'll need probably to add whether you are using Windows, Linux or Mac. Also what do you do (open which program, enter which command, etc?) when you get that error message, and what is the exact error message you see?

**Comment by ErikSchierboom** [comment]
That sounds like an installation issue. Could you open a command prompt in the project's directory and run "dotnet test"  @Jack6776?

**Comment by Jack6776** [comment]
> That sounds like an installation issue. Could you open a command prompt in the project's directory and run "dotnet test" @Jack6776?

I ran a dotnet test and it confirms that .NET core is installed. It says no project is currently in the directory.

**Comment by ErikSchierboom** [comment]
> It says no project is currently in the directory.

Hmmm weird. Could you post the contents of the directory, which files there are in that directory? And also possibly the output of running `exercism download --exercise=hello-world --track=csharp`.

**Comment by NobbZ** [comment]
> It says no project is currently in the directory.

Are you sure you used `cd` to go into the exercises directory first? If you did could you please show the contents of the folder as Erik suggested? `dir` is your friend here.

**Comment by Jack6776** [comment]
> > It says no project is currently in the directory.
> 
> Hmmm weird. Could you post the contents of the directory, which files there are in that directory? And also possibly the output of running `exercism download --exercise=hello-world --track=csharp`.

When I run this it it shows me that is successfully downloaded to my user folder. 
The folder does contains contain the exercise but when I try to open it that is when I receive the error.
![Untitled](https://user-images.githubusercontent.com/52048386/59962580-a221ef80-94e7-11e9-95bc-4fea816288f8.png)

**Comment by NobbZ** [comment]
Again, what happens when you run `dotnet test` in a terminal from *that*
folder, not anywhere else?

Jack6776 <notifications@github.com> schrieb am Sa., 22. Juni 2019, 12:17:

**Comment by Jack6776** [comment]
Hey thanks for all the help. Turn out the issue was me not opening the entire folder as a single project. I kept opening the individual C# files.

I just open the entire folder in visual studios on a whim and it worked fine

**Comment by ErikSchierboom** [comment]
That makes sense. Thanks for reporting back!
