### ISSUE TITLE
Freshly downloaded TwoFer exercise should compile

### ISSUE THREAD

**Issue by dmahnkopf** [exercism/csharp#1289]
The freshly downloaded exercise would not build & thus the first test can not be run which breaks the idea of the TDD approach of exercism. That is, how I understand it.

I don't know whether solving the compilation issues is the intent but I think they are also a little hard to come by for beginners; at least if solving them is not stated in the task description.

I suggest to...
1. ... add the missing using directive to `System` that is needed for the NotImplementedException.
2. ... add a simple `string` parameter (maybe `string input` like in the HelloWorld exercise) to the `Speak` method that is needed for the last 2 tests and won't allow the program to compile, even if they are skipped.

~Would You like me to create a PR on that?~ See my PR https://github.com/exercism/csharp/pull/1290

Edit: I see the problem with adding the "simple `string` parameter" by either making it optional or by adding a new overload as both would lead into one direction of solving the problem. Still, I would propose to add an optional parameter that is set to an empty string (`string input = ""`) as it seems to be the leanest approach to me which doesn't break compiling & testing.

**Comment by ErikSchierboom** [comment]
I've responded in the PR, but I'll add some additional thoughts here. 

> Still, I would propose to add an optional parameter that is set to an empty string (string input = "") as it seems to be the leanest approach to me which doesn't break compiling & testing.

I understand, but nowhere is it stated that one be able to start with a compiling solution. In fact, most of the languages on exercism have you started with no example at all. People just have to figure things out for themselves, so the C# track is already accommodating by providing a stub implementation file.

My main issue with adding `string input = ""` is that students will have already been pushed towards the optimal solution: setting the string parameter's default value to `"you"`. To me, this is leading them a bit too much, the students now no longer have to think as much on how to solve the exercise.

@SleeplessByte @robkeim what do you think?

**Comment by SleeplessByte** [comment]
Hello World should compile to not scare people off, Two Fer doesn't have that same requirement IMO. Stubs shouldn't be _too_ leading and I think adding a default parameter is.

**Comment by robkeim** [comment]
I also echo your thoughts @ErikSchierboom and @SleeplessByte that we shouldn't lead students in one direction or another in terms of implementation. That being said #1290 includes a missing using which I think is a good change since we don't want to break the compilation for issues that don't define one implementation over another.

**Comment by SleeplessByte** [comment]
Yes. The `using` definitely needs to be added :)

**Comment by ErikSchierboom** [comment]
> The `using` definitely needs to be added :)

Yep, which is also what I suggested in my review :)

**Comment by ErikSchierboom** [comment]
Closed by #1290.
