### ISSUE TITLE
Fix broken, auto-generated tests

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#1293]
Currently auto-generation is broken in the following exercises:

- [x] Allergies
- [x] ETL
- [x] Markdown

**Comment by ErikSchierboom** [comment]
The `etl` fix should be relatively simple, as the [change](https://github.com/exercism/problem-specifications/commit/47a0970422bd02f1f8a4d09b53fcee798d304e6d) is also relatively simple.

`allergies` too is relatively simple (see [this change](https://github.com/exercism/problem-specifications/pull/1494/files)), and means that we can use a lot less code as the format now better conforms to the standard.

**Comment by robkeim** [comment]
Thanks @ErikSchierboom for tracking down those changes, that made it really easy to make the updates!

**Comment by ErikSchierboom** [comment]
Thanks @robkeim for doing the updates!
