### ISSUE TITLE
AllergiesTest.cs giving error when run.

### ISSUE THREAD

**Issue by Mascasc** [exercism/csharp#1299]
I'm trying to do the C# exercism exercise Allergies.
When I run the usual `dotnet test`, I get the following error:
```
error CS0111: Type 'AllergiesTest' already defines a member called 'Not_allergic_to_anything' with the same parameter types 
```
There is one of these errors for every test in the AllergiesTest.cs file.
So far this is the only exercise that has given this error.

Edit: I figured out the problem.  There are several tests that all share the name 'Not_allergic_to_anything', as well as 'Allergic_to_everything'.  The test suite also expects a method called `AllergicTo`, while the provided template names this method `IsAllergicTo`.  When I changed the method names the test suite ran without issues.

**Comment by ErikSchierboom** [comment]
Yep, this is an error on our part. We'll fix it!
