### ISSUE TITLE
[Question] Do not understand a test on the Rational Numbers challenge

### ISSUE THREAD

**Issue by rwobben** [exercism/csharp#1303]
Hello, 

I have this code : 

```  
public struct RationalNumber
{
    private int Numerator;
    private int Denominator;

    public RationalNumber(int numerator, int denominator)
    {
        Numerator = numerator;
        Denominator = denominator;
    }

    public static RationalNumber operator +(RationalNumber r1, RationalNumber r2) 
    {
       var answer = new RationalNumber(r1.Numerator* r2.Denominator + r1.Denominator* r2.Numerator, r1.Denominator* r2.Denominator);
       return answer; 
    }
 ```  

and still this test fail : 

 public void Add_a_rational_number_to_its_additive_inverse()
    {
        Assert.Equal(new RationalNumber(0, 1), new RationalNumber(1, 2) + (new RationalNumber(-1, 2)));
    }

I see as answer now (0,4) instead of (0,1) 

is the test not good or did  I make a mistake ? 

Also this one makes no sense to me 

[Fact]
    public void Subtract_a_rational_number_from_itself()
    {
        Assert.Equal(new RationalNumber(0, 1), new RationalNumber(1, 2) - (new RationalNumber(1, 2)));
    }

 if you take any number and subsract it by itself, to my knowlegde you get always zero.

**Comment by robkeim** [comment]
The way to represent 0 as a rational number is 0/1, since 0/0 is undefined. So in both tests the answer is 0 as you're expecting.

**Comment by rwobben** [comment]
That could be the problem. I did not have to write the Reduce functiion
Thanks for the explanation

**Comment by robkeim** [comment]
Ok, sounds like this is resolved, so I'm going to go ahead and close the issue.
