### ISSUE TITLE
Add new beginner course video links to LEARNING.md

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1321]
As detailed in [this blog post](https://www.hanselman.com/blog/AnnouncingFreeCNETAndASPNETForBeginnersVideoCoursesAndTutorials.aspx), new beginner videos have been launched to teach about .NET and C#. We should include these in our https://github.com/exercism/csharp/blob/master/docs/LEARNING.md document.

**Comment by evanca** [comment]
@ErikSchierboom Do you need each of the videos as a separate link or one link to the video series?

**Comment by ErikSchierboom** [comment]
@evanca I'd say add the C# and .NET Core videos as separate links.
