### ISSUE TITLE
`dotnet test` for csharp/hello-world "not possible to find any compatible framework version"

### ISSUE THREAD

**Issue by Xuerian** [exercism/csharp#1330]
Following instructions to install C#, I installed .net core 3.0

Have I missed something obvious?

Documentation:
```Note: the C# track requires SDK version 2.1 or greater.```

```
Test run for C:\Users\Xuerian\Exercism\csharp\hello-world\bin\Debug\netcoreapp2.1\HelloWorld.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
. Please check the diagnostic logs for more information.

Test Run Aborted.
```

**Comment by robkeim** [comment]
Hello @Xuerian you're receiving that error because we currently haven't upgraded yet to .NET Core 3.0.

The short term fix for you to get unblocked is to install .NET Core version 2.1, and the real fixes are to:
- Update the documentation to indicate which versions are really supported
- Upgrade to support .NET Core 3.0 :)

**Comment by Xuerian** [comment]
Aha. That does make sense, thank you for letting me know.

**Comment by ErikSchierboom** [comment]
I've added an issue to upgrade to .NET Core 3.0: #1335. I'm closing this issue.
