### ISSUE TITLE
Update status of maintainers

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1345]
@burtlo @bressain @jwood803 @jpreese Just wanted to let you know that you are listed as active maintainers in the [maintainers.json](https://github.com/exercism/csharp/blob/master/config/maintainers.json) file and could possibly have missed issue #1343 being opened. If you no longer desire to be a maintainer that is perfectly fine of course. I'll mark you account as an alumnus maintainer then. If you do like to stay being a maintainer, we'd love that of course! We are working on tons of very interesting stuff, mainly the migration to v3. If you'd like to read more about v3, check the [v3 repository](https://github.com/exercism/v3). Hope to hear from you!

**Comment by bressain** [comment]
Yeah, probably best that you mark me as alumnus. Thanks!
