### ISSUE TITLE
Fix failing builds

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1367]
Builds have been failing of late, which is due to the configlet tool not being able to be downloaded. One workaround would be to retry, as the problem seems to be intermittent.

**Comment by robkeim** [comment]
I took a first stab at adding a retry here:
https://github.com/exercism/csharp/pull/1369

Unfortunately it doesn't look like my change helped reduced the failing builds. I ran 10 builds to test this with the following results:
- 3 builds failed after three attempts to download the configlet tool
- 7 builds passed without needing any retries

Another option might be to only run this flaky step of the build if the PR contains changes to config.json. I'm not sure to how to examine the contents of a PR from the build though.

**Comment by ErikSchierboom** [comment]
Thanks a lot for testing this! I've also done a bit digging and according to the [documentation](https://developer.github.com/v3/#rate-limiting), the rate limit for unauthenticated requests is 60 requests per hour. Authenticated requests makes this 5000 requests per hour. It looks like using simple basic authentication would be enough: https://developer.github.com/v3/#basic-authentication. I've asked on Slack if we can use basic authentication. I'll report back.

**Comment by robkeim** [comment]
Should we consider disabling this step of the build until the issue with configlet is resolved?

**Comment by ErikSchierboom** [comment]
We can do that. An alternative would be to include the configlet binary into the repository. I don't have a strong preference either way, but I agree that we have to get the builds working again.

**Comment by robkeim** [comment]
Alright, here's a PR to disable configlet:
https://github.com/exercism/csharp/pull/1374

**Comment by ErikSchierboom** [comment]
Great. Let's leave this issue open for when we can work on an actual fix.

**Comment by robkeim** [comment]
Sounds good!

**Comment by ErikSchierboom** [comment]
Closed by #1375
