### ISSUE TITLE
Robot_names_are_unique() passes with invalid name

### ISSUE THREAD

**Issue by mikewalker** [exercism/csharp#1409]
Using my bad version of generate_name() all tests pass. This is because generate_name was appending to the name on collisions.

To fix this I needed to add another assert since I like the test to actually fail before I fix the problem with my solution. The test should change to test for both unique and vailid.

```csharp
    [Fact]
    public void Robot_names_are_unique()
    {
        var names = new HashSet<string>();
        for (int i = 0; i < 10_000; i++) {
            var robot = new Robot();
            Assert.True(names.Add(robot.Name));
            Assert.Matches(@"^[A-Z]{2}\d{3}$", robot.Name);
        }
    }

```

**Comment by robkeim** [comment]
Thanks for reporting this issue @mikewalker! I've gone ahead and created a PR to fix this #1410
