### ISSUE TITLE
How to update config.json

### ISSUE THREAD

**Issue by aes421** [exercism/csharp#1416]
How does config.json get updated?

I added a new generator for an unimplemented exercise, but since it's not in the config.json it is skipped.

**Comment by ErikSchierboom** [comment]
@aes421 Great to hear you are working on a generator for a new exercise! The config.json file is updated manually, so for a new exercise, you should manually add a new entry. That said, we have a [add-new-exercise.ps1 script](https://github.com/exercism/csharp/blob/master/add-new-exercise.ps1) that you can run to automatically create the required files. Note that this script also scaffolds the test generator, so you might want to store that in a branch or somewhere else before running the script.

**Comment by aes421** [comment]
The generator seems super useful, but I'm getting some sort of syntax error in the copy-track-files.ps1 file.

D:\Programming\exercism\csharp\add-new-exercise.ps1 : At D:\Programming\exercism\csharp\copy-track-files.ps1:38 char:37
+ ... tem â€“Path "exercises" -Filter $filter -Directory | ForEach-Object {
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The string is missing the terminator: ".
At D:\Programming\exercism\csharp\copy-track-files.ps1:34 char:27
+ function Copy-Track-Files {
+                           ~
Missing closing '}' in statement block or type definition.
At line:1 char:1
+ ./add-new-exercise.ps1 resistor-color-duo
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [add-new-exercise.ps1], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString,add-new-exercise.ps1

**Comment by aes421** [comment]
A did a little digging and found an odd error.

The dash(-) in front of path looked a little visually different than the others, so I backspaced it and added it back.  It runs find after that.  I am going to make a PR fixing it and I will add a little section to the read me on how to scaffold a project.

**Comment by ErikSchierboom** [comment]
Thanks for working it out and fixing it! Sorry for the inconvenience.
