### ISSUE TITLE
Include fetch canonical data syncer scripts

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1425]
We should copy the `scripts/fetch-canonical_data_syncer` and `scripts/fetch-canonical_data_syncer.ps1` scripts from the [canonical-data-syncer repo](https://github.com/exercism/canonical-data-syncer) to our `bin` directory. This will enable us to use the canonical data syncer. See https://github.com/exercism/problem-specifications#track-test-data-tooling

**Comment by wolf99** [comment]
Will this be a maintenance burden?

I.e. to remember to check if there are updates in the fetcher repo before using it?

I had thought the idea of having the fetcher in a separate repo was to centralise any maintenance

**Comment by ErikSchierboom** [comment]
> Will this be a maintenance burden?

It won't. The script is very unlikely to change.

**Comment by mkushnikov** [comment]
Hi.
I'm new here but would like to contribute to the project.
What should I do once a pull request had been made?

**Comment by ErikSchierboom** [comment]
@mkushnikov Nothing really but wait for a maintainer to respond :) Unfortunately, this is issue should have been closed, as it has since been superseded. Sorry about that!

**Comment by ErikSchierboom** [comment]
@mkushnikov One issue that you could help with is https://github.com/exercism/csharp/issues/1469.

**Comment by mkushnikov** [comment]
@ErikSchierboom there are issues #1426 and #1427 linked to this one and they also marked as good-first. 
Should they be done? Or they've been already completed as well?

**Comment by ErikSchierboom** [comment]
#1427 should have been closed (I've just done that), but #1426 can be worked on!

**Comment by mkushnikov** [comment]
Thank you. 
So I'll try to do it.
