### ISSUE TITLE
Update Target Framework (Currently .NET Core 3.0)

### ISSUE THREAD

**Issue by epikkoder** [exercism/csharp#1439]
Hi,

Whenever I run tests on an exercise, I get this warning message:

`C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [{Path\To\File}]`

I'm opening an issue to see if the target framework for the exercises can be updated to a more recent one, for example .NET 5.

**Comment by ErikSchierboom** [comment]
Hi! We're planning on upgrading to .NET 5 relatively soon, probably next month.

**Comment by ErikSchierboom** [comment]
We've updated all exercises to .NET 5. The current website is in maintenance mode, so you'll see these changes once we launch v3.
