### ISSUE TITLE
Analyzer changes for properties exercise

### ISSUE THREAD

**Issue by mikedamay** [exercism/csharp#1449]
See: https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/properties/.meta/design.md for the definitive change requirements (of which an indication is provided below).

1.    If WeighingMachine.Units is not auto-implemented then the following comment should be made: "The appropriate form for a property such as WeighingMachine.Units which has no validation or other processing required is that for an auto-implemented property". - Approved with comment.

2.    If WeighingMachine.DisplayWeight has a non-private set accessor then the following comment should be made: "It is not approprirate for a property such as WeighingMachine.DisplayWeight which simply returns a value to have a set accessor. That should be removed.". - Approved with comment.

3.    If WeighingMachine.USDisplayWeight has a non-private set accessor then the following comment should be made: "It is not approprirate for a property such as USWeighingMachine.DisplayWeight which simply returns a value to have a set accessor. That should be removed.". - Approved with comment.

4.    If USDisplayWeight.Pounds has a non-private set accessor then the following comment should be made: "It is not approprirate for a property such as USDisplayWeight.Pounds which simply returns a value to have a set accessor. That should be removed.". - Approved with comment.

5.    If USDisplayWeight.Ounces has a non-private set accessor then the following comment should be made: "It is not approprirate for a property such as USDisplayWeight.Ounces which simply returns a value to have a set accessor. That should be removed.". - Approved with comment.

6.    If WeighingMachine.TareAdjustement is not an auto-implemented property then the following commen should be made: "A succinct way of implementing WeighingMachine.TareAdjustment is as an auto-implemented property with a private get accessor". - Approved with comment.

7. If WeighingMachine.TareAdjustment is an auto-implemented property but the get accessor is non-private then the following comment should be made: "A non-private set accessor is not appropriate for WeighingMachine.TareAdjustment as the instructions stipulate that the value must not be available outside the class". - Disapproved.

**Comment by Grenkin1988** [comment]
I'd like to try this

**Comment by Grenkin1988** [comment]
As I understand there is no analyzer for weighing-machine?

**Comment by ErikSchierboom** [comment]
Great! The above comments are likely outdated, as we've updated the exercise quite a bit. But the best thing to do is to look at the exemplar implementation to see what we want the student to write.

**Comment by Grenkin1988** [comment]
@ErikSchierboom Can be closed

**Comment by ErikSchierboom** [comment]
Thanks @Grenkin1988 !
