### ISSUE TITLE
[V3] Define key features

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1469]
With the [key features specification almost finalized](https://github.com/exercism/v3-docs/blob/master/anatomy/tracks/config-json.md#key-features) (except for the icons), we can now start working on them. I've taken a quick stab at them to have _something_ there, but that should not be used for more than inspiration. We can discuss the key features here, in Slack or in a PR to update the key features.

**Comment by ErikSchierboom** [comment]
The only thing that I would add to that list is a mention of C# being applicable to almost any domain imaginable:

```
{
  "icon": "features-lazy",
  "title": "Versatile",
  "content": "C# can be used for a wide variety of workloads, like websites, console applications, and even games."
}
```

**Comment by valentin-p** [comment]
## My preferred top 6

{
"key_features": [
{
"title": "Modern",
"content": "C# is a modern, fast-evolving, and feature-rich language",
"icon": "features-oop"
},
{
"title": "Object-Oriented",
"content": "Object-oriented with strong typing supported by a fast compiler and clear conventions",
"icon": "features-oop"
},
{
"title": "Versatile",
"content": "Domains include web, desktop-gui (Windows only), games, mobile, embedded and many others",
"icon": "features-oop"
},
{
"title": "Performant",
"content": "C# compares well on many benchmarks. It is particularly tuned for applications such as web",
"icon": "features-oop"
},
{
"title": "Open-source",
"content": "Almost all aspects of C# and .NET are open-source, cross-platform and supported by the community",
"icon": "features-oop"
},
{
"title": "Rich Ecosystem",
"content": "The Nuget package manager supports a vast array of libraries and tools",
"icon": "features-oop"
}
]
}

**Comment by ErikSchierboom** [comment]
These are my six preferred key features:

```json
{
  "key_features": [
    {
      "title": "Modern",
      "content": "C# is a modern, fast-evolving language with tons of great features",
      "icon": "features-oop"
    },
    {
      "title": "Versatile",
      "content": "C# can be used to build websites, console applications, games, mobile, embedded, and many others",      
      "icon": "features-lazy"
    },
    {
      "title": "Cross-platform",
      "content": "C# runs on all major platforms: Windows, MacOS, Linux, iOS and Android",
      "icon": "features-oop"
    },
    {
      "title": "Multi-paradigm",
      "content": "Although principally an object-oriented language, C# has rich support for functional programming",
      "icon": "features-oop"
    },
    {
      "title": "Managed and Performant",
      "content": "C# code is managed with fully automated memory management and high performance",
      "icon": "features-oop"
    },
    {
      "title": "Excellent Tooling",
      "content": "C# has fantastic tooling support in a wide range of IDEs/editors",
      "icon": "features-oop"
    }
  ]
}
```

**Comment by mikedamay** [comment]
I think something like "async-enabled" should be a candidate.  If you're coming from Javascript (particularly Node) and apparently "Python 3.5, Hack, Dart, Kotlin 1.1, Rust 1.39, Nim 0.9." or in fact languages that support coroutines this might have some appeal.

**Comment by ErikSchierboom** [comment]
I can see why that would be useful. Could you post your preferred key features?

**Comment by mikedamay** [comment]
My preferences rather depend on what we put in the language introduction (assuming it's not set in stone).  Hence my questions on Slack as to whether the intro page will be the only place for the features.

**Comment by ErikSchierboom** [comment]
I'm fairly sure it will be. But we could also tweak the language introduction a bit of course.

**Comment by ErikSchierboom** [comment]
@mikedamay Do you want to suggest a candidate for the "async-enabled" (which we should probably rephrase to something like "Easy Concurrency" or something like that.
