### ISSUE TITLE
Remove "skip" from exercises tests

### ISSUE THREAD

**Issue by AngryShaDoW** [exercism/csharp#1506]
What the purpose to add "skip" to tests on each exercise? Having to constantly edit a file with tests is a little tiring.

**Comment by ErikSchierboom** [comment]
Exercism favours (Practice) Exercises being completed via Test Driven Development. To achieve this, all but the first test should be skipped by default. How this is done differs between languages.

**Comment by AngryShaDoW** [comment]
Hi, thank you for your answer. I like TDD, but tools that run test display passed/failed tests (include dotnet cli), that's why I think tests without skipping are not break TDD way. Sorry for the tediousness and wasted your time, just wanted to understand.

**Comment by ErikSchierboom** [comment]
No problem, it never hurts to ask :)
