### ISSUE TITLE
Resistor Color Test for non existent color

### ISSUE THREAD

**Issue by iesoftwaredeveloper** [exercism/csharp#1508]
It is possible to submit a color that is not in the defined list of colors.  So if I were to submit a color named say "NaC" (Not a color) what should happen?  The requirements do not define what should happen if a color that is not defined is used.

Depending on the specific implementation a lot of solutions just return a default of 0 which maps to black.  That may or may not be correct.  If an Array.IndexOf is used then the color will not be found and a value of -1 will be returned.

Suggest adding a test that will validate "NaC" to better define this scenario.

**Comment by ErikSchierboom** [comment]
> It is possible to submit a color that is not in the defined list of colors. So if I were to submit a color named say "NaC" (Not a color) what should happen? The requirements do not define what should happen if a color that is not defined is used.

It is, but error handling is explicitly not in scope of this exercise. In general, most exercises won't deal with proper error handling for the simple fact that most exercises are not about learning how to do error handling. So yes, in real-world code you'd definitely included error handling, but for this exercise, we chose not to.
