### ISSUE TITLE
Add blurb to Concepts

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1538]
Add blurbs to all Concepts.

- [x] arrays
- [x] attributes
- [ ] basics
- [ ] bit-manipulation
- [x] booleans
- [x] casting
- [x] chars
- [x] classes
- [x] compound-assignment
- [ ] const-readonly
- [ ] constants
- [x] constructors
- [x] datetimes
- [x] defensive-copying
- [x] dictionaries
- [x] do-while-loops
- [ ] enums
- [ ] equality
- [ ] exception-filtering
- [x] exceptions
- [ ] explicit-casts
- [x] expression-bodied-members
- [ ] flag-enums
- [x] floating-point-numbers
- [x] for-loops
- [x] foreach-loops
- [x] generic-types
- [x] if-statements
- [ ] indexers
- [x] inheritance
- [ ] integral-numbers
- [x] interfaces
- [x] lists
- [ ] memory-allocation
- [ ] method-overloading
- [ ] named-arguments
- [ ] namespaces
- [ ] nested-types
- [ ] nullability
- [ ] numbers
- [ ] object-initializers
- [ ] operator-overloading
- [ ] optional-parameters
- [ ] ordering
- [ ] overflow
- [ ] parameters
- [ ] properties
- [ ] randomness
- [ ] readonly-collections
- [ ] regular-expressions
- [ ] resource-cleanup
- [ ] resource-lifetime
- [ ] sets
- [ ] string-builder
- [ ] string-formatting
- [ ] string-interpolation
- [ ] strings
- [ ] structs
- [ ] switch-expressions
- [ ] switch-statements
- [ ] ternary-operators
- [ ] throw-expressions
- [ ] time
- [ ] timezone
- [ ] tuples
- [ ] user-defined-exceptions
- [ ] varargs
- [ ] verbatim-strings
- [ ] while-loops

**Comment by yzAlvin** [comment]
updated list

* [x]  arrays
* [x]  attributes
* [ ]  basics
* [ ]  bit-manipulation
* [x]  booleans
* [x]  casting
* [x]  chars
* [x]  classes
* [x]  compound-assignment
* [x]  const-readonly
* [x]  constants
* [x]  constructors
* [x]  datetimes
* [x]  defensive-copying
* [x]  dictionaries
* [x]  do-while-loops
* [x]  enums
* [x]  equality
* [ ]  exception-filtering
* [x]  exceptions
* [ ]  explicit-casts
* [x]  expression-bodied-members
* [ ]  flag-enums
* [x]  floating-point-numbers
* [x]  for-loops
* [x]  foreach-loops
* [x]  generic-types
* [x]  if-statements
* [ ]  indexers
* [x]  inheritance
* [x]  integral-numbers
* [x]  interfaces
* [x]  lists
* [ ]  memory-allocation
* [x]  method-overloading
* [x]  named-arguments
* [x]  namespaces
* [ ]  nested-types
* [x]  nullability
* [x]  numbers
* [x]  object-initializers
* [x]  operator-overloading
* [x]  optional-parameters
* [ ]  ordering
* [x]  overflow
* [ ]  parameters
* [ ]  properties
* [ ]  randomness
* [x]  readonly-collections
* [x]  regular-expressions
* [ ]  resource-cleanup
* [ ]  resource-lifetime
* [x]  sets
* [x]  string-builder
* [x]  string-formatting
* [ ]  string-interpolation
* [x]  strings
* [x]  structs
* [x]  switch-expressions
* [x]  switch-statements
* [x]  ternary-operators
* [ ]  throw-expressions
* [ ]  time
* [ ]  timezone
* [x]  tuples
* [ ]  user-defined-exceptions
* [ ]  varargs
* [x]  verbatim-strings
* [x]  while-loops

**Comment by ErikSchierboom** [comment]
This is now done.
