### ISSUE TITLE
TwoFer Version downloaded from Site is not the same the one in /cSharp repo

### ISSUE THREAD

**Issue by JustJordanT** [exercism/csharp#1540]
I noticed that the TwoFer version of this exercise is not the same as the one download from the site. 

- The one from the site is using `.netcore-3.0` when trying to run you get warning messages. 
- The one from the site also has errors because the program is not using the Main method by default.

I hope this helps. Cheers!

**Comment by ErikSchierboom** [comment]
> The one from the site is using .netcore-3.0 when trying to run you get warning messages.

We're upgrading to .NET 5 when Exercism v3 is launched (will be in a couple of months)

> The one from the site also has errors because the program is not using the Main method by default.

None of the exercises do, as they're all class libraries which don't have a `Main` method. The exercises are all class libraries that are meant to run using `dotnet test`.
