### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1567]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- `docs/ABOUT.md`
- `docs/INSTALLATION.md`
- `docs/LEARNING.md`
- `docs/RESOURCES.md`
- `docs/TESTS.md`
- `exercises/shared/.docs/help.md`
- `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total..........792
✅ Successful.....765
⏳ Timeouts.........1
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors..........26

Errors in ./exercises/practice/sublist/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/system.icomparable(v=vs.110).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/system.icomparable(v=vs.110).aspx))</span>

Errors in ./exercises/practice/simple-linked-list/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/9eekhta0(v=vs.110).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/9eekhta0(v=vs.110).aspx))</span>

Errors in ./exercises/practice/diffie-hellman/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/system.numerics.biginteger(v=vs.110).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/system.numerics.biginteger(v=vs.110).aspx))</span>

Errors in ./exercises/practice/allergies/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/6a71f45d.aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/6a71f45d.aspx))</span>

Errors in ./exercises/concept/faceid-2/.docs/instructions.md
<span style="color:#ff5555">✗ alice@thecompetition.com (Unreachable mail address: alice@thecompetition.com)</span>
<span style="color:#ff5555">✗ tunde@thecompetition.com (Unreachable mail address: tunde@thecompetition.com)</span>
<span style="color:#ff5555">✗ admin@exerc.ism (Unreachable mail address: admin@exerc.ism)</span>

Errors in ./exercises/practice/accumulate/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us//library/bb383977.aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us//library/bb383977.aspx))</span>

Errors in ./exercises/practice/nucleotide-count/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/s4ys34ea(v=vs.110).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/s4ys34ea(v=vs.110).aspx))</span>

Errors in ./exercises/practice/react/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/9aackb16(v=vs.110).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/9aackb16(v=vs.110).aspx))</span>

Errors in ./exercises/concept/building-telemetry/.docs/hints.md
<span style="color:#ff5555">✗ https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-references/passing-parameters (HTTP status client error (404 Not Found) for url (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-references/passing-parameters))</span>

Errors in ./docs/RESOURCES.md
<span style="color:#ffff55">⧖ http://geekswithblogs.net/BlackRabbitCoder/archive/2015/04/02/c.net-little-wonders-amp-little-pitfalls-the-complete-collection.aspx</span>

Errors in ./exercises/concept/booking-up-for-beauty/.docs/hints.md
<span style="color:#ff5555">✗ https://csharp.net-tutorials.com/data-types/working-with-datetimes-time/ (HTTP status client error (404 Not Found) for url (https://csharp.net-tutorials.com/data-types/working-with-datetimes-time/))</span>

Errors in ./exercises/practice/word-search/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/system.tuple(v=vs.110).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/system.tuple(v=vs.110).aspx))</span>

Errors in ./exercises/practice/rational-numbers/hints.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us//library/bb383977.aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us//library/bb383977.aspx))</span>

Errors in ./exercises/practice/bank-account/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-US/library/system.decimal.aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-US/library/system.decimal.aspx))</span>

Errors in ./exercises/practice/saddle-points/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/system.tuple(v=vs.110).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/system.tuple(v=vs.110).aspx))</span>

Errors in ./exercises/practice/leap/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/system.datetime.isleapyear(v=vs.110).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/system.datetime.isleapyear(v=vs.110).aspx))</span>

Errors in ./exercises/practice/markdown/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/dn961160.aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/dn961160.aspx))</span>

Errors in ./exercises/practice/dot-dsl/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/bsc2ak47(v=vs.110).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/bsc2ak47(v=vs.110).aspx))</span>

Errors in ./exercises/practice/variable-length-quantity/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/6a71f45d.aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/6a71f45d.aspx))</span>

Errors in ./exercises/practice/palindrome-products/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/system.tuple(v=vs.110).aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/system.tuple(v=vs.110).aspx))</span>

Errors in ./exercises/concept/developer-privileges/.docs/instructions.md
<span style="color:#ff5555">✗ bert@ex.ism (Unreachable mail address: bert@ex.ism)</span>
<span style="color:#ff5555">✗ admin@ex.ism (Unreachable mail address: admin@ex.ism)</span>
<span style="color:#ff5555">✗ anders@ex.ism (Unreachable mail address: anders@ex.ism)</span>

Errors in ./exercises/practice/roman-numerals/.docs/instructions.append.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us//library/bb383977.aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us//library/bb383977.aspx))</span>

Errors in ./docs/ABOUT.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/library/bb308959.aspx (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/library/bb308959.aspx))</span>

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by yzAlvin** [comment]
I ran lycheeverse locally and found the errors are false positives from hitting websites too often, or they are dummy emails, so maybe this can be closed

**Comment by ErikSchierboom** [comment]
Great, thanks!
