### ISSUE TITLE
BookingUpForBeauty - A test class may only define a single public constructor.

### ISSUE THREAD

**Issue by johnburkert** [exercism/csharp#1575]
Tests fail in the browser editor with the default unimplemented class with the message: 

"A test class may only define a single public constructor.". 

If downloaded locally, the project has a missing reference "Exercism.Tests". 

If I remove that reference and run the tests locally with no issue and then submit, it shows up as failed with the message:

"A test class may only define a single public constructor."

![image](https://user-images.githubusercontent.com/1059055/131761452-fae9fba9-4b60-4a3f-8e0d-3818db2392b4.png)

**Comment by ErikSchierboom** [comment]
This has been fixed. There is another issue now which I'll be fixing too.
