### ISSUE TITLE
Test doesn't pass on platform even though it passes locally.

### ISSUE THREAD

**Issue by 18-F-cali** [exercism/csharp#1579]
This is the current exercise, I am working on
https://exercism.org/tracks/csharp/exercises/squeaky-clean

I am unable to pass this test case:
![image](https://user-images.githubusercontent.com/63421973/132045775-b347b554-9c0e-47de-972e-6d4529b0c85b.png)

![image](https://user-images.githubusercontent.com/63421973/132045597-52ce9f1d-6e52-4163-a08a-8bc820380c99.png)

Below is my code.

```
using System;
using System.Text;

Convert_kebab_to_camel_case();

void Convert_kebab_to_camel_case()
{
     Console.WriteLine("àḂç" == Identifier.Clean("à-ḃç"));
}


public static class Identifier
{

    public static string Clean(string identifier)
    {
        if (!string.IsNullOrWhiteSpace(identifier))
        {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < identifier.Length; i++)
            {
                if (char.IsWhiteSpace(identifier[i]))
                {
                    sb.Append('_');
                    continue;
                }
                else if (char.IsControl(identifier[i]))
                {
                    sb.Append("CTRL");
                    continue;
                }
                else if (identifier[i] == '-')
                {
                    if (i + 1 != identifier.Length)
                    {
                        ++i;
                        sb.Append(char.ToUpper(identifier[i]));
                    }
                    continue;
                }
                else if (identifier[i] >= 'α' && identifier[i] <= 'ω')
                {
                    continue;
                }
                if (char.IsLetter(identifier[i]))
                {
                    sb.Append(identifier[i]);
                }

            }
            return sb.ToString();
        }
        return string.Empty;
    }
}
```

output:
![image](https://user-images.githubusercontent.com/63421973/132046007-6e71f542-f714-4e74-8748-7f9d97eb6abc.png)

**Comment by 18-F-cali** [comment]
![image](https://user-images.githubusercontent.com/63421973/132048119-adb62dcd-1b9a-438d-918a-3b47e83ca588.png)

this works using the console program.

**Comment by 18-F-cali** [comment]
this program works using the console program though
![image](https://user-images.githubusercontent.com/63421973/132048262-fdf8c62e-e767-40f1-8b0e-6d4dc6991e11.png)

should i go ahead with the submission ?

**Comment by QuintenJ** [comment]
Same issue here as well.

**Comment by ErikSchierboom** [comment]
Interesting. I'll look at it (I'm terribly busy right now so I don't know when exactly).

**Comment by joce** [comment]
Same here, using `net5.0` as well. What framework is used to run the tests on exercism?

**Comment by ErikSchierboom** [comment]
This is now fixed! If you re-run the tests they'll now pass.

**Comment by joce** [comment]
@ErikSchierboom Thanks! 😁 Also, which PR fixes this? I'm curious to see the fix.

**Comment by ErikSchierboom** [comment]
@joce This PR: https://github.com/exercism/csharp-test-runner/pull/56
