### ISSUE TITLE
Different names for methods in online problem description and intial language stub file and test file

### ISSUE THREAD

**Issue by 18-F-cali** [exercism/csharp#1581]
![image](https://user-images.githubusercontent.com/63421973/132052978-f0cd0129-4e91-427e-8967-e3fd9c766b64.png)

Problem description has ```RemoteControlCar.Nitro();```
Initial language stub has ```RemoteControlCar TopModel()```
Test file has ```RemoteControlCar.TopOfTheLine();```

**Comment by ErikSchierboom** [comment]
Closed by #1582
