### ISSUE TITLE
Test and problem description dont match

### ISSUE THREAD

**Issue by 18-F-cali** [exercism/csharp#1583]
Problem Decription:
![image](https://user-images.githubusercontent.com/63421973/132060119-8f27a744-e58e-449a-b7e9-e93688beff91.png)

Test :
![image](https://user-images.githubusercontent.com/63421973/132060214-1e4d9e5a-45eb-48a3-b80f-bc5063b27540.png)

**Comment by 18-F-cali** [comment]
This is for https://exercism.org/tracks/csharp/exercises/booking-up-for-beauty/

**Comment by ErikSchierboom** [comment]
@18-F-cali Would you be interested in creating a PR to fix this?

**Comment by 18-F-cali** [comment]
Yes, definitely.
