### ISSUE TITLE
Football Match Reports - test and setup code don't match

### ISSUE THREAD

**Issue by Willz42** [exercism/csharp#1584]
This may be an intentional part of the exercise, but the "please don't change" pre-written class Injury has description text "A player is injured." but the test expects "A player is injured. Medics are on the field."

It's unclear if part of the exercise requires you to handle the Injury case differently than the Incident and Foul case (ie manually append " Medics are on the field." or if it's a error in the pre-written code. The two other published solutions are divided on how to handle it.

**Comment by ErikSchierboom** [comment]
This is intentional. The goal is for the `Injury` case to be handled differently in the `AnalyzeOffField` method.
