### ISSUE TITLE
Tests error "A test class may only define a single public constructor"

### ISSUE THREAD

**Issue by CairnsBit** [exercism/csharp#1586]
Track: C#
Exercise: Booking up for Beauty
Username: CairnsBit

I started the exercise on my local machine, and all the tests seemed to pass there, but after submiting it to the site, every test failed throwing the same error. A mentor suggested that the fault lies with the tests...

**Comment by ErikSchierboom** [comment]
I know what the issue is and I know how to fix it, I just have to find the time to do so :) It is not the lack of top-level statements or anything. I'll probably be able to fix it this week.

**Comment by joce** [comment]
If you're lacking bandwidth and if you could point us in the right direction, we might be able to fix that for you? A quick glance around did not allow me to figure out where the issue lies.

**Comment by ErikSchierboom** [comment]
Thanks for the offer! I'm quite a ways into solving the issue though, so there's no need. I do really appreciate the offer!

**Comment by ErikSchierboom** [comment]
This should now be fixed due to https://github.com/exercism/csharp-test-runner/pull/51

**Comment by Th3Kh3d1v3** [comment]
@ErikSchierboom This one is having problems again for the for the two tests that check the afternoon based on "DateTime.Now".

**Comment by ErikSchierboom** [comment]
@Th3Kh3d1v3 I can't reproduce. What code are you using?

**Comment by Th3Kh3d1v3** [comment]
@ErikSchierboom https://exercism.org/tracks/csharp/exercises/booking-up-for-beauty/solutions/Musaab

`using System;

static class Appointment
{
    public static DateTime Schedule(string appointmentDateDescription)
    {
        return Convert.ToDateTime(appointmentDateDescription);
    }
    public static bool HasPassed(DateTime appointmentDate)
    {
        return appointmentDate < DateTime.Today;
    }
    public static bool IsAfternoonAppointment(DateTime appointmentDate)
    {
        return appointmentDate.Hour >= 12 && appointmentDate.Hour < 18;
    }
    public static string Description(DateTime appointmentDate)
    {
        return String.Format("You have an appointment on {0}.", appointmentDate);
    }
    public static DateTime AnniversaryDate()
    {
        return new DateTime(2021, 9, 15, 0, 0, 0);
    }
}`

**Comment by ErikSchierboom** [comment]
@Th3Kh3d1v3 You're having a different issue. This issue is about all tests failing. In your case, your implementation of the `HasPassed` method is incorrect (hence the other tests all passing). Hint: you're not taking into account the current day's time.

**Comment by Th3Kh3d1v3** [comment]
@ErikSchierboom ok thanks :)
