### ISSUE TITLE
Syllabus impossible to complete due to missing concepts/learning exercises

### ISSUE THREAD

**Issue by Elavina** [exercism/csharp#1587]
https://github.com/exercism/csharp/blob/c9e85c2f09b44dcb6cc79a4abc867fa3a23f4015/config.json#L251

There's a few "impossible" concepts:
* Nullability requires non-existent Memory Allocation
* Dictionaries require non-existent Indexers
* Verbatim Strings and String Formatting require non-existent Varargs and Const Readonly

Nullability blocks Exceptions, preventing the vast majority of the rest of the tracks.

![image](https://user-images.githubusercontent.com/5093287/132270031-724ff5b7-434b-4dbf-b0e9-30cc7969d076.png)

**Comment by Elavina** [comment]
![image](https://user-images.githubusercontent.com/5093287/132270493-39e26996-896c-4d63-9ecd-a92c2f630cd8.png)

It's impossible to get past this point. Ah, Bit Manipulation is also missing.

**Comment by Elavina** [comment]
Note, you can still access the learning exercises, e.g. for Nullability if you disable Learning Mode and complete the relevant exercise. This unlocks the rest of the tree, but is clearly hacky and not the intended process..

**Comment by ErikSchierboom** [comment]
@Elavina Thanks for reporting! This will be fixed in https://github.com/exercism/csharp/pull/1588
