### ISSUE TITLE
Nullibility concept exercise - Tim From Marketing - format in instructions doesn't match format in tests

### ISSUE THREAD

**Issue by Willz42** [exercism/csharp#1592]
https://exercism.org/tracks/csharp/exercises/tim-from-marketing / https://github.com/exercism/csharp/tree/782086650efff991f61184f3c55bc173ad28955b/exercises/concept/tim-from-marketing

Instructions ask for the output to be formatted like: **"[id] - [name] - [DEPARTMENT]"** but in the test's it's looking for **"[17] Ryder Herbert - MARKETING"** (no hyphen between Id and name)

I'm happy to have a go at a PR to fix update either the tests or the instructions if appropriate.

**Comment by ErikSchierboom** [comment]
Good catch! I've just looked at the instructions and I think we should update them to something like:

```
Employee badge labels are formatted as follows: `"[<id>] - <name> - <DEPARTMENT>"`
```

I think the brackets help make it clear that they are placeholders, separate from the square brackets. What do you think?

**Comment by Willz42** [comment]
I think that's good - and would we change the tests to match, or make it:
`Employee badge labels are formatted as follows: `"[<id>] <name> - <DEPARTMENT>"`
To match the current test format?

**Comment by ErikSchierboom** [comment]
No the tests are fine. With ``"[<id>] - <name> - <DEPARTMENT>"`` I mean: replace `<id>` with the ID, `<name>` with the name and `<DEPARTMENT>` with the uppercase department.
