### ISSUE TITLE
Link to contributing guide in the README is broken

### ISSUE THREAD

**Issue by joce** [exercism/csharp#1594]
The link for the contributing guide in the [README](https://github.com/exercism/csharp/blob/main/README.md) for the track is broken.
It's pointing to https://github.com/exercism/docs/tree/master/contributing-to-language-tracks, which does not appear to exist.

**Comment by ErikSchierboom** [comment]
The correct link is https://exercism.org/docs/building. Would you be willing to submit a PR to fix this @joce?
