### ISSUE TITLE
BirdCount.CountForFirstDays() starts from wrong end of the array

### ISSUE THREAD

**Issue by mvdmolen** [exercism/csharp#1603]
Task 2 defines the order of the array as: 

**The bird counts are ordered by day, with the _first_ element being the count of the oldest day, and the last element being today's count.**

Task 5 expects the first 4 days starting from the first element, note the expected result of 14:
```
int[] birdsPerDay = { 2, 5, 0, 7, 4, 1 };
var birdCount = new BirdCount(birdsPerDay);
birdCount.CountForFirstDays(4);
// => 14
```

**Comment by ErikSchierboom** [comment]
I don't see the error to be honest. The first X days of the week are the four oldest days, meaning 2, 5, 0 and 7 which sums up to 14.

**Comment by mvdmolen** [comment]
Yep, you are right! I was confused. Thanks!
