### ISSUE TITLE
No TimeZoneInfo appears to be available

### ISSUE THREAD

**Issue by joce** [exercism/csharp#1607]
For the Beauty Salon Goes Global exercise, it appears that no time zones can be found.

I wrote the following helper function to have the code run on either Linux or Windows (based on the information provided in the README file of the exercise):

```csharp
    static string GetTimZoneString(Location location)
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            return location switch
            {
                Location.NewYork => "Eastern Standard Time",
                Location.London => "GMT Standard Time",
                Location.Paris => "W. Europe Standard Time",
                _ => ""
            };

        return location switch
        {
            Location.NewYork => "America/New_York",
            Location.London => "Europe/London",
            Location.Paris => "Europe/Paris",
            _ => ""
        };
    }
```
and all my test suite runs fine both on Windows and on WSL.

However, when I attempt to run on the Exercism website, I get the following type of error for all the test that require the use of a TimeZone string:
`The time zone ID 'America/New_York' was not found on the local computer.`

Just for fun, I attempted to remove the platform check and always return the "Windows" values, but I fared no better, getting something like:
`The time zone ID 'Eastern Standard Time' was not found on the local computer.`

I attempted to gather the list of available time zones on the system by replacing the body of the above method with this:

```csharp
    static string GetTimZoneString(Location location)
    {
        StringBuilder sb = new StringBuilder("All TZ\n");
        int cnt = 0;
        foreach (TimeZoneInfo z in TimeZoneInfo.GetSystemTimeZones())
        {
            cnt++;
            sb.AppendLine(z.Id);
        }
        sb.AppendLine($"{cnt} time zones found");
        throw new Exception(sb.ToString());
    }
```

Locally, I get a list of 141 time zones when running on Windows, and 425 when running on WSL. However this is the output I get when running on the Exercism site:

```
All TZ
0 time zones found
```

😞 

It would appear there are no time zones available. Is it something that would have to be added to the dockerfile?

**Comment by ErikSchierboom** [comment]
I merged a PR yesterday to add globalization to the Docker test runner: https://github.com/exercism/csharp-test-runner/pull/56 Did you test this _after_ that PR was merged?

**Comment by joce** [comment]
I presume that yes. The fix you mention fixed the issue I had with the capitalization of some non-latin letter in the Squeaky Clean exercise, but it doesn't appear to address the fact that no timezone info appears to be present on the system.
Also, I just reran the tests just now, and I get the same issue.

**Comment by ErikSchierboom** [comment]
>  Is it something that would have to be added to the dockerfile?

Yeah, I guess so. Would you be willing to submit a PR to fix this? https://wiki.alpinelinux.org/wiki/Setting_the_timezone mentions a package to be added.

**Comment by joce** [comment]
Err... I've never touched Docker from near or far. I know it exists and I _think_ I know what it's used for. 
What do you suggest I add to the dockerfile?
```dockerfile
RUN apk add tzdata
```
?

**Comment by joce** [comment]
@ErikSchierboom Somewhat related question: Since I started trying to complete all the exercises on Exercism v3, it's at least the 3rd where I've been unable to complete it due do some quirks of the setup. Shouldn't there be, somewhere a set of solution for all the problems that would have to run whenever a change to the infrastructure is changed to make sure the infra still supports all the exercises?

**Comment by ErikSchierboom** [comment]
> Err... I've never touched Docker from near or far. I know it exists and I think I know what it's used for.
What do you suggest I add to the dockerfile?

Just add `tzdata` at the end of this line: https://github.com/exercism/csharp-test-runner/blob/main/Dockerfile#L17

After that, please add a new test solution in https://github.com/exercism/csharp-test-runner/tree/main/test/Exercism.TestRunner.CSharp.IntegrationTests/Solutions and add a test for it here: https://github.com/exercism/csharp-test-runner/blob/main/test/Exercism.TestRunner.CSharp.IntegrationTests/TestRunnerTests.cs

**Comment by ErikSchierboom** [comment]
> Shouldn't there be, somewhere a set of solution for all the problems that would have to run whenever a change to the infrastructure is changed to make sure the infra still supports all the exercises?

There should be, but I've not yet found the time to do that. Could you open an issue on https://github.com/exercism/csharp-test-runner?

**Comment by msdeibel** [comment]
Another mentee ran into it and I opened 
https://github.com/exercism/csharp-test-runner/issues/62
The issue already has a PR in it.

**Comment by ErikSchierboom** [comment]
This is fixed in https://github.com/exercism/csharp-test-runner/pull/63

Re-running a valid solution should now pass all tests!
