### ISSUE TITLE
Wrong expected value in 2 test cases in Hyper-optimized Telemetry

### ISSUE THREAD

**Issue by 18-F-cali** [exercism/csharp#1621]
![image](https://user-images.githubusercontent.com/63421973/133880917-c2055861-ea53-4e2a-b1d7-9a56c2ced4a5.png)
But according to the range in problem description
![image](https://user-images.githubusercontent.com/63421973/133880955-a00c6cd5-65c8-4bce-9f8a-8912fc576ea9.png)

 the expected values should be 

32767?							=> 0xfe, 0xff, 0x7f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0
//unsigned						=> 0x2, 0xff, 0x7f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0 

0?								=> 0xfe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0 
//unsigned						=> 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0

**Comment by ErikSchierboom** [comment]
@18-F-cali I'm updating the instructions in #1626. It does look like there might be another issue with the tests.
