### ISSUE TITLE
Wrong Expected Values in WeighingMachine

### ISSUE THREAD

**Issue by 18-F-cali** [exercism/csharp#1629]
```cs
[Fact]
    public void Get_us_display_weight_pounds()
    {
        var wm = new WeighingMachine();
        wm.InputWeight = 60m;// no default unit supplied hence assumed kg
        Assert.Equal(132, wm.USDisplayWeight.Pounds);// 60 kg == 132.277 pounds  // **precision lost** 
    }

    [Fact]
    public void Get_us_display_weight_ounces()
    {
        var wm = new WeighingMachine();
        wm.InputWeight = 60m;// no default unit supplied hence assumed kg
        Assert.Equal(4, wm.USDisplayWeight.Ounces); // **60 kg  = 2116.44 ounces** 
    }

    [Fact]
    public void Input_pounds_and_get_us_display_weight_pounds()
    {
        var wm = new WeighingMachine();
        wm.Units = Units.Pounds;
        wm.InputWeight = 175.5m;
        Assert.Equal(175, wm.USDisplayWeight.Pounds); // **precision lost**
    }

    [Fact]
    public void Input_pounds_and_get_is_display_weight_ounces()
    {
        var wm = new WeighingMachine();
        wm.Units = Units.Pounds;
        wm.InputWeight = 175.5m;
        Assert.Equal(8, wm.USDisplayWeight.Ounces); // **175.5 pounds == 2808 ounces**
    }
```

**Comment by ErikSchierboom** [comment]
I'll look into this!

**Comment by 18-F-cali** [comment]
Am I right in my understanding and create a pull request for this ? @ErikSchierboom

**Comment by ErikSchierboom** [comment]
@18-F-cali Having done this exercise myself, it is indeed a slightly problematic exercise. I've created three issues:

- #1645
- #1644
- #1643

**Comment by 18-F-cali** [comment]
@ErikSchierboom Will be happy to.

**Comment by ErikSchierboom** [comment]
Brilliant. For #1645 it might be best if we discussed the approach before you start coding, as it involves tweaking the design.

**Comment by 18-F-cali** [comment]
Cool. How do you suggest ? @ErikSchierboom

**Comment by 18-F-cali** [comment]
I made some assumptions here: https://gist.github.com/18-F-cali/0cd6d13c531d5191b4a473f74a94791d 
as a possible solution after changes.

**Comment by ErikSchierboom** [comment]
I think I'll only have time to look at this next week, sorry.

**Comment by 18-F-cali** [comment]
Here I have added possible Tests and solution for the exercise.

**Comment by ErikSchierboom** [comment]
@18-F-cali I've forked your exercise and tried to trim down a bit more on what the original exercise was trying to do. This results in the following code:

```csharp
using System;

class WeighingMachine
{
    private int _weight;
    
    public WeighingMachine(int precision)
    {
        Precision = precision;
    }
    
    // Goal: getter-only property initialized in constructor
    public int Precision { get; }

    // Goal: auto-implemented get/set property with initial value
    public int TareAdjustment { get; set; } = 5;
    
    // Goal: explicit get/set property
    public int Weight
    {
        get
        {
            return _weight;
        }
        set
        {
            if(value < 0)  throw new ArgumentOutOfRangeException();
            _weight = value;
        }
    }

    // Goal: getter-only property with logic 
    public int DisplayWeight
    {
        get
        {
            return Weight - TareAdjustment;
        }
    }
}
```

I've made a couple of changes, mostly to simplify things which should make things easier to understand for the student and result in less variance in the solutions submitted (which is good for automated mentoring). The main things I've changed are:

- Remove the`USDisplayWeight` class
- Get rid of the units

I've added comments to the code to indicate the goal of that property. IMHO the above design is much simpler and still has the student work with the exact same property types as before. What do you think?

See https://gist.github.com/ErikSchierboom/f0a453cf9e8f2a2c03311b6796e9f31b#file-weighingmachinepossiblesolution-cs

**Comment by ErikSchierboom** [comment]
Note that the above proposal would also require some changes to the tasks and tests, but we can discuss those once we're happy with the design.

**Comment by 18-F-cali** [comment]
I agree, Your solution is better and it shows intent clearly.

**Comment by ErikSchierboom** [comment]
Thanks! As for the tests/instructions: I think they'll mostly be fairly self-explanatory. The goal is to have the student slowly build a working implementation, so that means starting with the things that don't have any dependencies and are simple to implement and then moving on to more involved tasks.

The one potentially less obvious part of my proposal is the initialization of the `TareAdjustment` to the value `5`. We could maybe having this be explained in the task using something like this: "Most weighing machines are not perfectly accurate, and tests have found that they usually have a bias towards overestimating the weight. To remedy this, implement the `TareAdjustment` property to the value `5`.

We could follow this up with a later task that allows for adjusting the tare adjustment, which could give students the opportunity to convert a getter-only property to a get-set property.

**Comment by 18-F-cali** [comment]
@ErikSchierboom Sorry for the late reply.
What do you think about this ?
# Instructions

In this exercise you'll be modelling a weighing machine.

The weight can be set and retrieved, but it can't be negative.
It is also important to ensure that our weighing machine is precise.

A tare adjustment can be applied to the weight (for instance to deduct the
weight of a container). This can be any value (even negative or a value that makes the display weight negative)
as there are doubts about the accuracy of the weighing machine and tests have found that they usually have
a bias towards overestimating the weight.

Note that:

```
display-weight = input-weight - tare-adjustment
```

You have 6 tasks each of which requires you to implement one or
more properties:

## 1. Allow the weighing machine to have a precision.

Implement the `WeigingMachine` class to have a precision property set only from the constructor:

```csharp
var wm = new WeighingMachine(precision:3);

//  => wm.Precision == 3
```

## 2. Allow the weight to be set on the weighing machine

Implement the `WeigingMachine.Weight` property to allow the weight to be get and set:

```csharp
var wm = new WeighingMachine(precision:3);
wm.Weight = 60m;

//  => wm.Weight == 60m
```

## 3. Ensure that a negative input weight is rejected

Add validation to the `WeighingMachine.Weight` property to throw an `ArgumentOutOfRangeException` when trying to set it to a negative weight:

```csharp
var wm = new WeighingMachine(precision:3);
wm.Weight = -10m; // Throws an ArgumentOutOfRangeException
```

## 4. Ensure that the weighing machine has a default tare Adjustment.

Implement the `WeighingMachine.TareAdjustment` property to have the default value as 5.

```csharp
var wm = new WeighingMachine(precision:3);

// => wm.TareAdjustment == 5
```

## 5. Allow a tare adjustment to be applied to the weighing machine

Implement the `WeighingMachine.TareAdjustment` property to allow the tare adjustment to also be set:

```csharp
var wm = new WeighingMachine();
wm.TareAdjustment = 10;

// => wm.TareAdjustment == 10
```

## 6. Allow the weight to be retrieved

Implement the `WeighingMachine.DisplayWeight` property which shows weight after tare adjustment:

```csharp
var wm = new WeighingMachine();
wm.Weight = 60m;

// => wm.DisplayWeight == 55m
```

**Comment by ErikSchierboom** [comment]
@18-F-cali That looks really good! My only suggestion would be to move some of the introduction text to the individual tasks. For example, moving the bit about the tare adjustment from the instruction text to the task. In general, it's best to explain things in the tasks and have the introduction text just setup the general context. That makes it easier for students to know what the task is about without having to scroll back.

**Comment by 18-F-cali** [comment]
@ErikSchierboom something like this ?
# Instructions

In this exercise you'll be modelling a weighing machine.

You have 6 tasks each of which requires you to implement one or more properties:

## 1. Allow the weighing machine to have a precision.

It important to ensure that our weighing machine is precise.
Implement the `WeigingMachine` class to have a precision property set only from the constructor:

```csharp
var wm = new WeighingMachine(precision:3);

//  => wm.Precision == 3
```

## 2. Allow the weight to be set on the weighing machine

Implement the `WeigingMachine.Weight` property to allow the weight to be get and set:

```csharp
var wm = new WeighingMachine(precision:3);
wm.Weight = 60m;

//  => wm.Weight == 60m
```

## 3. Ensure that a negative input weight is rejected

The weight can be set and retrieved, but it can't be negative.
Add validation to the `WeighingMachine.Weight` property to throw an `ArgumentOutOfRangeException` when trying to set it to a negative weight:

```csharp
var wm = new WeighingMachine(precision:3);
wm.Weight = -10m; // Throws an ArgumentOutOfRangeException
```

## 4. Ensure that the weighing machine has a default tare Adjustment.

A tare adjustment can be applied to the weight they usually have a bias towards overestimating the weight.
Implement the `WeighingMachine.TareAdjustment` property to have the default value as 5.

```csharp
var wm = new WeighingMachine(precision:3);

// => wm.TareAdjustment == 5
```

## 5. Allow a tare adjustment to be applied to the weighing machine

The tare adjustment can be any value (even negative or a value that makes the display weight negative)
Implement the `WeighingMachine.TareAdjustment` property to allow the tare adjustment to also be set:

```csharp
var wm = new WeighingMachine();
wm.TareAdjustment = -10;

// => wm.TareAdjustment == -10
```

## 6. Allow the weight to be retrieved

Implement the `WeighingMachine.DisplayWeight` property which shows weight after tare adjustment:
Note that:
``` display-weight = input-weight - tare-adjustment ```

```csharp
var wm = new WeighingMachine();
wm.Weight = 60m;

// => wm.DisplayWeight == 55m
```

**Comment by ErikSchierboom** [comment]
@18-F-cali Yep!
