### ISSUE TITLE
football-match-report: add test for shirt number in AnalyzeOffField method

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1636]
The `football-match-report`'s instructions mention that the `AnalyzeOffField()` method should treat any `int` as a shirt number and return the `AnalyzeOnField()` text. There are no tests to verify this behavior though.

**Comment by sanderploegsma** [comment]
Looking at the way the exercise is set up I actually think that it's confusing to have the `AnalyzeOffField()` method treat `int` as a shirt number and call the `AnalyzeOnField()` method: according to the instructions those two methods are specifically to analyze activity _on_ the field and _off_ the field, respectively.

I get that the aim of the `AnalyzeOffField()` method is to teach type guards in a `switch` statement, so maybe we can come up with a different way to treat `int` that has nothing to do with shirt numbers?

**Comment by ErikSchierboom** [comment]
The goal is indeed to have the student work with several types. We _could_ consider removing `int` from `AnalyzeOffField`, but it is actually nice to have it in there as the only value type. Maybe we could have an `int` be interpreted as the attendance (number of people in the stadium)?

**Comment by sanderploegsma** [comment]
Exactly, using a different meaning for `int` would be my preference over removing it completely. Attendance is a good suggestion: it speaks to the imagination and doesn't contain as much logic as the shirt numbers, so it doesn't require many test cases to verify the implementation.
