### ISSUE TITLE
football-match-reports: have manager task make more sense

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1639]
Currently, there is a special case for a manager without a name. This makes relatively little sense (I expect _all_ managers to have a name), but maybe there can be a second property on the `Manager` class (e.g. the club?) that can be empty, or maybe a boolean or integer (easier default values).

**Comment by sanderploegsma** [comment]
I'm thinking about how to improve this task and I like your club suggestion. Maybe we can make them print the Manager's name by default, and then in the last task ask them to append the club name if set, so printing `John Doe` (manager without club/unknown club) or `John Doe (Chelsea)` (manager with club).

I was wondering if the `nullable` concept is out of scope for this exercise? If not, the cleanest way to do this would be to make the manager's club a `string?`, but if the students haven't seen nullable reference types we can also make it an empty string.

**Comment by ErikSchierboom** [comment]
I've just checked, and the `nullability` concept has just two simple prerequisites: `if-statements` and `strings`. So I'm totally fine with adding `nullability` as a prerequisite here.
