### ISSUE TITLE
Additional step needed in local installation instructions to add nuget source?

### ISSUE THREAD

**Issue by kaije** [exercism/csharp#1674]
Hi there, I'm brand new to .NET and C#, and had some trouble getting started with the hello-world exercise.
After following the 'Installing C# locally' instructions I was unable to run 'dotnet test' for hello-world - it generated "error NU1100 Unable to resolve" errors for all of the packages referenced in HelloWorld.csproj.

I did some digging and eventually noticed that no .nuget folder had been created under my user directory. After a lot of googling, I came across [this](https://docs.microsoft.com/en-us/answers/questions/216940/dotnet-fails-to-install-tools.html) suggestion to manually add the nuget source:

![image](https://user-images.githubusercontent.com/5555792/135782980-a3341ff3-033b-4fc7-89b3-493ddcec097c.png)

I gave it a try and it did the trick (yay).

Is there perhaps a step missing from the local installation instructions? Or did I just overlook something while following them? (Apologies if this has been raised elsewhere - I did scan the open and closed issues and couldn't find anything referencing this.)

**Comment by ErikSchierboom** [comment]
This sounds like a bug somehow. There really shouldn't be any manual action, and the reason mentioned in the above comment doesn't strike me as correct, as I've installed the .NET CLI without Visual Studio more than once and never had this issue.

Could you try the instructions at https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/intro to see if they help?

**Comment by kaije** [comment]
Thanks for the reply. I followed those same instructions yesterday to install .NET, and I was able to run the starter app. It was just when I went to run the first exercise that I got the resolution errors.

I did notice the starter app project file doesn't have any PackageReference elements. Could that be why it ran okay (prior to manually adding the package source) but the first exercise didn't?

![image](https://user-images.githubusercontent.com/5555792/135989648-85e98411-c3bf-4507-8320-c3631f6850d5.png)

**Comment by kaije** [comment]
No worries if you'd like me to close this one. It sounds like no one else has been reporting similar problems, so it was probably just a one-off.

**Comment by ErikSchierboom** [comment]
> I did notice the starter app project file doesn't have any PackageReference elements. Could that be why it ran okay (prior to manually adding the package source) but the first exercise didn't?

Yep, that is totally possible. 

> No worries if you'd like me to close this one. It sounds like no one else has been reporting similar problems, so it was probably just a one-off.

I think this is wise. We can always re-open later if more people are having the same issue. 

Hope the rest of your C# journey is better!
