### ISSUE TITLE
Different function names in the exercise description and the exercise itself

### ISSUE THREAD

**Issue by sgadiyar06** [exercism/csharp#1800]
Re: this exercise https://exercism.org/tracks/csharp/exercises/bird-watcher 
The 3rd task has the function name mentioned as IncrementDayCount() but the exercise in the editor shows  IncrementTodaysCount(). The link for the exercise is https://github.com/exercism/csharp/blob/main/exercises/concept/bird-watcher/BirdWatcher.cs

**Comment by wolf99** [comment]
Thanks for identifying @sgadiyar06 
Would you like to make a pull request to reschedule over this?
It hink the instructions just need to be updated, here: https://github.com/exercism/csharp/blob/main/exercises/concept/bird-watcher/.docs/instructions.md
