### ISSUE TITLE
Confusing Instructions for Parsing Log Files

### ISSUE THREAD

**Issue by dzegel** [exercism/csharp#1809]
The instructions [here](https://github.com/exercism/csharp/blob/50711b595c3a3c66fea07b3e03bfb8ea262e2206/exercises/concept/parsing-log-files/.docs/instructions.md#3-count-the-number-of-lines-containing-a-password) are quite confusing. If first explains that a log line is considered to contain a password if it has the term "password" followed by a space and then another word, and then the problem asks you to find passwords inside quoted text which would imply that you need to find the word "password" followed by a space and another word between quotes. However, the example and test cases provided indicates that you need to find the word "password" inside quoted text irrespective of if there is a word after it and irrespective of if there is any whitespace before or after "password".

**Comment by ErikSchierboom** [comment]
I agree that the instructions are not very clear (nor is the example). Are you interested in improving the instructions?

**Comment by dzegel** [comment]
sure, is there a process for this beyond just making a PR?

**Comment by ErikSchierboom** [comment]
I think in this case we probably want to discuss how to fix this in this issue first. Once we've agreed on that, you can submit a PR. Would that work for you?

As for what we should do to improve this, I think we need to make the instructions clearer. The goal of that particular task is to have the student learn about character classes and negations, as well dealing with multiple matches. The exemplar implementation uses this regex: `@"^.*""[^\\""]*password[^\\""]*"".*$"`. I think that could be simplified to `@"""[^\\""]*password[^\\""]*""" (and maybe more). The instructions should then mention that a password is a line with the word password between double quotes, possibly with leading and or trailing characters. Or something like that.

**Comment by dzegel** [comment]
To summaries seems to me these would be useful changes:
1. Update instructions:
   - removing the explanation about passwords followed by another word
   - explain that the goal is to identify lines with the word `password` (case-insensitive) found between quotation marks, possibly with any other content around `password`.
   - add an example log line that does not contain the word `password` in it
2. Simplify the regex in the exemplar implementation.
3. Add a log line to the `AreQuotedPasswords` test that does not contain the word `password` in it.

That said I don't see this exercise as requiring the usage of negations in regex. If that is the goal then I would suggest updating the exercise to require returning content between quotation marks that includes the word `password`. As it is the log line `some " stuff " and some password " and some" other stuff` would pass with or without the negations in the regex but the negations would be required to return ` and some password ` instead of ` stuff " and some password " and some `

**Comment by ErikSchierboom** [comment]
Your summary is right on the mark. Let's leave the negations for now and possibly come back to that later.

**Comment by dzegel** [comment]
ok I'll create a PR when I have some time.
