### ISSUE TITLE
Upgrade to .NET 6

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1810]
With .NET 6 released, we should be updating all exercises to .NET 6. This will allow students to use C# 10.

Note that we should make sure that the [csharp-test-runner](https://github.com/exercism/csharp-test-runner/), [csharp-representer](https://github.com/exercism/csharp-representer/) and [csharp-analyzer](https://github.com/exercism/csharp-analyzer/) all work. We likely want to update them to .NET 6 too.

**Comment by andrerfcsantos** [comment]
Complete C# noob here, but this might help? https://dotnet.microsoft.com/platform/upgrade-assistant

**Comment by ErikSchierboom** [comment]
Yeah that's a nice link. Upgrading is actually really simple though, which we can do with just a search/replace :)
