### ISSUE TITLE
interest-is-interesting: instruction clarification

### ISSUE THREAD

**Issue by dzegel** [exercism/csharp#1814]
This may be nitpicky but the instructions here do not mention compounding interest which I would have expected it to do. I think most coders would be familiar with compounding interest but I don't know if the entire target audience can be assumed to have that background.
https://github.com/exercism/csharp/blob/main/exercises/concept/interest-is-interesting/.docs/instructions.md#4-calculate-the-years-before-reaching-the-desired-balance

Anecdotes:
- When I did this exercise I was initially unsure of if I was supposed to account for compounding interest simply because it was not mentioned. I did quickly figure out what the requirements are by checking the tests but I feel like ideally you shouldn't have to see the tests for clarification.
- I'm mentoring someone's solution to this exercise and they seemed to not realize that they needed to account for compounding interest.

**Comment by ErikSchierboom** [comment]
Thanks for bringing this up! Would you be willing to submit a PR to help clarify this?

**Comment by dzegel** [comment]
Sure, I'm thinking of just mentioning that you need to account for annually compounding interest and providing a link to one or more educational resources to explain compounding interest if the user needs it.

these are some resources I found that seem clear and simple:
- https://tutorial.math.lamar.edu/classes/alg/ExpLogApplications.aspx
- https://granite.pressbooks.pub/math502/chapter/simple-and-compound-interest/
- https://www.khanacademy.org/economics-finance-domain/core-finance/interest-tutorial/compound-interest-tutorial/v/introduction-to-compound-interest

Thoughts?

**Comment by dzegel** [comment]
would the docs on compounding interest go in the introduction section?

**Comment by ErikSchierboom** [comment]
Yes, this additional explanation would go in the introduction.md. We prefer not to link to external resources in the introduction.md. I think you can probably explain this in one or two sentences?

**Comment by dzegel** [comment]
sure can do, i'll get to a PR when i have some time

**Comment by dzegel** [comment]
BTW I'm fine with not adding external links but I've definitely encountered exercises with external links, what are the guidelines around including external links?

**Comment by ErikSchierboom** [comment]
Quoting [the docs](https://exercism.org/docs/building/tracks/concept-exercises#h-file-docs-introduction-md):

> Links should be used sparingly, if at all. While a link explaining a complex topic like recursion might be useful, for most concepts the links will provide more information than needed so explaining things concisely inline should be the aim.

**Comment by dzegel** [comment]
https://github.com/exercism/csharp/pull/1825
