### ISSUE TITLE
Suggesting FluentAssertions

### ISSUE THREAD

**Issue by dzegel** [exercism/csharp#1828]
I'm not sure if this is the correct repo to raise this issue so please direct me to the right place if this is not it.

Due to the way the [tests in this exercise](https://github.com/exercism/csharp/blob/main/exercises/practice/go-counting/GoCountingTests.cs) are implemented I had to jump through a couple of hoops to make them pass. You can see [my solution here](https://exercism.org/tracks/csharp/exercises/go-counting/solutions/dzegel) where I have comments explaining that I had to sort the elements in the output `IEnumerable`s (though there does not seem like there should be such a requirement) and have `IEnumerable`s implemented specifically as arrays.

I think a good solution to this is to use FluentAssertions (see https://fluentassertions.com/) which is a great library to make testing easier.
```cs
var actual = sut.Territories();
var expected = new Dictionary<Owner, (int, int)[]>
{
    [Owner.Black] = new[] { (0, 0), (2, 0) },
    [Owner.White] = Array.Empty<(int, int)>(),
    [Owner.None] = Array.Empty<(int, int)>()
};

// FluentAssertions does deep smart comparisons with very little effort
actual.Should().BeEquivalentTo(expected);

// doing this stuff is very brittle
Assert.Equal(expected.Keys, actual.Keys);
Assert.Equal(expected[Owner.Black], actual[Owner.Black]);
Assert.Equal(expected[Owner.White], actual[Owner.White]);
Assert.Equal(expected[Owner.None], actual[Owner.None]);
```

It seems that this particular exercise [comes from the problem-specifications repo](https://github.com/exercism/problem-specifications/blob/main/exercises/go-counting/canonical-data.json) which as I understand it is used to auto generate the code in the csharp repo. I'm not familiar with how that works so if someone could point me in the right direction perhaps I could try and dig into see how it could be adapted to utilize FluentAssertions.

Is a change that would be considered?

**Comment by ErikSchierboom** [comment]
> Is a change that would be considered?

While I appreciate the proposal, it would mean updating all the exercises, and I feel link this is more of an exception use case than the norm. That said, I do agree that depending on the ordering here is bad, but I think we can make this better by not using an array but instead to use `HashSet`. I've just checked, and there the `Assert.Equal` call works fine if the order in which they're added is different. Would you be interested in updating the exercise to use HashSet?

**Comment by dzegel** [comment]
i don't mind taking a crack at it but as I understand it the code is auto generated in a way I'm not familiar with so you'll need to point me in the right direction.

**Comment by ErikSchierboom** [comment]
That is correct. The source of the generator can be found here: https://github.com/exercism/csharp/blob/main/generators/Exercises/Generators/GoCounting.cs
The docs can be found here: https://github.com/exercism/csharp/blob/main/docs/GENERATORS.md

**Comment by dzegel** [comment]
hmm perhaps I didn't understand what your proposing but I made this change to the first test
```cs

        var actual = sut.Territory(coordinate);
        // changes from -  var expected = (Owner.Black, new[] { (0, 0), (0, 1), (1, 0) });
        var expected = (Owner.Black, new HashSet<(int, int)> { (0, 0), (0, 1), (1, 0) }); 
        Assert.Equal(expected.Item1, actual.Item1);
        Assert.Equal(expected.Item2, actual.Item2);
```
and it still fails with 
```
        Assert.Equal() Failure
        Expected: HashSet<ValueTuple<Int32, Int32>> [(0, 0), (0, 1), (1, 0)]
        Actual:   HashSet<ValueTuple<Int32, Int32>> [(0, 1), (0, 0), (1, 0)]
```

Did you mean to have the methods in the exercise themselves return `HashSet`s? I tried that and `One_territory_is_the_whole_board` still fails on the key collection assertion (which I have to say I find surprising).

I won't push it further if your really not interested but I would guess that at worst FluentAssertions could be added such that its available for all exercises without other exercises changing aside from  the added dependency. It might seem like an edge case but I wouldn't be surprised if there have been (or will be) other cases where writing tests was more complex than it could have been.

**Comment by dzegel** [comment]
or did you mean to sprinkle `.ToHashSet()` around in the test file to convert all the `IEnumerable`s to sets in the assertions? if you do that you would unwanted ignore duplicates in the actual values

**Comment by dzegel** [comment]
another option would be to sort each collection in the test assertions but I feel like its a patch solution to a problem that could arise more

**Comment by ErikSchierboom** [comment]
I've just converted the tests to use HashSets and that works as intended, except for one thing:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using Xunit;

public class GoCountingTests
{
    [Fact]
    public void Black_corner_territory_on_5x5_board()
    {
        var coordinate = (0, 1);
        var board = 
            "  B  \n" +
            " B B \n" +
            "B W B\n" +
            " W W \n" +
            "  W  ";
        var sut = new GoCounting(board);
        var actual = sut.Territory(coordinate);
        var expected = (Owner.Black, new HashSet<(int, int)> { (0, 0), (0, 1), (1, 0) });
        Assert.Equal(expected.Item1, actual.Item1);
        Assert.Equal(expected.Item2, actual.Item2);
    }

    [Fact]
    public void White_center_territory_on_5x5_board()
    {
        var coordinate = (2, 3);
        var board = 
            "  B  \n" +
            " B B \n" +
            "B W B\n" +
            " W W \n" +
            "  W  ";
        var sut = new GoCounting(board);
        var actual = sut.Territory(coordinate);
        var expected = (Owner.White, new[] { (2, 3) });
        Assert.Equal(expected.Item1, actual.Item1);
        Assert.Equal(expected.Item2, actual.Item2);
    }

    [Fact]
    public void Open_corner_territory_on_5x5_board()
    {
        var coordinate = (1, 4);
        var board = 
            "  B  \n" +
            " B B \n" +
            "B W B\n" +
            " W W \n" +
            "  W  ";
        var sut = new GoCounting(board);
        var actual = sut.Territory(coordinate);
        var expected = (Owner.None, new HashSet<(int, int)> { (0, 3), (0, 4), (1, 4) });
        Assert.Equal(expected.Item1, actual.Item1);
        Assert.Equal(expected.Item2, actual.Item2);
    }

    [Fact]
    public void A_stone_and_not_a_territory_on_5x5_board()
    {
        var coordinate = (1, 1);
        var board = 
            "  B  \n" +
            " B B \n" +
            "B W B\n" +
            " W W \n" +
            "  W  ";
        var sut = new GoCounting(board);
        var actual = sut.Territory(coordinate);
        var expected = (Owner.None, new HashSet<(int, int)>());
        Assert.Equal(expected.Item1, actual.Item1);
        Assert.Equal(expected.Item2, actual.Item2);
    }

    [Fact]
    public void Invalid_because_x_is_too_low_for_5x5_board()
    {
        var coordinate = (-1, 1);
        var board = 
            "  B  \n" +
            " B B \n" +
            "B W B\n" +
            " W W \n" +
            "  W  ";
        var sut = new GoCounting(board);
        Assert.Throws<ArgumentException>(() => sut.Territory(coordinate));
    }

    [Fact]
    public void Invalid_because_x_is_too_high_for_5x5_board()
    {
        var coordinate = (5, 1);
        var board = 
            "  B  \n" +
            " B B \n" +
            "B W B\n" +
            " W W \n" +
            "  W  ";
        var sut = new GoCounting(board);
        Assert.Throws<ArgumentException>(() => sut.Territory(coordinate));
    }

    [Fact]
    public void Invalid_because_y_is_too_low_for_5x5_board()
    {
        var coordinate = (1, -1);
        var board = 
            "  B  \n" +
            " B B \n" +
            "B W B\n" +
            " W W \n" +
            "  W  ";
        var sut = new GoCounting(board);
        Assert.Throws<ArgumentException>(() => sut.Territory(coordinate));
    }

    [Fact]
    public void Invalid_because_y_is_too_high_for_5x5_board()
    {
        var coordinate = (1, 5);
        var board = 
            "  B  \n" +
            " B B \n" +
            "B W B\n" +
            " W W \n" +
            "  W  ";
        var sut = new GoCounting(board);
        Assert.Throws<ArgumentException>(() => sut.Territory(coordinate));
    }

    [Fact]
    public void One_territory_is_the_whole_board()
    {
        var board = " ";
        var sut = new GoCounting(board);
        var actual = sut.Territories();
        var expected = new Dictionary<Owner, HashSet<(int, int)>>
        {
            [Owner.Black] = new(),
            [Owner.White] = new(),
            [Owner.None] = new() { (0, 0) }
        };
        Assert.Equal(expected[Owner.Black], actual[Owner.Black]);
        Assert.Equal(expected[Owner.White], actual[Owner.White]);
        Assert.Equal(expected[Owner.None], actual[Owner.None]);
    }

    [Fact]
    public void Two_territory_rectangular_board()
    {
        var board = 
            " BW \n" +
            " BW ";
        var sut = new GoCounting(board);
        var actual = sut.Territories();
        var expected = new Dictionary<Owner, HashSet<(int, int)>>
        {
            [Owner.Black] = new() { (0, 0), (0, 1) },
            [Owner.White] = new() { (3, 0), (3, 1) },
            [Owner.None] = new()
        };
        Assert.Equal(expected[Owner.Black], actual[Owner.Black]);
        Assert.Equal(expected[Owner.White], actual[Owner.White]);
        Assert.Equal(expected[Owner.None], actual[Owner.None]);
    }

    [Fact]
    public void Two_region_rectangular_board()
    {
        var board = " B ";
        var sut = new GoCounting(board);
        var actual = sut.Territories();
        var expected = new Dictionary<Owner, HashSet<(int, int)>>
        {
            [Owner.Black] = new() { (0, 0), (2, 0) },
            [Owner.White] = new(),
            [Owner.None] = new()
        };
        Assert.Equal(expected[Owner.Black], actual[Owner.Black]);
        Assert.Equal(expected[Owner.White], actual[Owner.White]);
        Assert.Equal(expected[Owner.None], actual[Owner.None]);
    }
}
```

The only thing that is not working is the keys check, but I'd be fine with omitting that as the key is an enum so the student can't actually use a different value.

I still feel this is an edge case and I'd rather not introduce the different type of assertion that fluentassertions provides.

**Comment by dzegel** [comment]
to be clear, your proposing changing the tests as well as the method signatures in the exercise right?
I tired my solution without the workarounds I put in with the tests you have above and it does not work unless I change the methods under test to return hashsets instead of enumerables

**Comment by ErikSchierboom** [comment]
> to be clear, your proposing changing the tests as well as the method signatures in the exercise right?

That is correct.

> I tired my solution without the workarounds I put in with the tests you have above and it does not work unless I change the methods under test to return hashsets instead of enumerables

That is also correct.

**Comment by dzegel** [comment]
@ErikSchierboom I've got the test updates worked out but how do I update the method signatures in the SUT?
I assume that file is also auto generated but am I wrong? Do I just update that file directly?

**Comment by dzegel** [comment]
https://github.com/exercism/csharp/pull/1837
