### ISSUE TITLE
Small formatting and other issues in 'The Weather from Deather' exercise

### ISSUE THREAD

**Issue by aage** [exercism/csharp#1830]
- Incorrect using `using Xunit.Sdk;`
- The `WindDirection` `enum` sets the first value (`Unknown`) to `0`, but this is already the default value for the first value of an `enum` if no backing `integer` is explicitly specified. This only causes confusion IMO.

**Comment by aage** [comment]
Submitted a PR: https://github.com/exercism/csharp/pull/1831

**Comment by ErikSchierboom** [comment]
Closed by #1831
