### ISSUE TITLE
Stale links in GENERATORS.md

### ISSUE THREAD

**Issue by dzegel** [exercism/csharp#1836]
a number of links in https://github.com/exercism/csharp/blob/main/docs/GENERATORS.md no longer work
- https://github.com/exercism/csharp/blob/main/docs/GENERATORS.md?plain=1#L3
  - https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/test-suites.md
  - can't find where it was moved to
- https://github.com/exercism/csharp/blob/main/docs/GENERATORS.md?plain=1#L24
  - https://github.com/exercism/csharp/blob/master/generators/Exercises/Bob.cs
  - moved to https://github.com/exercism/csharp/blob/main/generators/Exercises/Generators/Bob.cs
- https://github.com/exercism/csharp/blob/main/docs/GENERATORS.md?plain=1#L51
  - https://github.com/exercism/csharp/blob/master/generators/Exercises/Generators/BracketPush.cs
  - can't find where it was moved to

There are a bunch of other links in the doc that point to the `master` branch and get auto redirected to the `main` branch.

Aside from fixing the broken links I would propose updating all github links to be relative links

**Comment by ErikSchierboom** [comment]
For the first broken link, I'd refer to https://github.com/exercism/problem-specifications#test-data-canonical-datajson
For the third one, https://github.com/exercism/csharp/blob/main/generators/Exercises/Generators/MatchingBrackets.cs should be used.

**Comment by dzegel** [comment]
and how do you feel about updating all the github links pointing to this repo to be relative?

**Comment by ErikSchierboom** [comment]
We can't as the documentation is displayed on https://exercism.org/docs/tracks/csharp.

**Comment by dzegel** [comment]
https://github.com/exercism/csharp/pull/1838

**Comment by ErikSchierboom** [comment]
Closed by https://github.com/exercism/csharp/pull/1838
