### ISSUE TITLE
Generify Exponentiation Operator for Diffie-Hellman C# Example

### ISSUE THREAD

**Issue by CanadianBaconBoi** [exercism/csharp#1849]
Currently in the example for the Diffie-Hellman exercise on the C# track, `**` is used to denote an exponent however in C# and many other languages `**` is  not used for this purpose.

I believe that it would be beneficial for the sake of readability to replace `**` with `pow` as it will be more easily understood.

**Comment by CanadianBaconBoi** [comment]
#1848

**Comment by ErikSchierboom** [comment]
Closing. See https://github.com/exercism/csharp/pull/1848#issuecomment-987682718
