### ISSUE TITLE
Football Match Reports: Test fails because string in test doesn't match string in class

### ISSUE THREAD

**Issue by nordicjg** [exercism/csharp#1853]
**Test**
[Fact]
    [Task(4)]
    public void AnalyzeOffField_injury()
    {
        Assert.Equal("**Oh no! Player 3 is injured. Medics are on the field.**", PlayAnalyzer.AnalyzeOffField(new Injury(3)));
    }

**class Injury :  Incident**
public override string GetDescription() => $"**Player {player} is injured.**";

**Comment by ErikSchierboom** [comment]
If you read task 4 (https://github.com/exercism/csharp/blob/main/exercises/concept/football-match-reports/.docs/instructions.md#4-report-on-incidents-during-the-match), you'll find that there is a special case for handling injuries with the `AnalyzeOffField` method.
