### ISSUE TITLE
[Diffie Hellman] Is a**b a known notation for a^b?

### ISSUE THREAD

**Issue by Gautzilla** [exercism/csharp#1860]
Hey,
I had some trouble with the Diffie Hellman exercise because of the instruction:

`A = g**a mod p`

Where `g**a` represents `g` to the power of `a`.

I thought it was basically a `a*b` and then struggled correcting my code. I can't fin any info on the `**` notation. Wouldn't it be clearer to write `A = g^a mod p` instead?

**Comment by ErikSchierboom** [comment]
Hi! The description comes from the description in the problem-specifications repo: https://github.com/exercism/problem-specifications/blob/main/exercises/diffie-hellman/description.md Could you open an issue there please?

**Comment by Gautzilla** [comment]
Sure! Sorry for the misplaced issue.
