### ISSUE TITLE
Update Diffie-Hellman description to match with the problem-specifications repo

### ISSUE THREAD

**Issue by Gautzilla** [exercism/csharp#1861]
The[ PR #1933 in the exercism/problem-specifications repo](https://github.com/exercism/problem-specifications/pull/1933) changed the exponentiation notation "a**b" to "aᵇ" in the Diffie Hellman exercise description.

The change does not appear in the csharp track (and other tracks that use this exercise). Should we update it locally in each track too?

**Comment by ErikSchierboom** [comment]
Yep. We have a workflow for that:

```shell
> ./bin/fetch-configlet
> ./bin/configlet sync --docs --update
```

This syncs the docs.

I've opened https://github.com/exercism/csharp/issues/1861 to update all descriptions
