### ISSUE TITLE
105 locked exercises, 0 available, 0 in progress

### ISSUE THREAD

**Issue by Gautzilla** [exercism/csharp#1865]
I'm stuck at a point in the track where I have no unlocked exercise and no way to unlock new exercises.
[This is what my exercises page looks like](https://files.gitter.im/550b052715522ed4b3dd8338/9bF5/image.png)

I'm not sure how this happened, maybe that's due to the order in which I completed the exercises?

For some locked exercises, i.e. "Accumulate", I'm told that I need to compelte "Tracks on Tracks on Tracks" and "Log Analysis" (which I have completed already) to unlock the exercise.

In the Syllabus, there is a strange displaying of the exercises, [showing me that I completed the learning exercise but still specifying "0/5 completed exercises"](https://files.gitter.im/550b052715522ed4b3dd8338/b6Ux/image.png)

**Comment by ErikSchierboom** [comment]
Can this be closed as a duplicate of https://github.com/exercism/exercism/issues/6231?

**Comment by Gautzilla** [comment]
Sure!
