### ISSUE TITLE
dominoes: ask for Chain rather than CanChain OR modify README to ask for CanChain

### ISSUE THREAD

**Issue by petertseng** [exercism/csharp#190]
There are two possible ways to interpret the dominoes problem, as [the canonical data](https://github.com/exercism/x-common/blob/master/exercises/dominoes/canonical-data.json) tells us.

1. Only ask for `CanChain`, a boolean telling us whether the given dominoes can be chained. The tests only need to check whether the boolean matches the expectation.
2. Ask for `Chain`, which will be (I assume for C#) a valid chain if one exists, or `null` if one does not. The tests would need to check the various properties noted in [the canonical data](https://github.com/exercism/x-common/blob/master/exercises/dominoes/canonical-data.json#L27-L33)

This track asks for `CanChain` only. **I assumed this was an intentional decision**, so I did not question it. But Erik asked me to file an issue. So y'all can reopen the issue in case y'all want to ask for `Chain`.

**Comment by ErikSchierboom** [comment]
@robkeim How do you feel about this?

**Comment by petertseng** [comment]
summary of what I say in https://github.com/exercism/xfsharp/issues/296 is that I think doing `Chain`

advantages:

* student peace of mind that their code found a correct chain

disadvantage

* more complex test
* students are probably already finding a full chain anyway, so it's not like using `Chain` is going to "weed out" any more students.

**Comment by robkeim** [comment]
I added my $0.02 in: https://github.com/exercism/xfsharp/issues/296

**Comment by ErikSchierboom** [comment]
Re-opened.

**Comment by robkeim** [comment]
@petertseng and @ErikSchierboom I'm going to go ahead and close this issue since the canonical data has `canChain` and not `chain`:
https://github.com/exercism/problem-specifications/blob/master/exercises/dominoes/canonical-data.json

If we want to re-open this for discussion I think we should change the canonical data first then update the individual tracks. Does that make sense?

**Comment by petertseng** [comment]
> the canonical data has `canChain` and not `chain`

My suggestion for `chain` stands even when the canonical data contains `canChain` because https://github.com/exercism/problem-specifications/blob/master/exercises/dominoes/canonical-data.json#L21-L24.

It does not matter to me whether this issue is closed, but what does matter to me is that if it is closed, it is closed for the right reason.

If considering `chain` in canonical-data.json, it may be possible if the canonical data chooses a canonical representation for the chain that is invariant to reversal and rotation. A question I have not explored is whether there is only one chain under this canonicalisation.

**Comment by ErikSchierboom** [comment]
I think I lean towards keeping this closed, to keep the implementation of an already challenging problem slightly simpler.

**Comment by petertseng** [comment]
It looks like this track will need to change its README.

The https://github.com/exercism/csharp/blob/master/exercises/dominoes/README.md says such things like:

> Compute a way to order a given set of dominoes

Since this track asks for canChain, this should probably read "Compute whether there exists a way to order a given set of dominoes"

> For example given the stones 21, 23 and 13 you should compute something like 12 23 31 or 32 21 13 or 13 32 21

Since this track asks for canChain, this should probably read "For example given the stones 21, 23 and 13 you should declare that there exists a possible chain (for example, 12 23 31 is a possible chain)"

Note upcoming changes to domino text representation in https://github.com/exercism/problem-specifications/pull/972

**Comment by robkeim** [comment]
Good point @petertseng... I'm re-opening this issue to track a README change.

**Comment by ErikSchierboom** [comment]
I'm working on this
