### ISSUE TITLE
[Forth] Test assert exception can be more specific

### ISSUE THREAD

**Issue by Gautzilla** [exercism/csharp#1935]
The unit test `Division_errors_if_dividing_by_zero()` expects the solution to throw a `InvalidOperationException`.

Shouldn't the test expect the solution to throw a `DivideByZeroException`?

**Comment by ErikSchierboom** [comment]
Would it? There are no numbers on the stack, so there is no division being done.

**Comment by Gautzilla** [comment]
> Would it? There are no numbers on the stack, so there is no division being done.

I'm sorry I mixed up the unit tests. I edited the comment.

**Comment by ErikSchierboom** [comment]
Ah yes, then it makes sense! Would you be interested in doing a PR? If so, you'd have to update the test generator found at https://github.com/exercism/csharp/blob/main/generators/Exercises/Generators/Forth.cs, which is responsible for auto-generating the test file of the `forth` exercise. You can find more about generators here: https://github.com/exercism/csharp/blob/main/docs/GENERATORS.md

**Comment by Gautzilla** [comment]
Thanks for pointing me to the resources, I'll submit a PR as soon as I have some free time.

**Comment by Gautzilla** [comment]
I submitted PR #1937 to address this issue.

**Comment by ErikSchierboom** [comment]
Closed by #1937
