### ISSUE TITLE
Show test summary in CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1949]
With Github Actions now supporting Job Summaries, we can leverage this to show the test results in a nice way.
For that, we can use the Test Summary Action: https://github.com/test-summary/action
See https://github.com/test-summary/examples/tree/main/dotnet for how to integrate this with .NET.
Note: we should only do this when run in CI, so the `test.ps1` script should detect this (probably via an environment variable, see https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables).

**Comment by putquo** [comment]
@ErikSchierboom, can I take a stab at this one?

**Comment by ErikSchierboom** [comment]
Sure!
