### ISSUE TITLE
Create test data generators

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#195]
The canonical data of the various exercises regularly receives updates. Some of our exercises will be using outdated or incomplete data. We should try to fix this by writing test generators, support for which is added in #228.

**Comment by ErikSchierboom** [comment]
- [ ] hello-world
- [ ] hamming
- [ ] gigasecond
- [ ] rna-transcription
- [ ] raindrops
- [ ] difference-of-squares
- [ ] pangram
- [ ] sieve
- [ ] roman-numerals
- [ ] robot-name
- [ ] nth-prime
- [ ] leap
- [ ] grains
- [ ] word-count
- [ ] bob
- [ ] run-length-encoding
- [ ] binary
- [ ] accumulate
- [ ] sum-of-multiples
- [ ] grade-school
- [ ] series
- [ ] phone-number
- [ ] prime-factors
- [ ] strain
- [ ] etl
- [ ] trinary
- [ ] beer-song
- [ ] bowling
- [ ] space-age
- [ ] anagram
- [ ] binary-search-tree
- [ ] crypto-square
- [ ] clock
- [ ] alphametics
- [ ] rail-fence-cipher
- [ ] acronym
- [ ] scrabble-score
- [ ] nucleotide-count
- [ ] flatten-array
- [ ] hexadecimal
- [ ] say
- [ ] meetup
- [ ] queen-attack
- [ ] palindrome-products
- [ ] bracket-push
- [ ] food-chain
- [ ] matrix
- [ ] saddle-points
- [ ] triangle
- [ ] atbash-cipher
- [ ] house
- [ ] secret-handshake
- [ ] proverb
- [ ] ocr-numbers
- [ ] pig-latin
- [ ] simple-linked-list
- [ ] luhn
- [ ] simple-cipher
- [ ] wordy
- [ ] allergies
- [ ] poker
- [ ] kindergarten-garden
- [ ] linked-list
- [ ] pythagorean-triplet
- [ ] robot-simulator
- [ ] twelve-days
- [ ] circular-buffer
- [ ] largest-series-product
- [ ] binary-search
- [ ] two-bucket
- [ ] pascals-triangle
- [ ] custom-set
- [ ] minesweeper
- [ ] scale-generator
- [ ] protein-translation
- [ ] perfect-numbers
- [ ] connect
- [ ] list-ops
- [ ] diamond
- [ ] all-your-base
- [ ] isogram
- [ ] transpose
- [ ] tournament
- [ ] dominoes

**Comment by ErikSchierboom** [comment]
If someone is interested in writing a test generator, please state so here, so that I can mark that exercise as being worked on.

**Comment by ErikSchierboom** [comment]
And the first test generator has been merged (in #229)! 🎉

**Comment by ErikSchierboom** [comment]
@robkeim Earlier, you stated that you were interested in creating a test data generator. Are you still interested? If so, I'd love to have you try out the current generators framework and see where you feel I can improve things.

**Comment by robkeim** [comment]
Hey @ErikSchierboom I'd love to help out, but I've been super busy with relocating to a new country, and now I'm trying to get settled into my job and establish myself here. You should keep making progress without me, as I think I'll need a couple of months before things settle down.

**Comment by ErikSchierboom** [comment]
@robkeim Ah, good luck then with your relocating! Hope to have you back soon.

**Comment by robkeim** [comment]
Created a PR for Bob:
https://github.com/exercism/xcsharp/pull/300

**Comment by ErikSchierboom** [comment]
Great to have you back!

**Comment by robkeim** [comment]
@ErikSchierboom I assume this work is on pause given the refactoring that you're doing in https://github.com/exercism/xcsharp/pull/302. I just want to make sure that others are aware of that so they don't try to pick up something here which conflicts with your work.

**Comment by ErikSchierboom** [comment]
Correct!

**Comment by jpreese** [comment]
There looks like there's a lot to be done in this department and it seems like PR #302 was merged. Is it safe to assume these can be worked on again?

I dug into the generators solution a decent bit tonight and believe I have a firm understanding of how it all works.

**Comment by robkeim** [comment]
Hey @jpreese, now that these PRs have merged we could definitely use all the help we can get! Just let us know which ones you're planning on working on and thanks in advance for your contributions!

**Comment by ErikSchierboom** [comment]
@jpreese Well there is indeed lots of work to be done here! I'm not completely happy with the way I currently set things up, which is why I'm doing another large refactoring to make things far easier: https://github.com/ErikSchierboom/csharp/tree/refactoring Currently, more complex exercises that require non-standard work to be done are quite complex. In the new version, it should be much easier to create generators for those exercises by simply using templates. 

I hope this have something working/mergeable next week, but you can already start working on this if you want. I would suggest that if you decide to work on a generator, that you choose a relatively simple one, as they are least likely to change due to the refactoring.

**Comment by jpreese** [comment]
I'll probably just wait it out then. No sense in potentially going through a rewrite of the generator if the new-hotness is coming out so soon.

**Comment by robkeim** [comment]
@jpreese we should be unblocked to start making progress on these again now that @ErikSchierboom's PR is merged

**Comment by ErikSchierboom** [comment]
I'm in awe how quickly you ( @jpreese  and @robkeim ) have been able to churn these out! It has been very nice to see what are the rough edges in the test generators code.

**Comment by robkeim** [comment]
Thanks @ErikSchierboom, we're definitely making good progress :)

**Comment by robkeim** [comment]
After the two open PRs merge we'll have 41 out of the 69 available exercises completed in terms of test generators 🎉

**Comment by ErikSchierboom** [comment]
That's amazing!

**Comment by robkeim** [comment]
I'm going to work on the generator for clock

**Comment by felix91gr** [comment]
Ah, here it is. I’m going to work in the Difference of Squares Test Case Generator :D

**Comment by robkeim** [comment]
I'm closing this issue now that we have individual issues for each generator.

**Comment by ErikSchierboom** [comment]
Agreed!
