### ISSUE TITLE
International Calling Connoisseur - Many passing solutions logically incorrect

### ISSUE THREAD

**Issue by PeteSutcliffe** [exercism/csharp#1961]
While looking at existing solutions for this problem I noticed a lot of them use existingDictionary.Values.Max() to find the longest country name. This only work by coincidence as the longest country name also happens to be last of the entries alphabetically.
Perhaps different values should be chosen to populate existingDictionary or the tests updates to catch this.

**Comment by ErikSchierboom** [comment]
That is a great suggestion! Would you be willing to submit a PR to fix this?

**Comment by PeteSutcliffe** [comment]
It's my first submission so please let me know if I need to update anything.

**Comment by ErikSchierboom** [comment]
Everything was good! I've just merged [the PR](https://github.com/exercism/csharp/pull/1963). Thanks.
