### ISSUE TITLE
Create pre-built Docker container 

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#202]
With .NET Core having great support for Docker, we could quite feasibly create a Docker container that has a working .NET Core installation as well as an installed exercism CLI. This could make starting out for those familiar with Docker a lot easier.

**Comment by ErikSchierboom** [comment]
A small checklist of things the Docker container should contain:

- The latest version of the .NET Core CLI (which we get automatically when we base ourselves on [this official .NET Core image](https://github.com/dotnet/dotnet-docker/blob/master/1.0/debian/runtime/Dockerfile))
- The latest version of the Exercism CLI
- An introduction message you get at startup telling you how to proceed (configuring the Exercism CLI etc.)

**Comment by jpreese** [comment]
Before I start going down the route I want to take, just wanted to get some feedback if it makes sense.

I think it makes sense to actually base this off of an image that already has the Exercism CLI. However, there isn't an image for the Exercism CLI, which is easy enough to make. Once that is made, I think every track can be based off of that image, since every track is going to need CLI, whereas every track won't need .NET

So what I'd like to do is make an image based off of go (https://hub.docker.com/_/golang/) and install the Exercism CLI on that. We can then publish that image to docker hub and the other tracks, if they soi wish to use docker, can base their dockerfiles off of that.

I would then use that image to install .NET Core

I did notice that we don't have an Organization set up on docker hub if we think thats something we want to do, so all of the images are centralized.

**Comment by robkeim** [comment]
@jpreese I would move this discussion over to this thread to get opinion's from people in other tracks as well:
https://github.com/exercism/discussions/issues/122

Even if other tracks weren't interested in participating, @ErikSchierboom had in mind creating docker container support for C# and F# so we would at minium get reuse out of those two languages.

**Comment by ErikSchierboom** [comment]
I agree with @robkeim. This is problem something that we should discuss together with other maintainers, but your approach sounds good! Installing the .NET Core runtime is actually quite simple, so we can probably easily add it to a base Exercism Docker image.

**Comment by jpreese** [comment]
I'm waiting for some final clarifications in exercism/discussions#122, but assuming nothing changes I'm probably going to make a .NET Core Exercism CLI image that C#/F# can leverage.

**Comment by ErikSchierboom** [comment]
Great news!

**Comment by ErikSchierboom** [comment]
I've given this topic a little bit more thought, and in the end I don't think we stand to benefit much from having a Docker image with Exercism pre-installed. If someone wants to convince me otherwise, please let me know why you think this is a good idea.

**Comment by robkeim** [comment]
@ErikSchierboom I'm curious to know what changed your mind given you were the one that initially created this issue. I'm not against closing it, but would just like to hear what made you change your mind.

**Comment by jpreese** [comment]
I'd be interested as well. The only thing I can think of is the relative simplicity of getting up and running (CLI and .NET Core SDK), so while a Docker image would include both of these it's not too much of a stretch to go out and grab the dependencies yourself.

**Comment by ErikSchierboom** [comment]
> I'd be interested as well. The only thing I can think of is the relative simplicity of getting up and running (CLI and .NET Core SDK), so while a Docker image would include both of these it's not too much of a stretch to go out and grab the dependencies yourself.

This. I've given it a little thought on how a Docker image would work, and you would then have to:

- Either store your code in the Docker container (as that is only where the Exercism CLI is available), but that would mean losing your code when the container is destroyed (although you could push to remote repository to workaround this). Or elsewise create a link to a local directory (what directory would that be?). Would people new to Docker understand how to link directories?
- You cannot use the Exercism command on your host machine, only in the Docker container. What advantage then does the Docker image give you, especially considering how easy installing .NET Core and the Exercism CLI are?

For these reasons, I've decided against creating a Docker image, but if I have drawn incorrect conclusions, let me know!
