### ISSUE TITLE
Integrate code analysis into build

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#203]
With Roslyn, there came the concept of code analyzers. These static analysis tools can help catch common errors, which is why I think they are a perfect fit for the exercism C# track.

See https://github.com/dotnet/roslyn/pull/18285/files for a reference to the code style package.

**Comment by robkeim** [comment]
@ErikSchierboom have you tried using that analyzer yet? My understanding is that library allows you to write your own anlyzers, but if you want to use some existing ones you have to use something like [StyleCop.Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers).

I tried integrating StyleCop.Analyzers but couldn't figure out how to customize the list of rules and there are likely some rules that we don't want to enforce such as XML documentation on every method as that tends to be a bit heavy handed.

**Comment by ErikSchierboom** [comment]
I haven't yet. These analyzers are still being worked on I think. The StyleCop analyzers might indeed be too strict.

**Comment by jpreese** [comment]
#380 handles this

**Comment by masters3d** [comment]
Are analyzers the only option for linting code?
https://github.com/DotNetAnalyzers/StyleCopAnalyzers

Is there a defacto analyzer?

**Comment by ErikSchierboom** [comment]
I'm inclined to close this for now. We can always re-add it later.
