### ISSUE TITLE
booking-up-for-beauty: Error in third format in description

### ISSUE THREAD

**Issue by sergeifmf** [exercism/csharp#2033]
There are three formats in the description and third is Thursday, July 25, 2019 13:45:00 **:00** with an extra colon and two zeroes in the end
https://exercism.org/tracks/csharp/exercises/booking-up-for-beauty
![error](https://user-images.githubusercontent.com/29398963/201420305-b2e746be-174e-45d7-9e68-2150f0365dde.png)

**Comment by ErikSchierboom** [comment]
Would you be willing to submit a PR to fix this?

**Comment by ErikSchierboom** [comment]
Closed by #2043
