### ISSUE TITLE
C# Authentication System: local test results different from online.

### ISSUE THREAD

**Issue by ghost** [exercism/csharp#2055]
The following code passes the local tests, but not the online ones:

```
using System.Collections.Generic;

public class Authenticator
{
    public Identity Admin { get; }
    private readonly IDictionary<string, Identity> _developers = new Dictionary<string, Identity>
        {
            ["Bertrand"] = new() { EyeColor = "blue" },
            ["Anders"] = new() { EyeColor = "brown" }
        };
    public Authenticator(Identity admin) => Admin = admin;
    public IDictionary<string, Identity> GetDevelopers() => _developers;
}

public struct Identity
{
    public string EyeColor { get; init; }
}
```
<img width="999" alt="CleanShot 2022-11-25 at 12 11 08@2x" src="https://user-images.githubusercontent.com/39763085/203973332-a681b488-0729-41d7-8968-e9d99fe2c9eb.png">
<img width="1385" alt="CleanShot 2022-11-25 at 12 12 09@2x" src="https://user-images.githubusercontent.com/39763085/203973475-81ab6494-43f8-43d4-9377-49963d78678d.png">

**Comment by ErikSchierboom** [comment]
You might have modified your tests file, as the tests contain an `Email` property: https://github.com/exercism/csharp/blob/main/exercises/concept/authentication-system/AuthenticationSystemTests.cs

**Comment by michalporeba** [comment]
@ErikSchierboom I have just tested this and I'm fairly sure that the local files must have been modified. Here is what I have done. 
* Downloaded the exercise using `exercism download...`
* Replaced the code with the version provided above. 
* Run the local tests

The tests failed as expected. 
I think this issue can be closed. Not only the problem cannot be reproduced, but the user who raised it has deleted their github account.
