### ISSUE TITLE
weighing-machine: missing test + number format

### ISSUE THREAD

**Issue by dorianignee** [exercism/csharp#2065]
In the exercise "weighing-machine", there is no test for a precision other than 3.

Maybe, you could add something like this:

```csharp
[Fact]
[Task(4)]
public void Apply_tare_adjustment_and_get_display_weight_with_precision_1()
{
    var wm = new WeighingMachine(precision: 1);
    wm.Weight = 100.77;
    wm.TareAdjustment = 10;
    Assert.Equal("90.8 kg", wm.DisplayWeight);
}
```
---
The second issue is that C# automatically uses the local number format, when casting float numbers to string. I don't know if it's intended to test for an InvariantCulture number format (CultureInfo was handled a bit earlier on the learning path in the exercise "beauty-salon-goes-global" (concept "Time"), but that's not mandatory for starting "weighing-machine")

If it's not intended to use InvariantCulture, you could use something similar to `Assert.Equal($"{90.770:F3} kg", wm.DisplayWeight);` for testing DisplayWeight

**Comment by ErikSchierboom** [comment]
@dorianignee I like the suggestion! Would you be willing to submit a PR to add the suggestion test?

>  I don't know if it's intended to test for an InvariantCulture number format

I would like this to be transparent to the student, such that they don't need to do anything. I think the easiest way to do this is to ensure that we use the invariant culture automatically whilst running the tests. Each exercise references the `Exercism.Tests` package, which has a `UseCulture` attribute that we can add to our test class: https://github.com/exercism/dotnet-tests/blob/main/tests/Exercism.Tests.Tests/UseCultureAttributeTests.cs#L26

If you're happy with that, we could also use a separate PR to fix that ;)
