### ISSUE TITLE
Circular buffer - incorrect Clear behaviour

### ISSUE THREAD

**Issue by michalporeba** [exercism/csharp#2109]
**Problem:** In the circular buffer the `Clear` method tests pass through implementations that remove a single item form the buffer while the typical implementation of `Clear` in .net is to remove all elements from a collection. 

**Solution:** improve the test

**Other things to consider:** Similarly to simple linked list exercise it might be worth comparing this exercise with other languages and .net standards to provide better learning experience. 

(This issue is just a reminder. I will raise a forum thread once I have actioned a few other threads I have already started).

**Comment by ErikSchierboom** [comment]
Good catch!
