### ISSUE TITLE
Missing closing parentheses in instructions

### ISSUE THREAD

**Issue by Nachop51** [exercism/csharp#2133]
Markdown file: <https://github.com/exercism/csharp/blob/main/exercises/practice/saddle-points/.docs/instructions.append.md>

![image](https://github.com/exercism/csharp/assets/79727818/3a189ce0-410e-44ac-955b-fb310e20b403)

**Comment by aage** [comment]
This issue was fixed in https://github.com/exercism/csharp/pull/2140
