### ISSUE TITLE
C# track, Hyper-optimized Telemetry exercise - unclear instructions

### ISSUE THREAD

**Issue by vlabensky-sana** [exercism/csharp#2160]
Hello,

In the Hyper-optimized Telemetry exercise of the C# track the last paragraph seems to give vague sentence which contradicts the task.

[Here's the exercise](https://exercism.org/tracks/csharp/exercises/hyper-optimized-telemetry)

The last paragraph goes like this:

> 2. Decode a received buffer
> 
> Please implement the static method TelemetryBuffer.FromBuffer() to decode the buffer received and return the value in the form of a long.
> 
> ```
> TelemetryBuffer.FromBuffer(new byte[] {0xfc, 0xff, 0xff, 0xff, 0x7f, 0x0, 0x0, 0x0, 0x0 })
> // => 2147483647
> ```
>
> If the prefix byte is not one of -8, -4, -2, 2 or 4 then 0 should be returned.

In the last sentence it says that if the prefix byte is not one of -8, -4, -2, 2 or 4 then 0 should be returned. But at the same time in the example above it has the prefix byte 0xFC, which is 252, which is none of the numbers listed in the last sentence, and the returned type is expected to be 2147483647 which contradicts the 0 from the last sentence.

So this last sentence - what is it supposed to mean? Perhaps it needs to re-phrased to make it more clear for the reader.

Thanks!

**Comment by ErikSchierboom** [comment]
> So this last sentence - what is it supposed to mean? Perhaps it needs to re-phrased to make it more clear for the reader.

Do you perhaps have a better suggestion for how to handle this?

**Comment by ErikSchierboom** [comment]
> If the prefix byte is of unexpected value then 0 should be returned.

I like that! Would you be willing to submit a PR?

**Comment by vlabensky-sana** [comment]
Took me a while to get back to it, sorry. Here's the PR #2163.

**Comment by michalporeba** [comment]
@ErikSchierboom The PR has been merged, I think this issue can be closed.
