### ISSUE TITLE
Missing example in do-while loops introduction in C# track

### ISSUE THREAD

**Issue by Hiexy** [exercism/csharp#2197]
in the C# track, in the section of `do-while` loops, the section has the following

**Comment by Hiexy** [comment]
@ErikSchierboom after the bot closed the issue, I opened a [topic](https://forum.exercism.org/t/missing-example-in-do-while-loops-introduction-in-c-track/8124) in the forum, but I realized that the example of the while loop shows when looking at the [exercise ](https://exercism.org/tracks/csharp/exercises/interest-is-interesting)that is related to it, but not when looking at it alone. I am not sure if this is how it is intended to be.

**Comment by ErikSchierboom** [comment]
Fixed in #2198
