### ISSUE TITLE
Either support the current C# language or tell us what language version is being used for tasks.

### ISSUE THREAD

**Issue by bbarry** [exercism/csharp#2237]
**Expected: C#12** (note: the project is targeting net8.0: https://github.com/exercism/csharp/blob/main/exercises/concept/bird-watcher/BirdWatcher.csproj)

**Actual: C#11** (at least based on testing the fact that raw string literals work)

I was fooling around with the site and decided to stumble into the C# track, hitting the bird watcher exercise...

My solution:

```csharp
using System;
using System.Linq;

class BirdCount(int[] birdsPerDay)
{
    public static int[] LastWeek() => [0, 2, 5, 3, 7, 8, 4];

    public int Today() => birdsPerDay[^1];

    public void IncrementTodaysCount() => birdsPerDay[^1]++;

    public bool HasDayWithoutBirds() => birdsPerDay.Any(b => b == 0);

    // the tests fail to notice the boundary cases here and the task is a little unclear, my first solution was: 
    // birdsPerDay[..Math.Clamp(numberOfDays, 0, birdsPerDay.Length)].Sum();
    // though I suppose maybe that is a little out of scope for a beginner
    public int CountForFirstDays(int numberOfDays) => birdsPerDay[..numberOfDays].Sum();
    
    public int BusyDays() => birdsPerDay.Count(birds => birds >= 5);
}
 ```
 
 Is totally valid C# but doesn't compile.

**Comment by kotp** [comment]
OP has no access to Forums, but sent a followup [here](https://discord.com/channels/854117591135027261/1085588875877031977/1213559697815375872).

**Comment by ErikSchierboom** [comment]
@bbarry Thanks for the report! This was fixed in https://github.com/exercism/csharp-test-runner/pull/218
