### ISSUE TITLE
Bob too early

### ISSUE THREAD

**Issue by GeF0rs** [exercism/csharp#2276]
I'm going through exercises in C# and exercise Bob opened too early.
There are tests that serve strings with only numbers, for example:
`Assert.Equal("Whatever.", Bob.Response("1, 2, 3"));`

And in order to determine that there is at least one letter character, you need to use either a linq or a loop
However, at the moment when this task opens, we know nothing about either one or the other.

I suggest either opening the exercise later or removing some of the tests.

**Comment by ErikSchierboom** [comment]
https://github.com/exercism/csharp/pull/2277 adds `for-loops` as a prerequisite.
