### ISSUE TITLE
Use FsCheck for property-based tests in diamond exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#251]
In the `diamond` exercise, the tests are defined as property-based tests. At the moment, we just use member data, but this is a great moment to introduce [FsCheck](https://github.com/fscheck/FsCheck). 

Besides replacing the tests with FsCheck-based property tests, we should also add information to the `HINTS.md` file about FsCheck.

**Comment by jpreese** [comment]
Just as a heads up, I'll take this one.

**Comment by ErikSchierboom** [comment]
Thanks!

**Comment by jpreese** [comment]
#332 merged -- issue can be closed.
