### ISSUE TITLE
Add documentation on how to add or update a test data generator

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#264]

**Comment by jpreese** [comment]
I'd also like to include in this, **why** we have a generator. Talk about the canonical data, versions, etc.

**Comment by ErikSchierboom** [comment]
Good point. We should take care not to duplicate any of the content that already exists, e.g. https://github.com/exercism/docs/tree/master/language-tracks/exercises and https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/test-suites.md.

**Comment by ErikSchierboom** [comment]
Fixed by #399.

**Comment by jpreese** [comment]
Closing
