### ISSUE TITLE
Transpose exercise has a wrong test case.

### ISSUE THREAD

**Issue by Smarticles101** [exercism/csharp#305]
The last exercise under the transpose exercise has a wrong test case.

The problem is [here](https://github.com/exercism/csharp/blob/master/exercises/transpose/TransposeTest.cs#L257). The last two spaces in the string on that line should not be there.

The example solution needs to be reworked a little bit as well in order to solve the fixed test case.
I would go ahead and make a pr to fix both, but I'm not familiar with C#

**Comment by robkeim** [comment]
Thanks @Smarticles101 for reporting this!

@ErikSchierboom has been doing a lot of work to get all of the test cases generated programatically so that should be pretty easy to change it's just the example solution that will need to be tweaked.

**Comment by ErikSchierboom** [comment]
@Smarticles101 I've just merged #306 which fixes this!
