### ISSUE TITLE
Multiple CI servers?

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#338]
Really just trying to familiarize myself with the project, how things work, potential areas for improvement, etc and had a question about our CI servers.

I noticed on our repository homepage, none of the links to the CI servers point to the correct location, but on top of that, why do we have four? Looking back at a previous PR, its checking AppVeyor twice, Travis, and Circle CI -- all of which essentially point to the same build script. I'd think we'd only need one, probably Travis since that seems to be the norm on the other tracks.

Assuming there are indeed some shinanigans going on here, I'd love to clean these up as I honestly haven't had a ton of experience setting up CI on github. I think this would be an excellent opportunity to learn how to setup/config them here.

**Comment by ErikSchierboom** [comment]
The reason that there is more than one build server is that I wanted to test that things work on multiple platforms. With AppVeyor, we can verify that everything works on Windows and with CircleCI and Travis we can test for Unix/MacOS.

However, I might have gone a little overboard with these build servers, as it is highly unlikely that there are cross-platform issues with our code. So maybe we should reconsider.

So which CI servers to keep? You bring up a good point that Travis is the norm on the other tracks, so maybe we should just keep that? @robkeim what do you think?

**Comment by jpreese** [comment]
Ah ok, that makes sense. I'm not necessarily partial to any one in particular, as stated above maybe Travis for conformity. Though I would vote to drop it down to a singular CI for simplicity. I agree that our code shouldn't have any cross platform issues, especially being on .NET Core.

**Comment by robkeim** [comment]
@ErikSchierboom @jpreese 

I remember wondering about this before and I thought I had asked but can't find the trace of the conversation here in GitHub.

I agree that given the scope of what we're doing the chance of cross-compatibility issues is small, and I'm always for simplicity so I'd give a thumbs up to only having Travis.

**Comment by ErikSchierboom** [comment]
Okay. I've created an new [issue](#340).

**Comment by robkeim** [comment]
Thanks @ErikSchierboom.

@jpreese I'm going to go ahead and close this issue now that we have #340.
