### ISSUE TITLE
Remove CircleCI and AppVeyor integration

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#340]
See #338

**Comment by jpreese** [comment]
I can handle the CircleCI/AppVeyor config removals, but we'll need some super powers to disable the builds / web hooks.

**Comment by kytrinyx** [comment]
On it!

**Comment by kytrinyx** [comment]
The AppVeyor build is gone.

**Comment by kytrinyx** [comment]
The CircleCI build is gone.

**Comment by ErikSchierboom** [comment]
Thanks @kytrinyx !
