### ISSUE TITLE
Implement Complex Numbers exercise

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#342]
Description can be found here:
https://github.com/exercism/problem-specifications/blob/master/exercises/complex-numbers/description.md

**Comment by robkeim** [comment]
I'd like to take this exercise but I think it's going to be a tricky one to get the test cases to generate automatically... it will put the new test case generator to the test :)

**Comment by jpreese** [comment]
@robkeim all yours! I keep getting side tracked with other exercism issues

**Comment by ErikSchierboom** [comment]
This will indeed be tricky. I'm really interested in your findings.

**Comment by robkeim** [comment]
I'm going to try to get some other generators done before tackling this one so I get a better understanding of how they work.

**Comment by ErikSchierboom** [comment]
@robkeim Sounds like a plan! 👍 Don't forget to mention any oddities or improvements you'd like to see.

**Comment by robkeim** [comment]
Will do 👍

**Comment by robkeim** [comment]
Done!
