### ISSUE TITLE
Generator does not read latest canonical data

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#347]
I recently opened a PR over in the problem-specifications repo to fix the TwoFer exercise property name (https://github.com/exercism/problem-specifications/pull/881). I was then going to use the generator to update its tests, but I couldn't get it to grab the latest canonical data.

For the generator, it looks like we're doing a Fetch(), but not actually pulling the data down into the local .problem-specifications repository, which is where its trying to read the canonical-data file from.

**Comment by robkeim** [comment]
This is probably happening because we're not doing a checkout of `origin/master` afterwards so while we have the latest code on disk it's not the active branch. If we checkout `origin/master` after fetching it should work correctly.

**Comment by ErikSchierboom** [comment]
Nice catch! Should be easy to fix. A `git pull` instead of a `git fetch` should do the trick.
