### ISSUE TITLE
My GitHub email notifications are working again :)

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#355]
@ErikSchierboom sorry I dropped off for a while, but I Just realized that when the track got renamed to `xcsharp` to `csharp` my GitHub email notifications fell through my Gmail filter and were getting auto-archived.

The issue is fixed now so I should be more responsive! Sorry about that.

@jpreese welcome to the team it's nice to have some more help on board, and I'm always happy to see another wolverine... Go Blue!

**Comment by ErikSchierboom** [comment]
@robkeim No problem! It's great to have you back. With you and @jpreese on the team, we can make this the best track there is :)

**Comment by ErikSchierboom** [comment]
@robkeim Oh and by the way, if you'd like you can also edit your data in the [maintainers file](https://github.com/exercism/csharp/blob/master/config/maintainers.json).

**Comment by robkeim** [comment]
Done, just created PR #361.
