### ISSUE TITLE
Return null values or throw exceptions in exercises?

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#360]
@ErikSchierboom @jpreese after seeing #353 and #359 I think we should agree on when we are going to have exercises return null values vs throw exceptions.

I'd like us to have some consistency and purpose in why we use the two. To simplify things we could move either all invalid input to null or to throw exceptions.

What do you guys think?

**Comment by jpreese** [comment]
Hm, thats tough. 

So my opinion is that the canonical-data should be the source of truth. Whatever is there, is what we render. I don't really think we should be making our own assumptions about what expected should be. Which means I believe we should just support both, and blame the canonical-data for using both.

An example of what I mean is take the [phone-number](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json) canonical-data and the [collatz-conjecture](https://github.com/exercism/problem-specifications/blob/master/exercises/collatz-conjecture/canonical-data.json) canonical-data.

phone-number explicitly states the expected return value should be `null` and the collatz-conjecture explicitly states it should return an error. I agree that they should probably be consistent, but I don't think thats our job. My vision is that our tests match the canonical data.

**Comment by robkeim** [comment]
Ok, I had forgotten some exercises canonical data called for `null` while others were specifying "errors" which transition in C# as `Exceptions`. In that case I agree with you that we shouldn't be adding rules in our track and should follow what the canonical data specifies. That seems like a good policy to me!
