### ISSUE TITLE
Normalize string topics

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#370]
At the moment, we use both the "Strings" and "Text Formatting" topics. I was thinking that perhaps we should just use the "Strings" topic, as the distinction is very small and might just confuse people.

**Comment by robkeim** [comment]
@ErikSchierboom is there any sort of cross track standardization for topics today? If not, I'm not against migrating the Text Formatting topics to strings as I agree the distinction isn't very pronounced.

**Comment by ErikSchierboom** [comment]
@robkeim No there is no standardization. In fact, there was sort of an agreement to not try to standardize too much.

**Comment by robkeim** [comment]
@ErikSchierboom in that case I'd say go ahead and combine the two topics!

**Comment by ErikSchierboom** [comment]
Okay I will!

**Comment by jpreese** [comment]
@ErikSchierboom @robkeim I completely agree with this. Text formatting is pretty specific, I'm down with making a little bit more generic.

**Comment by ErikSchierboom** [comment]
Closed by #377
