### ISSUE TITLE
Stub files

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#390]
At the moment, we provide stub files for all exercises. However, while adding .NET Core support to the F# track, I've decided upon choosing a slightly different approach. In the F# track, the exercises labeled as difficult (difficulty 8-10) don't have any stub implementation, just an empty stub file (so you don't have to create the file). What do you feel about also doing this for the C# track?

**Comment by robkeim** [comment]
I haven't had the chance to review your F# changes yet @ErikSchierboom, but what's the purpose of leaving the stub files out for the harder exercises... to make things more challenging?

I like the idea of not having to do the boiler plate work each time start a new exercise... do you feel like it adds interest to create the skeleton instead of just adding overhead?

**Comment by ErikSchierboom** [comment]
Yes, making it more challenging was the idea. However, I must admit that it makes less sense for C# than for F#. With F#, there is a lot of type inference which means that types are specified far less frequently. Part of the F# skillset people should learn IMHO is that they should be able to infer the types themselves. I thought to go one further for the difficulty exercises by removing the stubs, but it might not actually help much. I won't mind reverting to the previous state (stubs without types), if that is what the outcome is of our discussion.

**Comment by ErikSchierboom** [comment]
I have given it some thought, and have decided against removing the stubs for the C# track. The main reason is that in C# type inference of function parameters etc. is non-existent and virtually all C# IDE's allow generation of the stub methods.

**Comment by robkeim** [comment]
@ErikSchierboom I hadn't thought about developing the skill of when to specify types in F# but you're right that it's definitely something important to learn and can be non-trivial for people starting out, so I like that direction! I agree this would be less valuable on the C# track though.

**Comment by ErikSchierboom** [comment]
@robkeim Great to hear! Thanks for helping.
