### ISSUE TITLE
Add Circular Buffer Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#403]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by bangsholt** [comment]
I'll have a look at this one :)

**Comment by robkeim** [comment]
@bangsholt which cases exactly are you referring to that don't have an expect clause?
https://github.com/exercism/problem-specifications/blob/master/exercises/circular-buffer/canonical-data.json

I just glanced at this *very* quickly, but in the cases where there's no `expected` it seemed that is because `should_succeed` is false.

**Comment by bangsholt** [comment]
The problem case seems to be the one I've linked to here:

https://github.com/exercism/problem-specifications/blob/e7a596c1a76038ad441c281234634667b2222d81/exercises/circular-buffer/canonical-data.json#L336

A KeyNotFound exception is thrown - I don't understand why it's working previously with the other steps that doesn't have should_succeed and expected.

**Comment by ErikSchierboom** [comment]
@bangsholt Ah I see. The problem with the circular buffer test case is that you have several operations that have to be executed in a single test, some of which are only there to modify the state and which return value does not need to be tested. This is the case in the canonical data case you mention. Does that make sense?

**Comment by ErikSchierboom** [comment]
I'm working on this.
