### ISSUE TITLE
Add Diamond Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#406]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by avjgit** [comment]
[Current tests](https://github.com/exercism/csharp/blob/master/exercises/diamond/DiamondTest.cs) are using property testing.
Whereas [current canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/diamond/canonical-data.json) contain value based testcases.
So, canonical data should be updated by adding property based testcases?
Or should rewrite them?
What would be an impact on generators in other languages?

**Comment by ErikSchierboom** [comment]
Great observation. I think in this case we might not actually want to use the canonical data, as I think there is value in the property-based testing approach. @jpreese @robkeim what do you think?

**Comment by felix91gr** [comment]
Property Testing for the win!

It's so much stronger and descriptive than Case Testing.

That said, is it easy to follow for people doing the exercises? That should be the main criteria to apply here, right?
If it is, I think this is actually **better in every way**. It generalizes over all the domain of input. Unless the exercise itself changes, the canonical testcases will always be behind this exercise's test suite.

**Comment by jpreese** [comment]
Yeah, I would agree. This is a nice case to have where we can expose developers to property based testing (the tests themselves even use FsCheck).

**Comment by robkeim** [comment]
I agree we have a good reason for diverging from the canonical data here, and I think it would be sad to give up the opportunity of introducing/using property based testing just to conform with the canonical data.

When we go to solve https://github.com/exercism/csharp/issues/434 we'll need to have another status that is explicitly ignoring the canonical data.

**Comment by ErikSchierboom** [comment]
@robkeim Good idea!
