### ISSUE TITLE
Add Difference of Squares Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#407]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by felix91gr** [comment]
I want this issue! I think I can finish the tests by this weekend. How should I mark it so that someone else isn’t working on it as well?

**Comment by jpreese** [comment]
Thanks @felix91gr ! Just saying something here should suffice. If someone looks at this issue, they should see that you had interest in it.

**Comment by felix91gr** [comment]
Awesome :) Thanks!

**Comment by jpreese** [comment]
No problem! Please do not hesitate to reach out if you get stuck on anything. We're here to help 👍

**Comment by jpreese** [comment]
Were you still working on this one @felix91gr?

**Comment by felix91gr** [comment]
Yes! Just gimme a couple of days... I’ve been busy with uni work 😅

**Comment by ErikSchierboom** [comment]
Closed by #471
