### ISSUE TITLE
Add ETL Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#409]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by InKahootz** [comment]
I've started on this one.

**Comment by InKahootz** [comment]
I've run into a design decision. The `input` from the canonical-data is of type `IDictionary<int,IList<string>>` which switches to `default:` in the `ValueFormatter` class. Would it be helpful to add this to the `ValueFormatter` class or do I just write some methods in the generator class that formats it for me while Arranging?

If wanted in ValueFormatter I think I will also need to add a FormatMultilineEnumerable  method that doesn't output a variable name like the current one.

**Comment by ErikSchierboom** [comment]
@InKahootz Well, good point. It may be easier to just do the formatting in the generator class itself. We can always refactor to another method if needed later.

**Comment by ErikSchierboom** [comment]
Closed by #462.
