### ISSUE TITLE
Add Flatten Array Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#410]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by felix91gr** [comment]
Working on this one!

**Comment by jpreese** [comment]
Closed via #473, thanks @felix91gr!

**Comment by felix91gr** [comment]
^^ it's my pleasure :)
