### ISSUE TITLE
Add Largest Series Product Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#412]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by felix91gr** [comment]
I'll tackle this one as well

**Comment by felix91gr** [comment]
I finished this one as well :)
I'll wait for #471 to get merged before I open a PR though, because I branched off of that commit.

**Comment by felix91gr** [comment]
It's here: #474

**Comment by felix91gr** [comment]
Now that the PR's been merged, this issue can be closed :)

**Comment by jpreese** [comment]
Awesome! Thanks, @felix91gr.
