### ISSUE TITLE
Add List Ops Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#413]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by deyshin** [comment]
I started working on this. Please allow me a week or so.

**Comment by robkeim** [comment]
Sounds good @deyshin, please let us know if you have any questions!
