### ISSUE TITLE
Add Meetup Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#414]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by InKahootz** [comment]
Started on this one.

**Comment by jpreese** [comment]
Were you still wanting to complete this one @InKahootz ?
