### ISSUE TITLE
Add Minesweeper Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#415]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by felix91gr** [comment]
I'm signing up for this one as well!

**Comment by ErikSchierboom** [comment]
Closed by #472
