### ISSUE TITLE
Add Nucleotide Count Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#416]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by InKahootz** [comment]
I'll hop in with this one! Looking over the files, it seems to be a easy starter :smiley:

**Comment by ErikSchierboom** [comment]
@InKahootz Good observation! The test generators should just follow the canonical data as specific in the [problem-specification repo](https://github.com/exercism/problem-specifications), so if that means losing a couple of test, that is completely fine.

**Comment by ErikSchierboom** [comment]
Closed by #456
