### ISSUE TITLE
Add OCR Numbers Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#417]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by GKotfis** [comment]
I'll deal with it

**Comment by GKotfis** [comment]
I need to figure it out how to generate valid digit representation as code:
![image](https://user-images.githubusercontent.com/7391978/31068688-75710c6e-a759-11e7-9fbb-636447f97e72.png)

Don't know if DotLiquid have such option to generate non string characters that are part of code - here '+' sign

**Comment by GKotfis** [comment]
Have something that generate almost desired output:
![image](https://user-images.githubusercontent.com/7391978/31071573-d9521b0a-a764-11e7-8a07-0fdc51f3b412.png)
as you see I lost indentation - argument not starting in the same line as  method call. But maybe it's ok?

**Comment by ErikSchierboom** [comment]
@GKotfis Hmmm, that's almost correct! There is an Indent function somewhere, but I don't know if you can easily use that in your code. If not, I think this is fine.

**Comment by ErikSchierboom** [comment]
Closed by #450
