### ISSUE TITLE
Add Pascals Triangle Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#418]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by bmeverett** [comment]
I'll take a look at this one as well. I think I got most of it, just trying to figure out the last two cases that are null and return -1

**Comment by ErikSchierboom** [comment]
@bmeverett Those inputs should throw an exception. To get that behavior in a generator, checkout this code: https://github.com/exercism/csharp/blob/9e4635b7dfc304c3985795054398d0a6402a9941/generators/Exercises/NthPrime.cs
