### ISSUE TITLE
Add Robot Name Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#419]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by Gimly** [comment]
I'm not sure I'm getting how the generators work exactly. For this exercise, there is no canonical data specified, wouldn't that mean that the exercise doesn't need a generator?

**Comment by ErikSchierboom** [comment]
Yes, if there is no canonical data for this exercise, there can't be a test generator. Sorry about that.

**Comment by Gimly** [comment]
No worries, I was quite confused. So I guess you can close this issue because this exercise doesn't have any canonical data.

**Comment by GKotfis** [comment]
I'm also trying to figure it out connection between canonical-data and generator. But I didn't find any canonical-data.json in this repository. So this issues are valid? :)

**Comment by Gimly** [comment]
@GKotfis The canoncial-data.json are defined in another repository, the https://github.com/exercism/problem-specifications which contains all the problem specifications (as the name says 😄).

If you run `dotnet run` in the generator folder of this repository then it will run all generators.

**Comment by ErikSchierboom** [comment]
There is some documentation on the test generators here: https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md

**Comment by robkeim** [comment]
I'm closing this issue since there's no canonical data for this exercise.

@Gimly and @GKotfis thanks for looking into this! Feel free to update or suggest updates for the documentation for the generators as well. So far, we've had a very small group of contributors which hasn't forced us to be very rigorous with our documentation :)
