### ISSUE TITLE
Add Robot Simulator Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#420]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by nikibobi** [comment]
I will take this task

**Comment by GKotfis** [comment]
I have a solution but need to resolve one problem with the same description for two test. If you take a look at [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/robot-simulator/canonical-data.json) description _"does not change the position"_ appears two times. So it renders two methods with the same name. Two ideas come to my mind:
1. Update canonical data
2. Do something on generator side to make unique method names by adding some suffix

**Comment by ErikSchierboom** [comment]
@GKotfis There already is such an option in the `CanonicalDataCase` class: `UseFullDescriptionPath`.

**Comment by ErikSchierboom** [comment]
Closed by #521.
