### ISSUE TITLE
Add Two Bucket Test Generator

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#424]
This issue is part of an overall initiative to complete #195.

The documentation on how to add generators can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md). If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by GKotfis** [comment]
I'll deal with it.

**Comment by GKotfis** [comment]
Question about file & class names. Exercise, project name and canonical-data are "TwoBucket". But class name in exercise is "TwoBucket**s**. As I see generator use class name also for finding canonical-data and here is the problem. The quickest option will be to change class name in exercise to TwoBucket?

**Comment by jpreese** [comment]
@GKotfis yep! Feel free to update the existing class. This case is specifically outlined in the provided generators documentation :)

**Comment by robkeim** [comment]
@GKotfis for some historical context, when this project started we didn't have any canonical data so each of the different tracks had a lot of liberty in their implementations (naming, what they tested, etc).

Now we're trying to standardize to have a more consistent experience across tracks which is great, but we're trying to retrofit our existing solutions into the generators. For some exercises it's very straightforward but other exercises need a larger refactoring.

**Comment by ErikSchierboom** [comment]
Fixed by #447.
