### ISSUE TITLE
Add the exercises without canonical data to test generator

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#434]
Here's what I shared about this in #396:

Right now we have to manually check to see if an exercise gets canonical data in the future. I'd like to have it integrated into the generator with some sort of flag saying "this doesn't have data" and then it can start throwing exceptions in the future if the data is created so we know we'll have to implement it (keeping my fingers crossed that all exercises will have canonical data someday)

**Comment by robkeim** [comment]
With the diamond exercise (https://github.com/exercism/csharp/issues/406) we also decided to explicitly ignore canonical data in favor of property based testing, so that should be taken into account when solving this issue.

**Comment by ErikSchierboom** [comment]
I'm working on this.
