### ISSUE TITLE
Clock test generator should render Assert.Equals

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#435]
The Clock test generator currently renders:

```
Assert.True(sut.Equals(new Clock(15, 37)));
```

For the "Clocks with same time" test case. This should be simplified by using Assert.Equals

**Comment by paulogleuwyo** [comment]
I'll take a crack at the clock exercise #437

**Comment by robkeim** [comment]
@R0nd were you still planning on continuing with this? If not, it seems like @paulogleuwyo is interested in looking into it as well.

**Comment by R0nd** [comment]
When I last looked, the current source code wouldn't compile. Giving it up for now.

**Comment by robkeim** [comment]
@R0nd there was a bad commit that caused the solution to no longer compile but it was fixed here:
https://github.com/exercism/csharp/issues/438

In addition we added this solution to the build so the issue won't happen again:
https://github.com/exercism/csharp/issues/441

If you're still interested in contributing there are other exercises and as long as you sync your branch with the latest master the compilation issues should be fixed.

**Comment by jpreese** [comment]
Resolved by #453
