### ISSUE TITLE
Kindergarten problem. Not clear which functions does what

### ISSUE THREAD

**Issue by NobbZ** [exercism/csharp#436]
@rwobben commented on [Wed Sep 27 2017](https://github.com/exercism/exercism.io/issues/3638)

Hello, 

I try to solve the kindergarten challenge in c#. I see that there are 3 seperate functions given: Garden, GetPlants and DefaultGarden. 

I think GetPlants must give me the answer to this problem.
But what schould the other two do exactly ? 

Roelof

---

@NobbZ commented on [Thu Sep 28 2017](https://github.com/exercism/exercism.io/issues/3638#issuecomment-332753690)

Since this is a question spoecific to the C# version of the exercise (canonical data only knows about the property `plants`), I'll move you over there.

**Comment by NobbZ** [comment]
Let me chime in with possible solutions to this problem:

* Remove all methods that are not part of the canonical data
* Put documentational comments to the method declarations in the stub
* extend the README of the exercise to explain the extended requirements

**Comment by ErikSchierboom** [comment]
All very good points! I think we can solve this by better conforming to the canonical data, which should be done by creating a test generator for it: #411.

**Comment by NobbZ** [comment]
Perhaps try to explain here for now to make @rwobben able to continue with the exercise?

**Comment by ErikSchierboom** [comment]
@NobbZ I'll do that tomorrow!

**Comment by ErikSchierboom** [comment]
@NobbZ @rwobben The `Garden.DefaultGarden` method is static factory method that returns a new `Garden` instance with default child names. The `Garden` constructor allows you to specify the child names. Lastly the `GetPlants` method is an instance method of the `Garden` class, and returns the plants for the child name passed as its argument.

I'll be working on creating an updated version of the exercise to conform to the canonical data.
