### ISSUE TITLE
What is the story of Linters in C#?

### ISSUE THREAD

**Issue by masters3d** [exercism/csharp#476]
Hi, 
I am curious about the status on linters in C#?
In Swift we have SwiftLint and in Typescript we use TSLint. What is the a cross platform linter for C#? I'll be happy to help implement this but I just need a little bit of direction.

I read about this but this is new:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers

**Comment by ErikSchierboom** [comment]
@masters3d There already is an existing issue on this topic: #203. Could you chime in there?
