### ISSUE TITLE
Implement the Isbn Verifier exercise

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#484]
This new exercise needs to be implemented.

Problem description: https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/description.md

Canonical data: https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/canonical-data.json

**Comment by robkeim** [comment]
I'd like to do this one, I should have time this weekend.

**Comment by ErikSchierboom** [comment]
Great!

**Comment by jenlouie** [comment]
Hi @robkeim, did you start working on this one already? If not, I'd love to do it. I have some time to work on it in the next few days. Thanks!

**Comment by robkeim** [comment]
Hello @jenlouie! I've been caught up in some other things so I haven't had time to dig into this yet. Feel free to start working on it, but make sure that you're familiar with our generator system for test cases before starting. Thanks!

**Comment by jenlouie** [comment]
@robkeim, will do! Thanks!
