### ISSUE TITLE
Update exercises with latest canonical data

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#488]
I started the first batch of this work in #487 but there are still three exercises remaining (as of Nov 12):
- AllYourBase (changed to using "error" structure)
- BeerSong (changed to returning an array which isn't currently being formatted multi-line. That means the test validating the entire song is a reaaalllllyyyyy long line :) I think we should update the array to be able to be formatted multiline)
- NthPrime (changed to using "error" structure)

@ErikSchierboom FYI

**Comment by ErikSchierboom** [comment]
I'm working on this

**Comment by ErikSchierboom** [comment]
@robkeim PR #492 doesn't include the BeerSong update, which I've included in a new issue: #493.
