### ISSUE TITLE
Automating canonical data updates?

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#489]
I'm opening this issue with an open-ended question to provoke a discussion...

There's quite a bit of churn on the canonical data and right now we're manually updating the exercises as we stumble up on them. I'm wondering what the complexity would be to automate handling these canonical data updates and if it would be worth implementing a system to handle these updates "automatically".

The way I see it we'd need a process that would:
- Look for canonical data updates (could be a polling mechanism or triggered based on GitHub updates)
- Attempt to update the exercise with the latest version of the canonical data:
- If it builds, create a PR with the udpate
- If it doesn't build, create an issue to be investigated

That means the ideal flow would be a canonical data update is triggered and all we have to do is review/merge the PR.

@ErikSchierboom and @jpreese what do you guys think? Would something like this be worth investing in? Not a good ROI? Completely useless? :) (looking for honest feedback here)

**Comment by ErikSchierboom** [comment]
Well, my first thought is that it would be much effort for not that much gain, but if anyone wants to try and take this on, I wouldn't object.

**Comment by robkeim** [comment]
Thanks for the feedback @ErikSchierboom. That was my gut feeling as well, but wanted to see what other people's thoughts were.

I'll go ahead and close this issue for now unless anyone else sees an easy way to do this that wouldn't require a large investment.
