### ISSUE TITLE
Pangram: Add tests for accented characters and non-latin scripts

### ISSUE THREAD

**Issue by NobbZ** [exercism/csharp#502]
@isani commented on [Fri Dec 22 2017](https://github.com/exercism/problem-specifications/issues/1048)

On the csharp track, many pangram solutions use the built-in method IsLetter(char). This method matches more than a-z, which leads to wrong results when the input contains Unicode letters. There are currently no tests that contain letters outside the a-z range, and thus a range of bugs are not caught.

The following strings should be tested as _not_ pangrams (because they don't contain an 'a'):

"äbcdefghijklmnopqrstuvwxyz"
"αbcdefghijklmnopqrstuvwxyz"

The following strings should be tested as pangrams (to ensure input with Unicode isn't just rejected):

"the quick brown fox jumps over the lazy dög"
"the quick brown fox jumps over the lazy dөg"

---

@NobbZ commented on [Fri Dec 22 2017](https://github.com/exercism/problem-specifications/issues/1048#issuecomment-353602914)

Due to very different support of unicode across languages the problem-specifications do only cover ASCII (we haven't agreed if we use traditional 7bit or enhenced 8bit yet ;), some people imply the one, some people imply the other when reading ASCII).

If a language does cope well with Unicode handling, then its in the responsibility of the tracks maintainers to avoid and test against unicode pitfalls of that language.

Can you therefore file a bug at the [C# issue](https://github.com/exercism/csharp/issues) tracker?

cc @exercism/csharp

---

@coriolinus commented on [Fri Dec 22 2017](https://github.com/exercism/problem-specifications/issues/1048#issuecomment-353603038)

This has been discussed before in https://github.com/exercism/problem-specifications/issues/428.

---

@NobbZ commented on [Fri Dec 22 2017](https://github.com/exercism/problem-specifications/issues/1048#issuecomment-353603130)

Oh, it seems as if I am allowed to close here, so I'll move the issue over to C# repo directly.

**Comment by ErikSchierboom** [comment]
I'm inclined to close this issue, seeing how the readme currently explicitly specifies: 

> The alphabet used consists of ASCII letters a to z, inclusive, and is case insensitive. Input will not contain non-ASCII symbols.

Thoughts?

**Comment by bressain** [comment]
I say close it. If we care about handling unicode characters in a language track, seems like we should include an entire exercise around unicode handling and limit scope on other exercises.

**Comment by ErikSchierboom** [comment]
Okay, I'll close it.
