### ISSUE TITLE
bracket-push provides solution on cli fetch

### ISSUE THREAD

**Issue by martinfreedman** [exercism/csharp#506]
when fetching this exercise on windows cli, bracketpush.cs contains a solution rather than the skeleton code.

**Comment by ErikSchierboom** [comment]
Good catch! Would you be interested in creating a PR to fix this?

**Comment by martinfreedman** [comment]
ok will try

**Comment by martinfreedman** [comment]
Pull request #510

**Comment by ErikSchierboom** [comment]
Closed by #510
