### ISSUE TITLE
Transpose still has wrong test cases

### ISSUE THREAD

**Issue by martinfreedman** [exercism/csharp#507]
Tests many_lines() and First_line_longer_than_second_line() did not get spacing correct at the end.

**Comment by ErikSchierboom** [comment]
@martinfreedman Is that also in the canonical data? Or is perhaps the exercise not updated yet to the latest canonical data?

**Comment by martinfreedman** [comment]
In problem-specifications/exercises/transpose/canonical-data.json:-
a) there is no entry for "many lines"  ( there is `Many_lines()` in the TransposeTest.cs)
b) "first line longer than second line" appears incorrect - the last row should read `". "` not `"."`  (compare to the last line of "second line longer than first line")

So I provisionally conclude that: 
A) the canonical data needs to be fixed - has this issue (a) been noted anywhere else? 
B) The exercise needs to be updated to the latest canonical data once (A) has been fixed.

**Comment by ErikSchierboom** [comment]
To check if A) has been noted anywhere, please go to the [problem-specifications repo](https://github.com/exercism/problem-specifications/issues).

Once it has been fixed in A), I'll make sure B) is done.

**Comment by martinfreedman** [comment]
My bad, misread the Readme . Thanks @petertseng
