### ISSUE TITLE
Hangman is not FRP

### ISSUE THREAD

**Issue by martinfreedman** [exercism/csharp#508]
Meant to use FRP , in c# that is Reactive Linq. However the tests force one to use a conventional .Net event rather than Subscribe to an Observable.

**Comment by ErikSchierboom** [comment]
Hmmm, good point. Do you think it would be a good idea to convert the exercise to use observables? 

CC @robkeim

**Comment by martinfreedman** [comment]
Yes and No.

I don't recall there being an exercise for events  and this is good for that purpose too. That is, we need an exercise like this, as it is currently configured. 

On the other hand, I imagine we agree we also need a Rx exercise too. 

So really, IMV, there should be two exercises. It is  possible to  combine them into one,  in order to cohere with the cross-language exercise framework - if that is a constraint.

I am happy to do the PR(s) once we have completed discussion here.

**Comment by ErikSchierboom** [comment]
I would rather not combine the two concepts, to ease the learning curve. Do we have another exercise where we can apply events or FRP? @robkeim?

**Comment by martinfreedman** [comment]
Need to do React, not there yet in the language track (On Connect but not started). WIll download it manually and then report back

**Comment by ErikSchierboom** [comment]
Okay, thanks for checking into it!

**Comment by mrtank** [comment]
Oops. Accidentally I made it Rx exercise in [this pull request](https://github.com/exercism/csharp/pull/727) before checking if React exercise would be the right candidate for it.

**Comment by mrtank** [comment]
After checking React exercise. IMHO [React](https://github.com/exercism/csharp/tree/master/exercises/react) is about implementing Rx. Hangman is more about using it.

**Comment by ErikSchierboom** [comment]
> After checking React exercise. IMHO React is about implementing Rx. Hangman is more about using it.

That is correct!

**Comment by ErikSchierboom** [comment]
Closed by #727, due to the heroic efforts of @mrtank.
