### ISSUE TITLE
Add header with version to exercises that have no generator

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#514]

**Comment by martinfreedman** [comment]
Like it

**Comment by robkeim** [comment]
@martinfreedman exercises that we're auto-generating automatically bump up the version number as the canonical data (input used to generate the unit tests). The only case we have to be careful with is a non-generated file with a version that moves to a generator in the future. It might be sort of an edge case, but we want a way to not "go down in versions" when the generator is created for a specific exercise.

**Comment by martinfreedman** [comment]
@robkeim But this info is not visible on the web site, when we are looking at others' solution?

**Comment by ErikSchierboom** [comment]
> I think we could modify the test generator to also update the corresponding Example.cs to add the version. @ErikSchierboom what do you think about the feasibility of that?

Well, I think we don't need to do this, because as far as I understood, the Exercism reboot (slated for release somewhere this year) also includes the test file IIRC. This means that you always get to see which test file a solution was submitted for, which would make adding the version to the example file not necessary. However, if people think it would be a good idea to also include the version number in the solution file, I don't think that would be hard.

**Comment by martinfreedman** [comment]
I was more aguing to see it on the relevant web page not in the code itself. A user could delete it. If the new site has an alternate solution supplying the test file, then good. 

But on that latter point what if the user alters the test file so their solution passes?

**Comment by martinfreedman** [comment]
Yes, after thinking about that, I agree. Further being able to see the tests, one can comment on that too!

Given this will be on the new site  I think we can close this

**Comment by ErikSchierboom** [comment]
Okay, closed.
