### ISSUE TITLE
RNA Transcription Canonical Test are not testing for rna.Transcribe() "ToDna"

### ISSUE THREAD

**Issue by martinfreedman** [exercism/csharp#516]
This is a simple enough challenge as it is but a key was to reverse the transposition. This has been lost as the new tests no longer test for Complement.ToDna(string) but only Complement.ToRna(string) but as RnaTranscription.ToRna(string). This IMHO has really impoverished this exercise

**Comment by robkeim** [comment]
@martinfreedman I believe this was an explicit decision to remove the conversion back as while it makes sense from a programming perspective it doesn't from a biological one:
- https://github.com/exercism/plsql/issues/11
- https://github.com/exercism/problem-specifications/issues/148

**Comment by martinfreedman** [comment]
WTF! https://en.wikipedia.org/wiki/Reverse_transcriptase!!! I does exist biologically and it, AFAICS, ruins to point of this already simple exercise.

**Comment by ErikSchierboom** [comment]
@martinfreedman This discussion is probably a better fit for `exercism/problem-specifications`. There is an [open PR](https://github.com/exercism/problem-specifications/pull/1134) that involves this specific exercise, and it is better to have these discussions there.

**Comment by martinfreedman** [comment]
Yup already moved there
