### ISSUE TITLE
CSharp Clock IEquatable is not required for tests

### ISSUE THREAD

**Issue by kytrinyx** [exercism/csharp#523]
From @Gander7 in https://github.com/exercism/exercism.io/issues/3736

-----

Unless I'm doing something wrong or I'm entering this issue in the wrong place,

csharp Clock challenge README.md mentions that implementing IEquatable is required for the challenge.
I was able to complete the csharp Clock challenge without implementing IEquatable or creating any equality functions. 

There are no tests, that I can see, that test Equals(Clock), Equals(Object), GetHasCode(), ==, or !=. 
I can provide solution if needed.

If Equatable is required, then maybe add tests for those overriden methods.
If Equatable isn't required, then remove it from the readme?

**Comment by ErikSchierboom** [comment]
This is due to an outdated readme. Will fix this!
