### ISSUE TITLE
Implement Yacht exercise

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#527]
If you want to implement this exercise, please note that you need to ensure the test cases are generated based on the input.

Here's the exercise description:
https://github.com/exercism/problem-specifications/blob/master/exercises/yacht/description.md

Here's the test case data:
https://github.com/exercism/problem-specifications/blob/master/exercises/yacht/canonical-data.json

**Comment by ShamilS** [comment]
I have just completed this task implementation using .NET 4.6.2 Console App and NUnit 3.10.1 against current defined test set.
The solution is currently committed and pushed to [my forked repository's **_yacht-dice-game_** branch](https://github.com/ShamilS/csharp/tree/yacht-dice-game/exercises/yacht).
I'm not sure how to proceed further: I'm new to GitHub and exercism.io. 
Should I convert the solution to .NET Core 2.0 and XUNit and submit a pull request?
Please advise.

**Comment by ErikSchierboom** [comment]
@ShamilS Perhaps you could first contact @robkeim, as he indicated that he was already starting with this issue?

**Comment by ShamilS** [comment]
Erik, OK I can contact Rob (@robkeim). How should I do that?

I must note I didn't know that Rob has already been working on this task when I have got it solved yesterday: I have just jumped into this exercism.io site yesterday morning and I'm new to all this GitHub cooperation.  My notice on my version of Yacht problem solution and its code can be neglected by Rob et al - no problem.

**Comment by robkeim** [comment]
Hello @ShamilS you can contact me here is perfect :) Welcome to Exercism.io, GitHub, and open source! 

I had this on my todo list, but hadn't started it yet so there's no wasted work and @ErikSchierboom and I would be very happy to have you contribute!

Looking through your branch it looks like you would need to update your generator to conform with what we already have. Hopefully that will make a lot of the boiler plate JSON parsing disappear :) Unfortunately, we don't have a lot of documentation around how the generator works (yet), but it should be pretty straight-forward to use (and we're definitely open to feedback on how to make it easier if it's not).

Once that's done you could create a PR from your forked branch and we can review and merge it into the main repo. @ErikSchierboom and I can both help guide you through the process if you get stuck or need help along the way.

Here's an example of a new exercise that I recently added, and you can see the generator doesn't have any code in it because the framework handles everything:
https://github.com/exercism/csharp/pull/490/files

**Comment by ErikSchierboom** [comment]
@ShamilS As @robkeim said, it is probably best to look at other PR's that have added a new exercise. The documentation for the generators is indeed lacking, but most of it should be fairly easy to figure out.

If you have any specific questions you can also contact us in our [gitter channel](https://gitter.im/exercism/xcsharp).

**Comment by ShamilS** [comment]
Hi Rob and Erik --

Thank you for your welcoming me to join contributing to this project!
Yes, I will have to learn the Git(Hub) workflow to find the way to properly publish PRs for your review. I will check and I will read through the references you've provided here. I may ask a few questions in the coming days.

Meanwhile as Rob (@robkeim) proposed I have made .NET Core 2.0 solution for the Yacht problem and I have posted it temporarily [on my fork here](https://github.com/ShamilS/csharp/tree/yacht-net-core-2-0/exercises/Yacht2) just to make you sure the task is done. I have currently called the project Yacht2 to not intercept it with my first .NET 4.7.x Yacht project. The screenshot of the tests' run is attached to this posting.

I have called the test methods using _CamelCase_ notation not using underscores - would that be acceptable?

I'd like also to note that (re-)compiling the whole solution under VS2017 takes often "ages" on my i7/12GB notebook, and running xUnit tests, or even just selecting the set of tests is unavailable at all, so I have created a temp solution with just one Yacht2 project to run its xUNit tests in VS test runner (see attached screenshot).

P.S. Yacht solution xUnit test run screenshot:

![yacht problem solution tests results](https://user-images.githubusercontent.com/2162601/38215633-2520f2bc-36d1-11e8-94e8-c17ec5837a61.png)

**Comment by ErikSchierboom** [comment]
@ShamilS Perhaps it would be best if you submitted a PR so that we can comment on that PR? Please look at [this PR](https://github.com/exercism/csharp/pull/490/files) to see which files you are supposed to edit. Note that you should not create test file manually, that should be done using a test generator. In the aforementioned PR, there is a class added to the generators projects. After adding this class to the project, open a command prompt in the generators directory and do: `dotnet run --exercise <name>`, where `<name>` is the slug name of the exercise (in your case `yacht`). This will run the generator for the specified exercise and generate the test file.

**Comment by ShamilS** [comment]
@ErikSchierboom - Done. Please check it here: ['Yacht' problem solution is ready for PR](https://github.com/exercism/csharp/pull/529)

P.S. BTW, this is my first PR on GitHub. Time to celebrate! ;)

**Comment by ErikSchierboom** [comment]
🎉! The PR is already looking quite nice! I've added my comments in the PR. Thanks for helping us with this.

**Comment by ShamilS** [comment]
Thank you, Erik! I have made most of the fixes you requested. Some requested code corrections do not compile well. Please see my comments in the PR and advise how to proceed further with this or a new PR.

**Comment by ShamilS** [comment]
@ErikSchierboom & @robkeim, I have just pushed updated for my PR. Please check.

@ErikSchierboom, I think I have addressed and I have fixed all your requests including solution code changes (I was in a hurry this morning on first round of correction, and I have made mistakes with code changes). They should be OK now,

@robkeim,  I haven't yet (in this PR) used _enum_ for the second function argument as you proposed - to use it the tests have to be regenerated, and I currently have no idea what should be changed in the tests' metadata json and/or Yacht.cs for generator to have tests regenerated using enum as the second.  If you with @ErikSchierboom  will decide to use enum I will make the new PR but instruct me then how the Yacht-related generators .json and .cs file have to be changed.

Thank you both for all your prompt reviews, comments and code fixes proposals.

**Comment by ErikSchierboom** [comment]
@ShamilS I've just reviewed the second iteration! For the places where the generator has to have some logic, I've included links to existing generators that do something similar.

**Comment by ShamilS** [comment]
@ErikSchierboom Thank you, I see your review. I will make the changes tomorrow.

**Comment by ErikSchierboom** [comment]
Closed by #529.
