### ISSUE TITLE
The _Exercises_ solution compilation/rebuilding under VS2017 v.15.3.3 results in a long list of compilation errors.

### ISSUE THREAD

**Issue by ShamilS** [exercism/csharp#528]
The _**Exercises**_ solution compilation/rebuilding under VS2017 v.15.3.3 on Win 10 Pro v.1709, .NET Core 2.0 (see version details in P.S.) results in a long list of compilation errors. Unloading the following projects:

- AtbashCipher
- DotDsl
- ErrorHandling
- Etl
- Hangman
- LargestSeriesProduct
- Pangram 
- React

solves the issue.

I may give it a try to fix the compilation errors in the listed above projects. Should they be all fixed and pushed in one PR, or it's better to fix and to push back via PR every project separately?

P.S. Hosting system and .NET Core 2.0 version info:

\>dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by robkeim** [comment]
Hello @ShamilS, thanks for reporting this issue. We'd definitely appreciate you helping us fix this! Could you share the compilation errors with us (or at least the first few since you said the list is very long)?

In terms of solving them in one PR or multiple PRs it depends on how complex the needed changes are. If it's something where one reference needs to be changed in the csproj then it probably makes sense to make the change for every project in the same PR. If it's going to be a lot of changes in each project then maybe it makes sense to break them down and they could even be split up. Seeing the error might shed some light on the best approach to fixing this.

**Comment by ErikSchierboom** [comment]
@ShamilS Well, actually the purpose of the solution is not to build all projects successfully. This is for a rather simple reason: some projects have a starting point where we would like to help them out a bit, but not too much. In some of these cases, this results in projects that can't be built by default: the user has to do something to make them compile. This is precisely the goal of the exercise. For some exercises making the starting code compile would give away too much of the solution.

Of the list you mention, I am fairly certain the above is the case for the following exercises:

- DotDsl
- ErrorHandling
- Hangman
- React

However, the following projects should be able to be built by default:

- Etl
- LargestSeriesProduct
- Pangram

If you want to, we'd be happy to take PR's for those projects. I don't mind having either multiple PR's, or a single PR, as long as there is a separate commit per fixed project.

**Comment by ShamilS** [comment]
Hi Rob and Erik --

I have attached the errors log to this posting. Please note that I haven't yet tried to analyse/fix them - I have just unloaded several projects with errors projects to have to rest of solution's projects compiled successfully. I was unaware that this solution could be intentionally/by design made as having compile time errors.

P.S. Compile time errors for VS2017:

[exercises.sln.errors.VS2017.txt](https://github.com/exercism/csharp/files/1869154/exercises.sln.errors.VS2017.txt) (123KB)

**Comment by ErikSchierboom** [comment]
What you should try to do is to open a command prompt in one of the faulty exercise directories and then try to run `dotnet build` to see if there are any errors.

**Comment by ShamilS** [comment]
Done.

The following projects:

- DotDsl
- Hangman
- React

still result in compilation errors. That should be a feature by design AFAIU now.

On the other hand I'd expect to have the same set of compilation errors produced by VS2017 and _dotnet build_'s. But it's different - this difference should be considered MS problem not the problem/issue of the exercism.io C# sources?

P.S. The compilation logs for the DotDsl, Hangman and React projects:

[Errors - dot-dsl-build-log.txt](https://github.com/exercism/csharp/files/1871033/Errors.-.dot-dsl-build-log.txt)
[Errors - hangman-build-log.txt](https://github.com/exercism/csharp/files/1871034/Errors.-.hangman-build-log.txt)
[Errors - react-build-log.txt](https://github.com/exercism/csharp/files/1871035/Errors.-.react-build-log.txt)

**Comment by ErikSchierboom** [comment]
Yes that is indeed odd, but indeed not something we can fix. So if I understand correctly, only the three above mentioned projects fail (which is indeed by design)?
