### ISSUE TITLE
Problem/proposal/solution: Make s set of a side 'all-in-one' TotalExercism.csproj project(s) from exercises.sln with 100+ projects

### ISSUE THREAD

**Issue by ShamilS** [exercism/csharp#530]
**Problem**: _exercises.sln_ solution having currently 100+ projects is unmanageable under VS2017 IDE - it takes "ages" just to load/unload solution/rebuild depedencies/recompile. And there is no way to run xUnit tests by VS2017's _Test Explorer_.

**Proposal**: make 'all-in-one' side project/solution having all the sources of the exercises.sln' projects. Actually it would be better to have three side solutions: 

- the first one combining the sources of the projects, which compile and build well,
- the second one - the sources, which do not compile/build 'by design' requirement of this whole project/idea,
- the third one - having Example.cs instead of '{{problemName}}.cs and probably also having enabled xUnit tests, which are disabled by test code generator.

**Solution**: I have made (generated) two sample side 'all-in-one' projects.  Check the current sources here:  [All Projects Sources in One Solution](https://tinyurl.com/y9ohw764), where

 - _TotalExercism_Generated.sln_ belongs to the first type of 'all-in-one' side projects and

![total exercism generated solution xunit test results](https://user-images.githubusercontent.com/2162601/38248804-44e38408-3752-11e8-95bf-176efe1485bd.png)

 - _TotalExercism_Generated_Examples.sln_ belongs to the third type of 'all-in-one' side projects.

![total exercism generated examples solution xunit test results](https://user-images.githubusercontent.com/2162601/38248746-26ba4e8a-3752-11e8-8ae9-683f73f5c850.png)

The sources/projects, which currently do not compile/build are temporarily excluded from these projects.

**Comment by ErikSchierboom** [comment]
I understand what you are aiming to do, but as the exercises themselves are all stand-alone applications, editing everything from a single solution is not the desired workflow. Also, some projects used to have interferring types, which meant that they couldn't be compiled in the same solution. Another issue you mention is the usage of the `Example`/non-Example files. 

To workaround these issues, we have added a build script in the root of the project's folder. With this script, you can verify if an exercise is correct by running `build.ps1 --exercise=<name>` on Windows or `build.sh --exercise=<name>` on Unix systems. This build script will do several things:

1. It will check to see if the exercise's project builds successfully.
1. It will verify if the example implementation passes all the tests.

By using this build script, there is no real need for a solution file. In fact, there is an argument to be made for removing the solution file altogether, as it only causes confusion.

**Comment by ShamilS** [comment]
Yes, then the solution file for 100+ projects should be better removed altogether.

Although, in my opinion, running the tests via VS2017 Test Explorer in 'all-in-one' solution is rather useful option - it's a compact and a visual representation how well all the tests perform, it's possible to compare the execution time for different tests (from different problems' solutions) to find more optimal coding methods etc.

**Comment by ErikSchierboom** [comment]
We used to have different solutions as you suggested, but it ended up not being useful at all hence we removed them. I'd be happy to take a PR that also removes this last solution file.

**Comment by ShamilS** [comment]
Well, if there is no better alternative in your opinion, then I'd leave the current solution as is, maybe commenting it that it's left just as an overview.

**Comment by ErikSchierboom** [comment]
Okay, I'll close this issue then.
