### ISSUE TITLE
Implement 'Binary' generator and solution

### ISSUE THREAD

**Issue by ShamilS** [exercism/csharp#534]
I've started to work on subject using its [description](https://github.com/exercism/problem-specifications/blob/master/exercises/binary/description.md) and [canonical data set](https://github.com/exercism/problem-specifications/blob/master/exercises/binary/canonical-data.json).

**Comment by ErikSchierboom** [comment]
@ShamilS Ah, you've found a bug in the unimplemented listing. It doesn't take into account deprecated exercises (of which there are four: binary, trinary, octal and hexadecimal). Sorry about that.

**Comment by ShamilS** [comment]
@ErikSchierboom  Yes, I have found it's marked as deprecated.
And before reading this your post I have just got it implemented and tested OK replacing manually prepared tests. 
Never mind - I'd take 'binary-search-tree'. Please open an issue for it.
Thank you.

**Comment by ErikSchierboom** [comment]
@ShamilS Issue #536 has been created.
