### ISSUE TITLE
Add proverb generator

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#546]
If you want to implement this exercise, please note that you need to ensure the test cases are generated based on the input.

Here's the exercise description:
https://github.com/exercism/problem-specifications/blob/master/exercises/proverb/description.md

Here's the test case data:
https://github.com/exercism/problem-specifications/blob/master/exercises/proverb/canonical-data.json

**Comment by ShamilS** [comment]
@ErikSchierboom  I will take it.

**Comment by ShamilS** [comment]
@ErikSchierboom [PR is here.](https://github.com/exercism/csharp/pull/561)

**Comment by ErikSchierboom** [comment]
Closed by #561.
