### ISSUE TITLE
Add sublist generator

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#551]
If you want to implement this exercise, please note that you need to ensure the test cases are generated based on the input.

Here's the exercise description:
https://github.com/exercism/problem-specifications/blob/master/exercises/sublist/description.md

Here's the test case data:
https://github.com/exercism/problem-specifications/blob/master/exercises/sublist/canonical-data.json

**Comment by ShamilS** [comment]
[PR is here.](https://github.com/exercism/csharp/pull/562)

**Comment by robkeim** [comment]
Solved by #562
