### ISSUE TITLE
Add twelve-days generator

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#552]
If you want to implement this exercise, please note that you need to ensure the test cases are generated based on the input.

Here's the exercise description:
https://github.com/exercism/problem-specifications/blob/master/exercises/twelve-days/description.md

Here's the test case data:
https://github.com/exercism/problem-specifications/blob/master/exercises/twelve-days/canonical-data.json

**Comment by ShamilS** [comment]
I will make it.

**Comment by ErikSchierboom** [comment]
Closed by #564.
