### ISSUE TITLE
Calling .SetInputParameters result in run-time error in some generators

### ISSUE THREAD

**Issue by ShamilS** [exercism/csharp#567]
Similar to #566 but for .SetInputParameters

The list of the generators to check:

    .\exercism\csharp\generators\Exercises\BookStore.cs(11):             canonicalDataCase.SetInputParameters("basket");
    .\exercism\csharp\generators\Exercises\Bowling.cs(26):               canonicalDataCase.SetInputParameters();
    .\exercism\csharp\generators\Exercises\ComplexNumbers.cs(34):        canonicalDataCase.SetInputParameters(GetInputParameters(canonicalDataCase, constructorParamName));
    .\exercism\csharp\generators\Exercises\Matrix.cs(13):                canonicalDataCase.SetInputParameters("index");
    .\exercism\csharp\generators\Exercises\QueenAttack.cs(71):           canonicalDataCase.SetInputParameters("X", "Y");
    .\exercism\csharp\generators\Exercises\SpaceAge.cs(12):              canonicalDataCase.SetInputParameters();
    .\exercism\csharp\generators\Exercises\Triangle.cs(20):              data.SetInputParameters("sides");

Correct usage of .SetInputParameters can be found in [Meetup.cs](https://github.com/exercism/csharp/blob/master/generators/Exercises/Meetup.cs)

**Comment by ErikSchierboom** [comment]
Being worked on as part of #568.
