### ISSUE TITLE
Consider adding hint to each exercise explaining how to test the code

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#600]

**Comment by robkeim** [comment]
@ErikSchierboom can you elaborate more on this? Each exercise already provides a test suite which should guide people in *what* to test, but I'm not sure what additional information we would give about the *how* (that's relevant to everyone and not specific to certain setups, editors, etc). Could you give an example for one of the exercises of what you had in mind? I think that would help me understand more clearly what content you're looking for.

**Comment by ErikSchierboom** [comment]
Sure. Basically, this issue is about how much help should we give people to get started with testing. Say I am a new user and I check out the first exercise. Should we expect people to know how to run the tests, or should we provide a link to our testing documentation page to help explain? I'm not sure people will read the website fully (where the testing is explained), maybe some people only read the README? Furthermore, do people understand that in order to progress, the Skip attribute has to be removed from subsequent tests?

I'm not saying we should, but I do want to start a little discussion here on if we should.

**Comment by jpreese** [comment]
I would be in favor of adding some additional verbiage to the README on how we intend for users to solve the problems. If even as simple as linking to https://github.com/exercism/csharp/blob/master/docs/TESTS.md

I'm not seeing anywhere on the exercism v2 website where this document is displayed, and we definitely don't want users having to depend on going to GitHub for information.

**Comment by robkeim** [comment]
@ErikSchierboom ah ok I see what you're saying now. I was thinking of specific hints for each tests on how to approach the tests for that specific exercise, instead of something general that's applicable to all exercises.

I think that anything we can do to help reduce the barrier to entry with people getting started on the track is very valuable, and this definitely seems like it would help.

**Comment by ErikSchierboom** [comment]
Closed by #615.
