### ISSUE TITLE
Consider calling out DateTime.IsLeapYear() for Leap exercise

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#610]
Was doing some mentoring and noticed our Leap instructions just say 

>If your language provides a method in the standard library that does this look-up, pretend it doesn't exist and implement it yourself.

I think since we have the ability to be specific, since the README exists within the C# repo, we can explicitly call out DateTime.IsLeapYear().  I think it'd be a good learning opportunity, highlighting this function exists in the first place. As well as makes it a bit more personable to the C# track.

**Comment by ErikSchierboom** [comment]
Good idea!
