### ISSUE TITLE
Hacktoberfest is just around the corner

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#627]
This seems like it's going to be a bit of a dry year for the csharp repo. Last year we had tons of generators to write, this time around.. not so much. Is there anything we're capable of doing? Otherwise we can just direct participant to other repos.

**Comment by jpreese** [comment]
Discussion started! Closing.

**Comment by ErikSchierboom** [comment]
I've just started creating issues with the hacktoberfest label! Lots more (and simpler ones) are coming!

**Comment by ErikSchierboom** [comment]
Check it out: https://github.com/exercism/csharp/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest
