### ISSUE TITLE
Add laziness instructions to accumulate README

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#628]
Accumulate is not per se about laziness, and this is reflected in the README. The tests suite contains a test that verifies that the implementation is evaluated lazily. We should add a section to the README to mention the laziness property that is being tested.

Note that to update the README, one should create a patch file [here](https://github.com/exercism/csharp/tree/master/config/patches) and then run the `update-docs.sh` command in the root.

**Comment by robkeim** [comment]
Had I seen the label Octoberfest before having implemented the change I would have left this available for someone else, my bad.

**Comment by ErikSchierboom** [comment]
> Hello, could I start to work on this?

Yeah sure! Are the instructions clear (creating a patch file and such)?

**Comment by B1tF8er** [comment]
I have not created patch files before, but the instructions are clear

**Comment by ErikSchierboom** [comment]
Okay great! Good luck with it.
