### ISSUE TITLE
Add more test for two fer exercise

### ISSUE THREAD

**Issue by joostas** [exercism/csharp#630]
I suggest to add several unit tests in exercise https://github.com/exercism/csharp/tree/master/exercises/two-fer
 for these cases: 
* passing empty string 
* passing `null` value. 

What do you think?

**Comment by ErikSchierboom** [comment]
Hi! The tests for `two-fer` are automatically generated based on canonical data: https://github.com/exercism/problem-specifications/blob/master/exercises/two-fer/canonical-data.json This canonical data does not include such cases, so I am disinclined to add those cases.

**Comment by joostas** [comment]
Ok. Understood. Thanks for quick replay.
