### ISSUE TITLE
Allow generator to output outdated exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#631]
It would be quite useful if the generator would allow for displaying the exercises that have a test suite that is based on an outdated version of the canonical data.

To list these outdated exercises, one should be able to do `dotnet run -s Outdated`.

The generators code can be found [here](https://github.com/exercism/csharp/tree/master/generators), and the documentation can be found [here](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md).

**Comment by robkeim** [comment]
Yes, this would be very helpful indeed. One minor nit, the param name should be lower case to be consistent with the other param names:
https://github.com/exercism/csharp/blob/master/generators/Options.cs

**Comment by robkeim** [comment]
Ah the argument flags are lower case `-s` in this case but this argument is PascalCase... makes sense :)

**Comment by ErikSchierboom** [comment]
:)

**Comment by EarthlingRich** [comment]
I will take a look if I can add this.

**Comment by ErikSchierboom** [comment]
Great! Good luck! For reference: each test file that was generated from canonical data has the following header line format:

> // This file was auto-generated based on version X.X.X of the canonical data.

If you parse this line from generated test files, you should be able to compare that to the canonical data version.

**Comment by ErikSchierboom** [comment]
Closed by #674.
