### ISSUE TITLE
Implement new exercise: rest-api

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#632]
There is a new exercise, [rest-api](https://github.com/exercism/problem-specifications/blob/master/exercises/rest-api/description.md), which data can be found here: https://github.com/exercism/problem-specifications/tree/master/exercises/rest-api

To implement the `rest-api` exercise, the following needs to be done:

- Create a directory for the new exercise in the `exercises` directory (note: this has to match the exact exercise name).
- Add a new entry to the [config.json](https://github.com/exercism/csharp/blob/master/config.json) file.
- Create a generator to automatically convert the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/rest-api/canonical-data.json) to a test file. For more information on how to do this, check the [generators docs](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md).
- Create a stub implementation file that contains the code necessary to compile (which are the methods called by the test file), but lacks an implementation. (see [this example](https://github.com/exercism/csharp/blob/master/exercises/two-fer/TwoFer.cs)).
- Create an implementation file that passes all the tests.
- Create a project file for the project (you can probably best copy and modify one of the existing projects).

**Comment by yvincent** [comment]
I'll try this one.

**Comment by ErikSchierboom** [comment]
That would be great!

**Comment by ErikSchierboom** [comment]
Closed by #687.
