### ISSUE TITLE
Implement new exercise: affine-cipher

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#633]
There is a new exercise, [affine-cipher](https://github.com/exercism/problem-specifications/blob/master/exercises/affine-cipher/description.md), which data can be found here: https://github.com/exercism/problem-specifications/tree/master/exercises/affine-cipher

To implement the `affine-cipher` exercise, the following needs to be done:

- Create a directory for the new exercise in the `exercises` directory (note: this has to match the exact exercise name).
- Add a new entry to the [config.json](https://github.com/exercism/csharp/blob/master/config.json) file.
- Create a generator to automatically convert the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/affine-cipher/canonical-data.json) to a test file. For more information on how to do this, check the [generators docs](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md).
- Create a stub implementation file that contains the code necessary to compile (which are the methods called by the test file), but lacks an implementation. (see [this example](https://github.com/exercism/csharp/blob/master/exercises/two-fer/TwoFer.cs)).
- Create an implementation file that passes all the tests.
- Create a project file for the project (you can probably best copy and modify one of the existing projects).

**Comment by davidelettieri** [comment]
Hi Erik, I would like to help with this issue. If that's ok I'll fork the project and work on it.

**Comment by davidelettieri** [comment]
Great! Working on it. 

I could be useful to note that without the entry in the config.json file the generation for the test cases does not work ie running 
```
dotnet run -e affine-cipher
```
does not create the test cases file

**Comment by ErikSchierboom** [comment]
Thanks for letting me know! I'll update the description.

**Comment by ErikSchierboom** [comment]
Closed by #688.
