### ISSUE TITLE
Add generator for exercise: sgf-parsing

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#635]
The [sgf-parsing](https://github.com/exercism/problem-specifications/blob/master/exercises/sgf-parsing/description.md) now has [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/sgf-parsing/canonical-data.json). We should replace the existing, manually crafted test suite with on that is automatically generated based on the canonical data.

To implement a generator for the `sgf-parsing` exercise, the following needs to be done:

- Create a generator to automatically convert the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/sgf-parsing/canonical-data.json) to a test file. For more information on how to do this, check the [generators docs](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md).
- Make sure the implementation file passes all the tests (hint: you can verify this by running `./build.sh --exercise=sgf-parsing` or `.\build.ps1 -Exercise sgf-parsing`.

**Comment by deniscapeto** [comment]
Can I take this one too?

**Comment by ErikSchierboom** [comment]
Sure! This is a bit more work, as you will have to create a new generator from scratch. More work, but more fun I think!

**Comment by deniscapeto** [comment]
Hi @ErikSchierboom , As far as I understand I should also update the example file for this exercise since this doesn't implement IEquatable properly to compare the result properly. Is that Right?

**Comment by ErikSchierboom** [comment]
Hi! You should update the Example file to make sure it passes all the tests. So if that means implementing IEquatable, by all means do that.

**Comment by deniscapeto** [comment]
Hi Erik, The test generator is working fine. I'm still updating the example file. There's one test that is not passing ("Escaped_property"). Just to say i'm working on it.

**Comment by ErikSchierboom** [comment]
Great, and thanks for the feedback!

**Comment by deniscapeto** [comment]
Erik, I've just submitted a PR. Please let me know if there is something I can help.

**Comment by ErikSchierboom** [comment]
Closed by #694
