### ISSUE TITLE
Update test suite for exercise: robot-simulator 

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#636]
The `robot-simulator` exercise's [test suite](https://github.com/exercism/csharp/blob/master/exercises/robot-simulator/RobotSimulatorTest.cs) is automatically generated using its [test generator](https://github.com/exercism/csharp/blob/master/generators/Exercises/Generators/RobotSimulator.cs). This test generator converts the `robot-simulator`'s [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/robot-simulator/canonical-data.json) into the test suite just mentioned.

The canonical data for the `robot-simulator` exercise has been updated since the test suite was last generated. We should be updating the test suite to the latest version. To do this, one should:

- Run the test generator for the exercise. This is done by opening a command prompt and running: `dotnet run -e robot-simulator`.
- At this point, you should check to see what the updated test suite looks like. There are basically two options: one, the test generator was compatible with the updated canonical data and the test suite was updated and still has the same structure. The second option is that the test generator could not process the changed canonical data, in which case the generator has to be modified. In that case, you should check out the [generator docs](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md) in which the generators setup is explained in detail.
- Finally, please make sure that the [example implementation](https://github.com/exercism/csharp/blob/master/exercises/robot-simulator/Example.cs) passes all the tests. You can verify this by opening a command prompt in the root directory and running `./build.sh --exercise=robot-simulator` or `.\build.ps1 -Exercise robot-simulator`, depending on your operating system.

**Comment by igorluna** [comment]
Nice one, may i take a swing at it? 🤖

**Comment by ErikSchierboom** [comment]
Absolutely! I think this will require a bit of change in the test generator, as the updated canonical data only has a single property that is tested (`move`), so I expect that you'll be able to remove some code in the generator.

**Comment by abecerramatias** [comment]
Can I try it too?

**Comment by igorluna** [comment]
I'm having some difficulties, don't mind someone else jumping in!

**Comment by jpreese** [comment]
@abecerramatias you should be all set now. It looks like the canonical data had an error. 

I approved a fix for it in another repository, so the data should be correct going forward.

**Comment by ErikSchierboom** [comment]
Closed by #691
