### ISSUE TITLE
Update test suite for exercise: variable-length-quantity

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#650]
The `variable-length-quantity` exercise's [test suite](https://github.com/exercism/csharp/blob/master/exercises/variable-length-quantity/VariableLengthQuantityTest.cs) is automatically generated using its [test generator](https://github.com/exercism/csharp/blob/master/generators/Exercises/Generators/VariableLengthQuantity.cs). This test generator converts the `variable-length-quantity`'s [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/variable-length-quantity/canonical-data.json) into the test suite just mentioned.

The canonical data for the `variable-length-quantity` exercise has been updated since the test suite was last generated. We should be updating the test suite to the latest version. To do this, one should:
- Run the test generator for the exercise. This is done by opening a command prompt in the `generators` directory and running: `dotnet run -e variable-length-quantity`.
- At this point, you should check to see what the updated test suite looks like. There are basically two options: one, the test generator was compatible with the updated canonical data and the test suite was updated and still has the same structure. The second option is that the test generator could not process the changed canonical data, in which case the generator has to be modified. In that case, you should check out the [generator docs](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md) in which the generators setup is explained in detail.
- Finally, please make sure that the [example implementation](https://github.com/exercism/csharp/blob/master/exercises/variable-length-quantity/Example.cs) passes all the tests. You can verify this by opening a command prompt in the root directory and running `./build.sh --exercise=variable-length-quantity` or `.\build.ps1 -Exercise variable-length-quantity`, depending on your operating system.

**Comment by nicolastarzia** [comment]
Hey @ErikSchierboom, 
The test generator cannot process the changed canonical data.

I will try to fix that problem, ok?

**Comment by ErikSchierboom** [comment]
> I will try to fix that problem, ok?

That would be great!

**Comment by nicolastarzia** [comment]
@ErikSchierboom,
Do you know if we have something like "Assert.Equal(expected, actual, message)"?

**Comment by nicolastarzia** [comment]
@ErikSchierboom, please review!

**Comment by ErikSchierboom** [comment]
Closed by #671.
