### ISSUE TITLE
Update test suite for exercise: collatz-conjecture

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#655]
The `collatz-conjecture` exercise's [test suite](https://github.com/exercism/csharp/blob/master/exercises/collatz-conjecture/CollatzConjectureTest.cs) is automatically generated using its [test generator](https://github.com/exercism/csharp/blob/master/generators/Exercises/Generators/CollatzConjecture.cs). This test generator converts the `collatz-conjecture`'s [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/collatz-conjecture/canonical-data.json) into the test suite just mentioned.

The canonical data for the `collatz-conjecture` exercise has been updated since the test suite was last generated. We should be updating the test suite to the latest version. To do this, one should:
- Run the test generator for the exercise. This is done by opening a command prompt in the `generators` directory and running: `dotnet run -e collatz-conjecture`.
- At this point, you should check to see what the updated test suite looks like. There are basically two options: one, the test generator was compatible with the updated canonical data and the test suite was updated and still has the same structure. The second option is that the test generator could not process the changed canonical data, in which case the generator has to be modified. In that case, you should check out the [generator docs](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md) in which the generators setup is explained in detail.
- Finally, please make sure that the [example implementation](https://github.com/exercism/csharp/blob/master/exercises/collatz-conjecture/Example.cs) passes all the tests. You can verify this by opening a command prompt in the root directory and running `./build.sh --exercise=collatz-conjecture` or `.\build.ps1 -Exercise collatz-conjecture`, depending on your operating system.

**Comment by FizzBuzz791** [comment]
@ErikSchierboom I've run this as follows... I *think* that means everything is fine, but there was no output from the `dotnet` command, so I'm a bit unsure.

![image](https://user-images.githubusercontent.com/2747764/46395286-6d35f880-c71e-11e8-9341-ec4a10539b37.png)

**Comment by ErikSchierboom** [comment]
Aha! I figured it out. You are running the command in the wrong directory :) You should be running the command in the `generators` directory, which the instructions failed to mention.

**Comment by FizzBuzz791** [comment]
Aha! That works much better, thanks! For this one, it just updated the "This file was auto-generated..." comment to say `version 1.2.1` instead of `version 1.2.0`. Is that PR worthy?
