### ISSUE TITLE
Test Suite doesn't run all tests

### ISSUE THREAD

**Issue by FizzBuzz791** [exercism/csharp#680]
I'm not sure what the correct process is here, I've thought of two scenarios to fix the fact that the website honors the `Skip` tag and only runs the first test in the suite;

1. The user should submit the test suite along with the solution file(s).
1.1. This is rife with loopholes though, as you could submit as passing test. You're only cheating yourself, but I'm sure some will do it, either intentionally or unintentionally.
1.2. I've tried doing this; `exercism submit bob\Bob.cs bob\BobTest.cs` and it doesn't update the test file.
2. The test suite the user download remains as-is but the one that gets run automatically when an exercise is submitted runs all the tests in the suite.
2.1. Haven't looked into exactly how this would work yet, but obviously it would have to remove the `Skip` tags...

**Comment by ErikSchierboom** [comment]
> but the one that gets run automatically when an exercise is submitted runs all the tests in the suite.

There is no automatic running of tests, this is not something that is supported at the moment. There has been some discussion on how to enable this on the [exercism issues](https://github.com/exercism/exercism/issues) page, which is the correct place for this discussion.

It would be great to have though!
