### ISSUE TITLE
Check example implementation file' performance

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#706]
It might be interesting to do some type of performance analysis of the example implementations, to see where the bottlenecks are (if there are any). For example, if one test runs for 1,5 minute, it can significantly slow down the entire build.

**Comment by bmeverett** [comment]
I ran all the tests in Visual Studio and it seems the Alphametrics test takes over a minute to run. The next highest test is the Palindrome that takes about 12 seconds. The remaining tests take a second or less to run.

![image](https://user-images.githubusercontent.com/3941006/47293424-1e220b80-d5d8-11e8-968a-2274ecbe4176.png)
![image](https://user-images.githubusercontent.com/3941006/47293432-21b59280-d5d8-11e8-82c9-79da5e4f5e99.png)

**Comment by ErikSchierboom** [comment]
Great! This is the first step, now to speed things up :) Are you interested in trying to improve the performance? If not, feel free to say so.

**Comment by bmeverett** [comment]
I can give it a shot!

**Comment by bmeverett** [comment]
So, I'm not seeing any noticeable performance improvements, so if someone else wants to give this a shot go for it.

**Comment by ErikSchierboom** [comment]
No problem, thanks for trying!

**Comment by ErikSchierboom** [comment]
I'm working on this. I've got the alphametics time down to 20-25 seconds.

**Comment by ErikSchierboom** [comment]
PR #719 improved the performance. The net result is that running the tests is about 1,5 minute faster.

Old situation:

```
Task                           Duration            
---------------------------------------------------
BuildGenerators                00:00:11.2731591    
Clean                          00:00:00.0018651    
CopyExercises                  00:00:00.1278072    
EnableAllTests                 00:00:00.0625292    
TestRefactoringProjects        00:00:18.0416240    
ReplaceStubWithExample         00:00:00.0316201    
TestUsingExampleImplementation 00:06:02.4587236    
Default                        00:00:00.0003355    
---------------------------------------------------
Total:                         00:06:31.9976638  
```

New situation:

```
Task                           Duration            
---------------------------------------------------
BuildGenerators                00:00:12.5509480    
Clean                          00:00:00.0018638    
CopyExercises                  00:00:00.0780796    
EnableAllTests                 00:00:00.0623837    
TestRefactoringProjects        00:00:17.7578098    
ReplaceStubWithExample         00:00:00.0296463    
TestUsingExampleImplementation 00:04:38.2559311    
Default                        00:00:00.0002540    
---------------------------------------------------
Total:                         00:05:08.7369163   
```
