### ISSUE TITLE
Implement new exercise: high-scores

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#709]
There is a new exercise, [high-scores](https://github.com/exercism/problem-specifications/blob/master/exercises/high-scores/description.md), which data can be found here: https://github.com/exercism/problem-specifications/tree/master/exercises/high-scores

To implement the `high-scores` exercise, the following needs to be done:

- Create a directory for the new exercise in the `exercises` directory (note: this has to match the exact exercise name).
- Add a new entry to the [config.json](https://github.com/exercism/csharp/blob/master/config.json) file.
- Create a generator to automatically convert the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/high-scores/canonical-data.json) to a test file. For more information on how to do this, check the [generators docs](https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md).
- Create a stub implementation file that contains the code necessary to compile (which are the methods called by the test file), but lacks an implementation. (see [this example](https://github.com/exercism/csharp/blob/master/exercises/two-fer/TwoFer.cs)).
- Create an implementation file that passes all the tests.
- Create a project file for the project (you can probably best copy and modify one of the existing projects).

Note that the implementation should work with instance methods, not static methods.

**Comment by B1tF8er** [comment]
I will take this

**Comment by ErikSchierboom** [comment]
Note that this exercise should be implemented using a non-static, instance class. The scores should be passed as a constructor parameter, and the methods should be instance methods.

**Comment by B1tF8er** [comment]
@ErikSchierboom sorry, please go ahead with the other PR

**Comment by ErikSchierboom** [comment]
@B1tF8er No problem! Thanks for the speedy response.
