### ISSUE TITLE
Building with solution doesn't let you run individual exercises 

### ISSUE THREAD

**Issue by bmeverett** [exercism/csharp#710]
In #698 we changed the build to use the solution file. If you build an individual exercise using `.\build.ps1 -Exercise darts` the `Exercises.sln` doesn't get copied over

**Comment by ErikSchierboom** [comment]
Great catch! We should definitely fix this. Would you be willing to create a PR for this?

**Comment by bmeverett** [comment]
Yep I was working on it, thought I could just copy the solution over but it has references to all the projects that don't exist. May just have to check the exercise flag and build the project
