### ISSUE TITLE
Simplify robot-simulator exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#721]
There are several things we can do to improve the robot-simulator exercise:

- Remove the Position struct and just store the X and Y values directly on the class.
- Rename the tested class from `RobotSimulator` to `Robot`.

**Comment by robkeim** [comment]
What is the rationale behind wanted to make the exercise name no longer aligned with the class name? If we go down that route at what level do we make the change? Do we only change the class name or do we change the file name and underlying generator functionality as well to generate in another location?

**Comment by ErikSchierboom** [comment]
> What is the rationale behind wanted to make the exercise name no longer aligned with the class name? If we go down that route at what level do we make the change? Do we only change the class name or do we change the file name and underlying generator functionality as well to generate in another location?

Well, to me it's just that having it named RobotSimulator felt a bit odd. Robot looked like a more reasonable objective to me, but if you think RobotSimulator is fine, we can just leave it like that. My main reason for this issue was the removal of the Coordinate struct.

**Comment by ErikSchierboom** [comment]
I do agree that there is the discrepancy between the file name and the class name, so maybe changing it to Robot was a bad suggestion?

**Comment by robkeim** [comment]
Let's keep the new name for now (since the PR is done and ready) and if it causes confusion in the future we can always revisit that decision.

**Comment by ErikSchierboom** [comment]
@robkeim Okay, I'll merge then. Thanks for doing the PR!

**Comment by ErikSchierboom** [comment]
@robkeim I'll ask some of the other maintainers how they feel. If they feel otherwise, I'll create a new PR.
