### ISSUE TITLE
Use long instead of ulong in space-age exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#722]
This make the exercise progress a bit better in the track, as long can be thought of as an extension of int, without introducing the unsigned/signed differences.

**Comment by ErikSchierboom** [comment]
Ouch, I must have checked the wrong file (my implementation). Whoops! Thanks for being vigilant.

**Comment by robkeim** [comment]
No worries, I was going to grab this one which is why I took a look.
