### ISSUE TITLE
Use decimal type for money related exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#734]
Any exercises related to money should use the `decimal` type instead of `double`or `float` (see [this page](https://stackoverflow.com/questions/693372/what-is-the-best-data-type-to-use-for-money-in-c). Out of the top of my head, these exercises will include (but there may be more):

- book-store
- bank-account

**Comment by AndrewYHuang** [comment]
May I take this issue?

**Comment by ErikSchierboom** [comment]
Sure!

**Comment by AndrewYHuang** [comment]
Ah, thanks for pointing that out!

**Comment by AndrewYHuang** [comment]
Should Ledger be changed to use `decimal`? I'm not too sure as it's a refactoring exercise.

**Comment by ErikSchierboom** [comment]
Yes please!

**Comment by ErikSchierboom** [comment]
Closed by #737.
