### ISSUE TITLE
clock: test suite should verify immutability

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#742]
Some solutions have the `Add` and `Subtract`methods modify the current instance. This is not the goal of the exercise. We should add tests to verify this.

**Comment by ErikSchierboom** [comment]
The best approach is to modify the test generator: https://github.com/exercism/csharp/blob/master/generators/Exercises/Generators/Clock.cs. Within the test generator, you are then able to add additional methods. For an example, see the grep test generator: https://github.com/exercism/csharp/blob/e3142cb43b2ff0abfc1b9bcb8288500910b41695/generators/Exercises/Generators/Grep.cs

**Comment by vgrigoriu** [comment]
There were a couple of exercises (besides Clock) that had new test cases in the canonical data. What's the process for refreshing the tests, does it happen automatically?

**Comment by vgrigoriu** [comment]
I'll give it a try.
