### ISSUE TITLE
#753 modified README.md, probably should have modified .meta/hints.md

### ISSUE THREAD

**Issue by rpottsoh** [exercism/csharp#754]
I am assuming `configlet` was used to generate [README](https://github.com/exercism/csharp/blob/master/exercises/clock/README.md) which pulls from [hints.md](https://github.com/exercism/csharp/blob/master/exercises/clock/.meta/hints.md).  The text revised by #753 originates from `hints.md`.  A new PR is probably needed to repeat the changes made in #753 in `hints.md`.

**Comment by ErikSchierboom** [comment]
Ah, you are completely right! Great catch.

**Comment by rpottsoh** [comment]
No problem.  I noticed it by accident because I was curious how the track was adapting to the recent update to High Scores.

**Comment by ErikSchierboom** [comment]
Closed by #758.
