### ISSUE TITLE
Install Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#765]
Dependabot checks on dependencies and keeps them up-to-date. It generates a PR when any of the dependencies is out-of-date which triggers CI, and if that's green we can merge the update. I use it in another project and find it convenient. I think it's a lightweight to get up and running.

Here's more info:
https://github.com/marketplace/dependabot/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4zNTQ=#pricing-and-setup

Thoughts @ErikSchierboom and @jpreese?

**Comment by ErikSchierboom** [comment]
I like it a lot!

**Comment by robkeim** [comment]
Ok, I'm not sure who needs to approve but I just sent a "request" and got this message:

> A request to install Dependabot has been submitted on the @exercism account.

**Comment by ErikSchierboom** [comment]
I think @kytrinyx will be the one that receives the request.

**Comment by robkeim** [comment]
Ok, @kytrinyx I've requested to give dependabot (a third party tool) read/write access to the csharp and fsharp repositories in order to help keep project dependencies of the project up-to-date. Running it is free for open source software.

**Comment by kytrinyx** [comment]
I got the request! I created a dependabot account, and tried adding the C# and F# track repos to it, and got the following error:

<img width="915" alt="screen shot 2019-02-26 at 11 13 00 am" src="https://user-images.githubusercontent.com/276834/53436099-9c901f00-39b7-11e9-839b-9ef6cef5cb2a.png">

**Comment by ErikSchierboom** [comment]
@robkeim Do you know how that works? I know for a fact that we have csproj and fsproj files in our repositories.

**Comment by robkeim** [comment]
Thanks @kytrinyx for the help. This is enough to get me unblocked and I should be able to do the rest on my side!

@ErikSchierboom it looks like we need a configuration file to specify the location of the [cf]sproj's we want to track it doesn't by default go looking around in the code to find them. So I think we'd need that configuration file as well as a script that could generate the list of [cf]sproj's in the solution in order to make it easy to maintain. I'll dig into this and see what I can come up with.

**Comment by robkeim** [comment]
@ErikSchierboom I tested this and got it working on the generators project with this PR:
https://github.com/exercism/csharp/pull/770

It ran and found four out-of-date dependencies and here's an example PR it created to bump a dependency version:
https://github.com/exercism/csharp/pull/771

Now, I'll try to come up with a script to generate the config.yml file automatically.

**Comment by ErikSchierboom** [comment]
It seems to be working nicely! Thanks a lot.

**Comment by ErikSchierboom** [comment]
Closed by #775 and #770.
